# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/daemon/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/daemon/messages.proto',
  package='solipsis.gkk.daemon',
  syntax='proto3',
  serialized_pb=_b('\n\x19rpc/daemon/messages.proto\x12\x13solipsis.gkk.daemon\">\n\x0bPingRequest\x12/\n\x06params\x18\x01 \x01(\x0b\x32\x1f.solipsis.gkk.daemon.PingParams\"K\n\nPingParams\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0f\n\x07\x64isplay\x18\x02 \x01(\x08\x12\x0b\n\x03pin\x18\x03 \x01(\x08\x12\x12\n\npassphrase\x18\x04 \x01(\x08\"X\n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x36\n\x0c\x61uth_request\x18\x02 \x01(\x0b\x32 .solipsis.gkk.daemon.AuthRequest\"\xa5\x01\n\x0b\x41uthRequest\x12\x32\n\x06\x62utton\x18\x01 \x01(\x0b\x32\".solipsis.gkk.daemon.ButtonRequest\x12,\n\x03pin\x18\x02 \x01(\x0b\x32\x1f.solipsis.gkk.daemon.PinRequest\x12\x34\n\x04pass\x18\x03 \x01(\x0b\x32&.solipsis.gkk.daemon.PassphraseRequest\"\x0f\n\rButtonRequest\"\x0c\n\nPinRequest\"\x13\n\x11PassphraseRequest\"\xa9\x01\n\x0c\x41uthResponse\x12\x33\n\x06\x62utton\x18\x01 \x01(\x0b\x32#.solipsis.gkk.daemon.ButtonResponse\x12-\n\x03pin\x18\x02 \x01(\x0b\x32 .solipsis.gkk.daemon.PinResponse\x12\x35\n\x04pass\x18\x03 \x01(\x0b\x32\'.solipsis.gkk.daemon.PassphraseResponse\"\x10\n\x0e\x42uttonResponse\"\x1a\n\x0bPinResponse\x12\x0b\n\x03pin\x18\x01 \x01(\t\"(\n\x12PassphraseResponse\x12\x12\n\npassphrase\x18\x01 \x01(\t2U\n\x06\x44\x61\x65mon\x12K\n\x04Ping\x12 .solipsis.gkk.daemon.PingRequest\x1a!.solipsis.gkk.daemon.PingResponseB\x08Z\x06\x64\x61\x65monb\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='solipsis.gkk.daemon.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='solipsis.gkk.daemon.PingRequest.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=112,
)


_PINGPARAMS = _descriptor.Descriptor(
  name='PingParams',
  full_name='solipsis.gkk.daemon.PingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='solipsis.gkk.daemon.PingParams.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display', full_name='solipsis.gkk.daemon.PingParams.display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='solipsis.gkk.daemon.PingParams.pin', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passphrase', full_name='solipsis.gkk.daemon.PingParams.passphrase', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=189,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='solipsis.gkk.daemon.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='solipsis.gkk.daemon.PingResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_request', full_name='solipsis.gkk.daemon.PingResponse.auth_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=279,
)


_AUTHREQUEST = _descriptor.Descriptor(
  name='AuthRequest',
  full_name='solipsis.gkk.daemon.AuthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button', full_name='solipsis.gkk.daemon.AuthRequest.button', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='solipsis.gkk.daemon.AuthRequest.pin', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pass', full_name='solipsis.gkk.daemon.AuthRequest.pass', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=447,
)


_BUTTONREQUEST = _descriptor.Descriptor(
  name='ButtonRequest',
  full_name='solipsis.gkk.daemon.ButtonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=464,
)


_PINREQUEST = _descriptor.Descriptor(
  name='PinRequest',
  full_name='solipsis.gkk.daemon.PinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=478,
)


_PASSPHRASEREQUEST = _descriptor.Descriptor(
  name='PassphraseRequest',
  full_name='solipsis.gkk.daemon.PassphraseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=499,
)


_AUTHRESPONSE = _descriptor.Descriptor(
  name='AuthResponse',
  full_name='solipsis.gkk.daemon.AuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button', full_name='solipsis.gkk.daemon.AuthResponse.button', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='solipsis.gkk.daemon.AuthResponse.pin', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pass', full_name='solipsis.gkk.daemon.AuthResponse.pass', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=671,
)


_BUTTONRESPONSE = _descriptor.Descriptor(
  name='ButtonResponse',
  full_name='solipsis.gkk.daemon.ButtonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=673,
  serialized_end=689,
)


_PINRESPONSE = _descriptor.Descriptor(
  name='PinResponse',
  full_name='solipsis.gkk.daemon.PinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin', full_name='solipsis.gkk.daemon.PinResponse.pin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=717,
)


_PASSPHRASERESPONSE = _descriptor.Descriptor(
  name='PassphraseResponse',
  full_name='solipsis.gkk.daemon.PassphraseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='passphrase', full_name='solipsis.gkk.daemon.PassphraseResponse.passphrase', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=759,
)

_PINGREQUEST.fields_by_name['params'].message_type = _PINGPARAMS
_PINGRESPONSE.fields_by_name['auth_request'].message_type = _AUTHREQUEST
_AUTHREQUEST.fields_by_name['button'].message_type = _BUTTONREQUEST
_AUTHREQUEST.fields_by_name['pin'].message_type = _PINREQUEST
_AUTHREQUEST.fields_by_name['pass'].message_type = _PASSPHRASEREQUEST
_AUTHRESPONSE.fields_by_name['button'].message_type = _BUTTONRESPONSE
_AUTHRESPONSE.fields_by_name['pin'].message_type = _PINRESPONSE
_AUTHRESPONSE.fields_by_name['pass'].message_type = _PASSPHRASERESPONSE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingParams'] = _PINGPARAMS
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['AuthRequest'] = _AUTHREQUEST
DESCRIPTOR.message_types_by_name['ButtonRequest'] = _BUTTONREQUEST
DESCRIPTOR.message_types_by_name['PinRequest'] = _PINREQUEST
DESCRIPTOR.message_types_by_name['PassphraseRequest'] = _PASSPHRASEREQUEST
DESCRIPTOR.message_types_by_name['AuthResponse'] = _AUTHRESPONSE
DESCRIPTOR.message_types_by_name['ButtonResponse'] = _BUTTONRESPONSE
DESCRIPTOR.message_types_by_name['PinResponse'] = _PINRESPONSE
DESCRIPTOR.message_types_by_name['PassphraseResponse'] = _PASSPHRASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingParams = _reflection.GeneratedProtocolMessageType('PingParams', (_message.Message,), dict(
  DESCRIPTOR = _PINGPARAMS,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PingParams)
  ))
_sym_db.RegisterMessage(PingParams)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)

AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHREQUEST,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.AuthRequest)
  ))
_sym_db.RegisterMessage(AuthRequest)

ButtonRequest = _reflection.GeneratedProtocolMessageType('ButtonRequest', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONREQUEST,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.ButtonRequest)
  ))
_sym_db.RegisterMessage(ButtonRequest)

PinRequest = _reflection.GeneratedProtocolMessageType('PinRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINREQUEST,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PinRequest)
  ))
_sym_db.RegisterMessage(PinRequest)

PassphraseRequest = _reflection.GeneratedProtocolMessageType('PassphraseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PASSPHRASEREQUEST,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PassphraseRequest)
  ))
_sym_db.RegisterMessage(PassphraseRequest)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), dict(
  DESCRIPTOR = _AUTHRESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.AuthResponse)
  ))
_sym_db.RegisterMessage(AuthResponse)

ButtonResponse = _reflection.GeneratedProtocolMessageType('ButtonResponse', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONRESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.ButtonResponse)
  ))
_sym_db.RegisterMessage(ButtonResponse)

PinResponse = _reflection.GeneratedProtocolMessageType('PinResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINRESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PinResponse)
  ))
_sym_db.RegisterMessage(PinResponse)

PassphraseResponse = _reflection.GeneratedProtocolMessageType('PassphraseResponse', (_message.Message,), dict(
  DESCRIPTOR = _PASSPHRASERESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PassphraseResponse)
  ))
_sym_db.RegisterMessage(PassphraseResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006daemon'))

_DAEMON = _descriptor.ServiceDescriptor(
  name='Daemon',
  full_name='solipsis.gkk.daemon.Daemon',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=761,
  serialized_end=846,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='solipsis.gkk.daemon.Daemon.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAEMON)

DESCRIPTOR.services_by_name['Daemon'] = _DAEMON

# @@protoc_insertion_point(module_scope)
