// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages-eos.proto

package kkproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EosPublicKeyKind int32

const (
	EosPublicKeyKind_EOS    EosPublicKeyKind = 0
	EosPublicKeyKind_EOS_K1 EosPublicKeyKind = 1
	EosPublicKeyKind_EOS_R1 EosPublicKeyKind = 2
)

var EosPublicKeyKind_name = map[int32]string{
	0: "EOS",
	1: "EOS_K1",
	2: "EOS_R1",
}
var EosPublicKeyKind_value = map[string]int32{
	"EOS":    0,
	"EOS_K1": 1,
	"EOS_R1": 2,
}

func (x EosPublicKeyKind) Enum() *EosPublicKeyKind {
	p := new(EosPublicKeyKind)
	*p = x
	return p
}
func (x EosPublicKeyKind) String() string {
	return proto.EnumName(EosPublicKeyKind_name, int32(x))
}
func (x *EosPublicKeyKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EosPublicKeyKind_value, data, "EosPublicKeyKind")
	if err != nil {
		return err
	}
	*x = EosPublicKeyKind(value)
	return nil
}
func (EosPublicKeyKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{0}
}

// *
// Request: Ask device for Eos public key corresponding to address_n path
// @start
// @next EosPublicKey
// @next Failure
type EosGetPublicKey struct {
	AddressN             []uint32          `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ShowDisplay          *bool             `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	Kind                 *EosPublicKeyKind `protobuf:"varint,3,opt,name=kind,enum=EosPublicKeyKind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EosGetPublicKey) Reset()         { *m = EosGetPublicKey{} }
func (m *EosGetPublicKey) String() string { return proto.CompactTextString(m) }
func (*EosGetPublicKey) ProtoMessage()    {}
func (*EosGetPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{0}
}
func (m *EosGetPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosGetPublicKey.Unmarshal(m, b)
}
func (m *EosGetPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosGetPublicKey.Marshal(b, m, deterministic)
}
func (dst *EosGetPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosGetPublicKey.Merge(dst, src)
}
func (m *EosGetPublicKey) XXX_Size() int {
	return xxx_messageInfo_EosGetPublicKey.Size(m)
}
func (m *EosGetPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EosGetPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_EosGetPublicKey proto.InternalMessageInfo

func (m *EosGetPublicKey) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *EosGetPublicKey) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

func (m *EosGetPublicKey) GetKind() EosPublicKeyKind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return EosPublicKeyKind_EOS
}

// *
// Response: Contains an Eos public key derived from device private seed
// @end
type EosPublicKey struct {
	WifPublicKey         *string  `protobuf:"bytes,1,opt,name=wif_public_key,json=wifPublicKey" json:"wif_public_key,omitempty"`
	RawPublicKey         []byte   `protobuf:"bytes,2,opt,name=raw_public_key,json=rawPublicKey" json:"raw_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosPublicKey) Reset()         { *m = EosPublicKey{} }
func (m *EosPublicKey) String() string { return proto.CompactTextString(m) }
func (*EosPublicKey) ProtoMessage()    {}
func (*EosPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{1}
}
func (m *EosPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosPublicKey.Unmarshal(m, b)
}
func (m *EosPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosPublicKey.Marshal(b, m, deterministic)
}
func (dst *EosPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosPublicKey.Merge(dst, src)
}
func (m *EosPublicKey) XXX_Size() int {
	return xxx_messageInfo_EosPublicKey.Size(m)
}
func (m *EosPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EosPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_EosPublicKey proto.InternalMessageInfo

func (m *EosPublicKey) GetWifPublicKey() string {
	if m != nil && m.WifPublicKey != nil {
		return *m.WifPublicKey
	}
	return ""
}

func (m *EosPublicKey) GetRawPublicKey() []byte {
	if m != nil {
		return m.RawPublicKey
	}
	return nil
}

// *
// Request: Ask device to sign transaction
// @start
// @next EosTxRequest
// @next Failure
type EosSignTx struct {
	AddressN             []uint32     `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ChainId              []byte       `protobuf:"bytes,2,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Header               *EosTxHeader `protobuf:"bytes,3,opt,name=header" json:"header,omitempty"`
	NumActions           *uint32      `protobuf:"varint,4,opt,name=num_actions,json=numActions" json:"num_actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EosSignTx) Reset()         { *m = EosSignTx{} }
func (m *EosSignTx) String() string { return proto.CompactTextString(m) }
func (*EosSignTx) ProtoMessage()    {}
func (*EosSignTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{2}
}
func (m *EosSignTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosSignTx.Unmarshal(m, b)
}
func (m *EosSignTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosSignTx.Marshal(b, m, deterministic)
}
func (dst *EosSignTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosSignTx.Merge(dst, src)
}
func (m *EosSignTx) XXX_Size() int {
	return xxx_messageInfo_EosSignTx.Size(m)
}
func (m *EosSignTx) XXX_DiscardUnknown() {
	xxx_messageInfo_EosSignTx.DiscardUnknown(m)
}

var xxx_messageInfo_EosSignTx proto.InternalMessageInfo

func (m *EosSignTx) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *EosSignTx) GetChainId() []byte {
	if m != nil {
		return m.ChainId
	}
	return nil
}

func (m *EosSignTx) GetHeader() *EosTxHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EosSignTx) GetNumActions() uint32 {
	if m != nil && m.NumActions != nil {
		return *m.NumActions
	}
	return 0
}

// *
// Structure representing EOS transaction header
type EosTxHeader struct {
	Expiration           *uint32  `protobuf:"varint,1,req,name=expiration" json:"expiration,omitempty"`
	RefBlockNum          *uint32  `protobuf:"varint,2,req,name=ref_block_num,json=refBlockNum" json:"ref_block_num,omitempty"`
	RefBlockPrefix       *uint32  `protobuf:"varint,3,req,name=ref_block_prefix,json=refBlockPrefix" json:"ref_block_prefix,omitempty"`
	MaxNetUsageWords     *uint32  `protobuf:"varint,4,req,name=max_net_usage_words,json=maxNetUsageWords" json:"max_net_usage_words,omitempty"`
	MaxCpuUsageMs        *uint32  `protobuf:"varint,5,req,name=max_cpu_usage_ms,json=maxCpuUsageMs" json:"max_cpu_usage_ms,omitempty"`
	DelaySec             *uint32  `protobuf:"varint,6,req,name=delay_sec,json=delaySec" json:"delay_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosTxHeader) Reset()         { *m = EosTxHeader{} }
func (m *EosTxHeader) String() string { return proto.CompactTextString(m) }
func (*EosTxHeader) ProtoMessage()    {}
func (*EosTxHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{3}
}
func (m *EosTxHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosTxHeader.Unmarshal(m, b)
}
func (m *EosTxHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosTxHeader.Marshal(b, m, deterministic)
}
func (dst *EosTxHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosTxHeader.Merge(dst, src)
}
func (m *EosTxHeader) XXX_Size() int {
	return xxx_messageInfo_EosTxHeader.Size(m)
}
func (m *EosTxHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_EosTxHeader.DiscardUnknown(m)
}

var xxx_messageInfo_EosTxHeader proto.InternalMessageInfo

func (m *EosTxHeader) GetExpiration() uint32 {
	if m != nil && m.Expiration != nil {
		return *m.Expiration
	}
	return 0
}

func (m *EosTxHeader) GetRefBlockNum() uint32 {
	if m != nil && m.RefBlockNum != nil {
		return *m.RefBlockNum
	}
	return 0
}

func (m *EosTxHeader) GetRefBlockPrefix() uint32 {
	if m != nil && m.RefBlockPrefix != nil {
		return *m.RefBlockPrefix
	}
	return 0
}

func (m *EosTxHeader) GetMaxNetUsageWords() uint32 {
	if m != nil && m.MaxNetUsageWords != nil {
		return *m.MaxNetUsageWords
	}
	return 0
}

func (m *EosTxHeader) GetMaxCpuUsageMs() uint32 {
	if m != nil && m.MaxCpuUsageMs != nil {
		return *m.MaxCpuUsageMs
	}
	return 0
}

func (m *EosTxHeader) GetDelaySec() uint32 {
	if m != nil && m.DelaySec != nil {
		return *m.DelaySec
	}
	return 0
}

// *
// Response: Device asks to upload next action
// @next EosTxActionAck
type EosTxActionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosTxActionRequest) Reset()         { *m = EosTxActionRequest{} }
func (m *EosTxActionRequest) String() string { return proto.CompactTextString(m) }
func (*EosTxActionRequest) ProtoMessage()    {}
func (*EosTxActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{4}
}
func (m *EosTxActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosTxActionRequest.Unmarshal(m, b)
}
func (m *EosTxActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosTxActionRequest.Marshal(b, m, deterministic)
}
func (dst *EosTxActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosTxActionRequest.Merge(dst, src)
}
func (m *EosTxActionRequest) XXX_Size() int {
	return xxx_messageInfo_EosTxActionRequest.Size(m)
}
func (m *EosTxActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EosTxActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EosTxActionRequest proto.InternalMessageInfo

// *
// Request: Next action data that needs to be uploaded
// @next EosTxActionRequest
// @next EosSignedTx
// @next Failure
type EosTxActionAck struct {
	Common               *EosActionCommon       `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	Transfer             *EosActionTransfer     `protobuf:"bytes,2,opt,name=transfer" json:"transfer,omitempty"`
	Delegate             *EosActionDelegate     `protobuf:"bytes,3,opt,name=delegate" json:"delegate,omitempty"`
	Undelegate           *EosActionUndelegate   `protobuf:"bytes,4,opt,name=undelegate" json:"undelegate,omitempty"`
	Refund               *EosActionRefund       `protobuf:"bytes,5,opt,name=refund" json:"refund,omitempty"`
	BuyRam               *EosActionBuyRam       `protobuf:"bytes,6,opt,name=buy_ram,json=buyRam" json:"buy_ram,omitempty"`
	BuyRamBytes          *EosActionBuyRamBytes  `protobuf:"bytes,7,opt,name=buy_ram_bytes,json=buyRamBytes" json:"buy_ram_bytes,omitempty"`
	SellRam              *EosActionSellRam      `protobuf:"bytes,8,opt,name=sell_ram,json=sellRam" json:"sell_ram,omitempty"`
	VoteProducer         *EosActionVoteProducer `protobuf:"bytes,9,opt,name=vote_producer,json=voteProducer" json:"vote_producer,omitempty"`
	UpdateAuth           *EosActionUpdateAuth   `protobuf:"bytes,10,opt,name=update_auth,json=updateAuth" json:"update_auth,omitempty"`
	DeleteAuth           *EosActionDeleteAuth   `protobuf:"bytes,11,opt,name=delete_auth,json=deleteAuth" json:"delete_auth,omitempty"`
	LinkAuth             *EosActionLinkAuth     `protobuf:"bytes,12,opt,name=link_auth,json=linkAuth" json:"link_auth,omitempty"`
	UnlinkAuth           *EosActionUnlinkAuth   `protobuf:"bytes,13,opt,name=unlink_auth,json=unlinkAuth" json:"unlink_auth,omitempty"`
	NewAccount           *EosActionNewAccount   `protobuf:"bytes,14,opt,name=new_account,json=newAccount" json:"new_account,omitempty"`
	Unknown              *EosActionUnknown      `protobuf:"bytes,15,opt,name=unknown" json:"unknown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EosTxActionAck) Reset()         { *m = EosTxActionAck{} }
func (m *EosTxActionAck) String() string { return proto.CompactTextString(m) }
func (*EosTxActionAck) ProtoMessage()    {}
func (*EosTxActionAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{5}
}
func (m *EosTxActionAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosTxActionAck.Unmarshal(m, b)
}
func (m *EosTxActionAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosTxActionAck.Marshal(b, m, deterministic)
}
func (dst *EosTxActionAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosTxActionAck.Merge(dst, src)
}
func (m *EosTxActionAck) XXX_Size() int {
	return xxx_messageInfo_EosTxActionAck.Size(m)
}
func (m *EosTxActionAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EosTxActionAck.DiscardUnknown(m)
}

var xxx_messageInfo_EosTxActionAck proto.InternalMessageInfo

func (m *EosTxActionAck) GetCommon() *EosActionCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *EosTxActionAck) GetTransfer() *EosActionTransfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

func (m *EosTxActionAck) GetDelegate() *EosActionDelegate {
	if m != nil {
		return m.Delegate
	}
	return nil
}

func (m *EosTxActionAck) GetUndelegate() *EosActionUndelegate {
	if m != nil {
		return m.Undelegate
	}
	return nil
}

func (m *EosTxActionAck) GetRefund() *EosActionRefund {
	if m != nil {
		return m.Refund
	}
	return nil
}

func (m *EosTxActionAck) GetBuyRam() *EosActionBuyRam {
	if m != nil {
		return m.BuyRam
	}
	return nil
}

func (m *EosTxActionAck) GetBuyRamBytes() *EosActionBuyRamBytes {
	if m != nil {
		return m.BuyRamBytes
	}
	return nil
}

func (m *EosTxActionAck) GetSellRam() *EosActionSellRam {
	if m != nil {
		return m.SellRam
	}
	return nil
}

func (m *EosTxActionAck) GetVoteProducer() *EosActionVoteProducer {
	if m != nil {
		return m.VoteProducer
	}
	return nil
}

func (m *EosTxActionAck) GetUpdateAuth() *EosActionUpdateAuth {
	if m != nil {
		return m.UpdateAuth
	}
	return nil
}

func (m *EosTxActionAck) GetDeleteAuth() *EosActionDeleteAuth {
	if m != nil {
		return m.DeleteAuth
	}
	return nil
}

func (m *EosTxActionAck) GetLinkAuth() *EosActionLinkAuth {
	if m != nil {
		return m.LinkAuth
	}
	return nil
}

func (m *EosTxActionAck) GetUnlinkAuth() *EosActionUnlinkAuth {
	if m != nil {
		return m.UnlinkAuth
	}
	return nil
}

func (m *EosTxActionAck) GetNewAccount() *EosActionNewAccount {
	if m != nil {
		return m.NewAccount
	}
	return nil
}

func (m *EosTxActionAck) GetUnknown() *EosActionUnknown {
	if m != nil {
		return m.Unknown
	}
	return nil
}

// *
// Structure representing asset type
type EosAsset struct {
	Amount               *int64   `protobuf:"zigzag64,1,opt,name=amount" json:"amount,omitempty"`
	Symbol               *uint64  `protobuf:"varint,2,opt,name=symbol" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosAsset) Reset()         { *m = EosAsset{} }
func (m *EosAsset) String() string { return proto.CompactTextString(m) }
func (*EosAsset) ProtoMessage()    {}
func (*EosAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{6}
}
func (m *EosAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAsset.Unmarshal(m, b)
}
func (m *EosAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAsset.Marshal(b, m, deterministic)
}
func (dst *EosAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAsset.Merge(dst, src)
}
func (m *EosAsset) XXX_Size() int {
	return xxx_messageInfo_EosAsset.Size(m)
}
func (m *EosAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAsset.DiscardUnknown(m)
}

var xxx_messageInfo_EosAsset proto.InternalMessageInfo

func (m *EosAsset) GetAmount() int64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *EosAsset) GetSymbol() uint64 {
	if m != nil && m.Symbol != nil {
		return *m.Symbol
	}
	return 0
}

// *
// Structure representing action permission level
type EosPermissionLevel struct {
	Actor                *uint64  `protobuf:"varint,1,opt,name=actor" json:"actor,omitempty"`
	Permission           *uint64  `protobuf:"varint,2,opt,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosPermissionLevel) Reset()         { *m = EosPermissionLevel{} }
func (m *EosPermissionLevel) String() string { return proto.CompactTextString(m) }
func (*EosPermissionLevel) ProtoMessage()    {}
func (*EosPermissionLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{7}
}
func (m *EosPermissionLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosPermissionLevel.Unmarshal(m, b)
}
func (m *EosPermissionLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosPermissionLevel.Marshal(b, m, deterministic)
}
func (dst *EosPermissionLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosPermissionLevel.Merge(dst, src)
}
func (m *EosPermissionLevel) XXX_Size() int {
	return xxx_messageInfo_EosPermissionLevel.Size(m)
}
func (m *EosPermissionLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_EosPermissionLevel.DiscardUnknown(m)
}

var xxx_messageInfo_EosPermissionLevel proto.InternalMessageInfo

func (m *EosPermissionLevel) GetActor() uint64 {
	if m != nil && m.Actor != nil {
		return *m.Actor
	}
	return 0
}

func (m *EosPermissionLevel) GetPermission() uint64 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

// *
// Structure representing auth key
type EosAuthorizationKey struct {
	Type                 *uint32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Weight               *uint32  `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	AddressN             []uint32 `protobuf:"varint,4,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosAuthorizationKey) Reset()         { *m = EosAuthorizationKey{} }
func (m *EosAuthorizationKey) String() string { return proto.CompactTextString(m) }
func (*EosAuthorizationKey) ProtoMessage()    {}
func (*EosAuthorizationKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{8}
}
func (m *EosAuthorizationKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAuthorizationKey.Unmarshal(m, b)
}
func (m *EosAuthorizationKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAuthorizationKey.Marshal(b, m, deterministic)
}
func (dst *EosAuthorizationKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAuthorizationKey.Merge(dst, src)
}
func (m *EosAuthorizationKey) XXX_Size() int {
	return xxx_messageInfo_EosAuthorizationKey.Size(m)
}
func (m *EosAuthorizationKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAuthorizationKey.DiscardUnknown(m)
}

var xxx_messageInfo_EosAuthorizationKey proto.InternalMessageInfo

func (m *EosAuthorizationKey) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *EosAuthorizationKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *EosAuthorizationKey) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

func (m *EosAuthorizationKey) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

// *
// Structure representing auth account
type EosAuthorizationAccount struct {
	Account              *EosPermissionLevel `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Weight               *uint32             `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EosAuthorizationAccount) Reset()         { *m = EosAuthorizationAccount{} }
func (m *EosAuthorizationAccount) String() string { return proto.CompactTextString(m) }
func (*EosAuthorizationAccount) ProtoMessage()    {}
func (*EosAuthorizationAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{9}
}
func (m *EosAuthorizationAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAuthorizationAccount.Unmarshal(m, b)
}
func (m *EosAuthorizationAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAuthorizationAccount.Marshal(b, m, deterministic)
}
func (dst *EosAuthorizationAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAuthorizationAccount.Merge(dst, src)
}
func (m *EosAuthorizationAccount) XXX_Size() int {
	return xxx_messageInfo_EosAuthorizationAccount.Size(m)
}
func (m *EosAuthorizationAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAuthorizationAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EosAuthorizationAccount proto.InternalMessageInfo

func (m *EosAuthorizationAccount) GetAccount() *EosPermissionLevel {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *EosAuthorizationAccount) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

// *
// Structure representing auth delays
type EosAuthorizationWait struct {
	WaitSec              *uint32  `protobuf:"varint,1,opt,name=wait_sec,json=waitSec" json:"wait_sec,omitempty"`
	Weight               *uint32  `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosAuthorizationWait) Reset()         { *m = EosAuthorizationWait{} }
func (m *EosAuthorizationWait) String() string { return proto.CompactTextString(m) }
func (*EosAuthorizationWait) ProtoMessage()    {}
func (*EosAuthorizationWait) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{10}
}
func (m *EosAuthorizationWait) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAuthorizationWait.Unmarshal(m, b)
}
func (m *EosAuthorizationWait) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAuthorizationWait.Marshal(b, m, deterministic)
}
func (dst *EosAuthorizationWait) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAuthorizationWait.Merge(dst, src)
}
func (m *EosAuthorizationWait) XXX_Size() int {
	return xxx_messageInfo_EosAuthorizationWait.Size(m)
}
func (m *EosAuthorizationWait) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAuthorizationWait.DiscardUnknown(m)
}

var xxx_messageInfo_EosAuthorizationWait proto.InternalMessageInfo

func (m *EosAuthorizationWait) GetWaitSec() uint32 {
	if m != nil && m.WaitSec != nil {
		return *m.WaitSec
	}
	return 0
}

func (m *EosAuthorizationWait) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

// *
// Structure representing authorization settings
type EosAuthorization struct {
	Threshold            *uint32                    `protobuf:"varint,1,opt,name=threshold" json:"threshold,omitempty"`
	Keys                 []*EosAuthorizationKey     `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	Accounts             []*EosAuthorizationAccount `protobuf:"bytes,3,rep,name=accounts" json:"accounts,omitempty"`
	Waits                []*EosAuthorizationWait    `protobuf:"bytes,4,rep,name=waits" json:"waits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EosAuthorization) Reset()         { *m = EosAuthorization{} }
func (m *EosAuthorization) String() string { return proto.CompactTextString(m) }
func (*EosAuthorization) ProtoMessage()    {}
func (*EosAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{11}
}
func (m *EosAuthorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosAuthorization.Unmarshal(m, b)
}
func (m *EosAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosAuthorization.Marshal(b, m, deterministic)
}
func (dst *EosAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosAuthorization.Merge(dst, src)
}
func (m *EosAuthorization) XXX_Size() int {
	return xxx_messageInfo_EosAuthorization.Size(m)
}
func (m *EosAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_EosAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_EosAuthorization proto.InternalMessageInfo

func (m *EosAuthorization) GetThreshold() uint32 {
	if m != nil && m.Threshold != nil {
		return *m.Threshold
	}
	return 0
}

func (m *EosAuthorization) GetKeys() []*EosAuthorizationKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *EosAuthorization) GetAccounts() []*EosAuthorizationAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *EosAuthorization) GetWaits() []*EosAuthorizationWait {
	if m != nil {
		return m.Waits
	}
	return nil
}

// *
// Structure representing the common part of every action
type EosActionCommon struct {
	Account              *uint64               `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Name                 *uint64               `protobuf:"varint,2,opt,name=name" json:"name,omitempty"`
	Authorization        []*EosPermissionLevel `protobuf:"bytes,3,rep,name=authorization" json:"authorization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EosActionCommon) Reset()         { *m = EosActionCommon{} }
func (m *EosActionCommon) String() string { return proto.CompactTextString(m) }
func (*EosActionCommon) ProtoMessage()    {}
func (*EosActionCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{12}
}
func (m *EosActionCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionCommon.Unmarshal(m, b)
}
func (m *EosActionCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionCommon.Marshal(b, m, deterministic)
}
func (dst *EosActionCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionCommon.Merge(dst, src)
}
func (m *EosActionCommon) XXX_Size() int {
	return xxx_messageInfo_EosActionCommon.Size(m)
}
func (m *EosActionCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionCommon.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionCommon proto.InternalMessageInfo

func (m *EosActionCommon) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionCommon) GetName() uint64 {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return 0
}

func (m *EosActionCommon) GetAuthorization() []*EosPermissionLevel {
	if m != nil {
		return m.Authorization
	}
	return nil
}

// *
// Structure representing transfer data structure
type EosActionTransfer struct {
	Sender               *uint64   `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Receiver             *uint64   `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	Quantity             *EosAsset `protobuf:"bytes,3,opt,name=quantity" json:"quantity,omitempty"`
	Memo                 *string   `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EosActionTransfer) Reset()         { *m = EosActionTransfer{} }
func (m *EosActionTransfer) String() string { return proto.CompactTextString(m) }
func (*EosActionTransfer) ProtoMessage()    {}
func (*EosActionTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{13}
}
func (m *EosActionTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionTransfer.Unmarshal(m, b)
}
func (m *EosActionTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionTransfer.Marshal(b, m, deterministic)
}
func (dst *EosActionTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionTransfer.Merge(dst, src)
}
func (m *EosActionTransfer) XXX_Size() int {
	return xxx_messageInfo_EosActionTransfer.Size(m)
}
func (m *EosActionTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionTransfer proto.InternalMessageInfo

func (m *EosActionTransfer) GetSender() uint64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *EosActionTransfer) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *EosActionTransfer) GetQuantity() *EosAsset {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *EosActionTransfer) GetMemo() string {
	if m != nil && m.Memo != nil {
		return *m.Memo
	}
	return ""
}

// *
// Structure representing delegation data structure
type EosActionDelegate struct {
	Sender               *uint64   `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Receiver             *uint64   `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	NetQuantity          *EosAsset `protobuf:"bytes,3,opt,name=net_quantity,json=netQuantity" json:"net_quantity,omitempty"`
	CpuQuantity          *EosAsset `protobuf:"bytes,4,opt,name=cpu_quantity,json=cpuQuantity" json:"cpu_quantity,omitempty"`
	Transfer             *bool     `protobuf:"varint,5,opt,name=transfer" json:"transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EosActionDelegate) Reset()         { *m = EosActionDelegate{} }
func (m *EosActionDelegate) String() string { return proto.CompactTextString(m) }
func (*EosActionDelegate) ProtoMessage()    {}
func (*EosActionDelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{14}
}
func (m *EosActionDelegate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionDelegate.Unmarshal(m, b)
}
func (m *EosActionDelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionDelegate.Marshal(b, m, deterministic)
}
func (dst *EosActionDelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionDelegate.Merge(dst, src)
}
func (m *EosActionDelegate) XXX_Size() int {
	return xxx_messageInfo_EosActionDelegate.Size(m)
}
func (m *EosActionDelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionDelegate.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionDelegate proto.InternalMessageInfo

func (m *EosActionDelegate) GetSender() uint64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *EosActionDelegate) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *EosActionDelegate) GetNetQuantity() *EosAsset {
	if m != nil {
		return m.NetQuantity
	}
	return nil
}

func (m *EosActionDelegate) GetCpuQuantity() *EosAsset {
	if m != nil {
		return m.CpuQuantity
	}
	return nil
}

func (m *EosActionDelegate) GetTransfer() bool {
	if m != nil && m.Transfer != nil {
		return *m.Transfer
	}
	return false
}

// *
// Structure representing the removal of delegated resources from `payer`
type EosActionUndelegate struct {
	Sender               *uint64   `protobuf:"varint,1,opt,name=sender" json:"sender,omitempty"`
	Receiver             *uint64   `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	NetQuantity          *EosAsset `protobuf:"bytes,3,opt,name=net_quantity,json=netQuantity" json:"net_quantity,omitempty"`
	CpuQuantity          *EosAsset `protobuf:"bytes,4,opt,name=cpu_quantity,json=cpuQuantity" json:"cpu_quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EosActionUndelegate) Reset()         { *m = EosActionUndelegate{} }
func (m *EosActionUndelegate) String() string { return proto.CompactTextString(m) }
func (*EosActionUndelegate) ProtoMessage()    {}
func (*EosActionUndelegate) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{15}
}
func (m *EosActionUndelegate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionUndelegate.Unmarshal(m, b)
}
func (m *EosActionUndelegate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionUndelegate.Marshal(b, m, deterministic)
}
func (dst *EosActionUndelegate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionUndelegate.Merge(dst, src)
}
func (m *EosActionUndelegate) XXX_Size() int {
	return xxx_messageInfo_EosActionUndelegate.Size(m)
}
func (m *EosActionUndelegate) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionUndelegate.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionUndelegate proto.InternalMessageInfo

func (m *EosActionUndelegate) GetSender() uint64 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *EosActionUndelegate) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *EosActionUndelegate) GetNetQuantity() *EosAsset {
	if m != nil {
		return m.NetQuantity
	}
	return nil
}

func (m *EosActionUndelegate) GetCpuQuantity() *EosAsset {
	if m != nil {
		return m.CpuQuantity
	}
	return nil
}

// *
// Structure representing fallbalck if undelegate wasnt executed automaticaly.
type EosActionRefund struct {
	Owner                *uint64  `protobuf:"varint,1,opt,name=owner" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionRefund) Reset()         { *m = EosActionRefund{} }
func (m *EosActionRefund) String() string { return proto.CompactTextString(m) }
func (*EosActionRefund) ProtoMessage()    {}
func (*EosActionRefund) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{16}
}
func (m *EosActionRefund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionRefund.Unmarshal(m, b)
}
func (m *EosActionRefund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionRefund.Marshal(b, m, deterministic)
}
func (dst *EosActionRefund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionRefund.Merge(dst, src)
}
func (m *EosActionRefund) XXX_Size() int {
	return xxx_messageInfo_EosActionRefund.Size(m)
}
func (m *EosActionRefund) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionRefund.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionRefund proto.InternalMessageInfo

func (m *EosActionRefund) GetOwner() uint64 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

// *
// Structure representing buying RAM operation for EOS tokens
type EosActionBuyRam struct {
	Payer                *uint64   `protobuf:"varint,1,opt,name=payer" json:"payer,omitempty"`
	Receiver             *uint64   `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	Quantity             *EosAsset `protobuf:"bytes,3,opt,name=quantity" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EosActionBuyRam) Reset()         { *m = EosActionBuyRam{} }
func (m *EosActionBuyRam) String() string { return proto.CompactTextString(m) }
func (*EosActionBuyRam) ProtoMessage()    {}
func (*EosActionBuyRam) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{17}
}
func (m *EosActionBuyRam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionBuyRam.Unmarshal(m, b)
}
func (m *EosActionBuyRam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionBuyRam.Marshal(b, m, deterministic)
}
func (dst *EosActionBuyRam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionBuyRam.Merge(dst, src)
}
func (m *EosActionBuyRam) XXX_Size() int {
	return xxx_messageInfo_EosActionBuyRam.Size(m)
}
func (m *EosActionBuyRam) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionBuyRam.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionBuyRam proto.InternalMessageInfo

func (m *EosActionBuyRam) GetPayer() uint64 {
	if m != nil && m.Payer != nil {
		return *m.Payer
	}
	return 0
}

func (m *EosActionBuyRam) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *EosActionBuyRam) GetQuantity() *EosAsset {
	if m != nil {
		return m.Quantity
	}
	return nil
}

// *
// Structure representing buying bytes according to RAM market price.
type EosActionBuyRamBytes struct {
	Payer                *uint64  `protobuf:"varint,1,opt,name=payer" json:"payer,omitempty"`
	Receiver             *uint64  `protobuf:"varint,2,opt,name=receiver" json:"receiver,omitempty"`
	Bytes                *uint32  `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionBuyRamBytes) Reset()         { *m = EosActionBuyRamBytes{} }
func (m *EosActionBuyRamBytes) String() string { return proto.CompactTextString(m) }
func (*EosActionBuyRamBytes) ProtoMessage()    {}
func (*EosActionBuyRamBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{18}
}
func (m *EosActionBuyRamBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionBuyRamBytes.Unmarshal(m, b)
}
func (m *EosActionBuyRamBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionBuyRamBytes.Marshal(b, m, deterministic)
}
func (dst *EosActionBuyRamBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionBuyRamBytes.Merge(dst, src)
}
func (m *EosActionBuyRamBytes) XXX_Size() int {
	return xxx_messageInfo_EosActionBuyRamBytes.Size(m)
}
func (m *EosActionBuyRamBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionBuyRamBytes.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionBuyRamBytes proto.InternalMessageInfo

func (m *EosActionBuyRamBytes) GetPayer() uint64 {
	if m != nil && m.Payer != nil {
		return *m.Payer
	}
	return 0
}

func (m *EosActionBuyRamBytes) GetReceiver() uint64 {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return 0
}

func (m *EosActionBuyRamBytes) GetBytes() uint32 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

// *
// Structure representing sell RAM
type EosActionSellRam struct {
	Account              *uint64  `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Bytes                *int64   `protobuf:"zigzag64,2,opt,name=bytes" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionSellRam) Reset()         { *m = EosActionSellRam{} }
func (m *EosActionSellRam) String() string { return proto.CompactTextString(m) }
func (*EosActionSellRam) ProtoMessage()    {}
func (*EosActionSellRam) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{19}
}
func (m *EosActionSellRam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionSellRam.Unmarshal(m, b)
}
func (m *EosActionSellRam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionSellRam.Marshal(b, m, deterministic)
}
func (dst *EosActionSellRam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionSellRam.Merge(dst, src)
}
func (m *EosActionSellRam) XXX_Size() int {
	return xxx_messageInfo_EosActionSellRam.Size(m)
}
func (m *EosActionSellRam) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionSellRam.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionSellRam proto.InternalMessageInfo

func (m *EosActionSellRam) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionSellRam) GetBytes() int64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

// *
// Structure representing voting. Currently, there could be up to 30 producers.
type EosActionVoteProducer struct {
	Voter                *uint64  `protobuf:"varint,1,opt,name=voter" json:"voter,omitempty"`
	Proxy                *uint64  `protobuf:"varint,2,opt,name=proxy" json:"proxy,omitempty"`
	Producers            []uint64 `protobuf:"varint,3,rep,name=producers" json:"producers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionVoteProducer) Reset()         { *m = EosActionVoteProducer{} }
func (m *EosActionVoteProducer) String() string { return proto.CompactTextString(m) }
func (*EosActionVoteProducer) ProtoMessage()    {}
func (*EosActionVoteProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{20}
}
func (m *EosActionVoteProducer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionVoteProducer.Unmarshal(m, b)
}
func (m *EosActionVoteProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionVoteProducer.Marshal(b, m, deterministic)
}
func (dst *EosActionVoteProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionVoteProducer.Merge(dst, src)
}
func (m *EosActionVoteProducer) XXX_Size() int {
	return xxx_messageInfo_EosActionVoteProducer.Size(m)
}
func (m *EosActionVoteProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionVoteProducer.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionVoteProducer proto.InternalMessageInfo

func (m *EosActionVoteProducer) GetVoter() uint64 {
	if m != nil && m.Voter != nil {
		return *m.Voter
	}
	return 0
}

func (m *EosActionVoteProducer) GetProxy() uint64 {
	if m != nil && m.Proxy != nil {
		return *m.Proxy
	}
	return 0
}

func (m *EosActionVoteProducer) GetProducers() []uint64 {
	if m != nil {
		return m.Producers
	}
	return nil
}

// *
// Structure representing update authorization.
type EosActionUpdateAuth struct {
	Account              *uint64           `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Permission           *uint64           `protobuf:"varint,2,opt,name=permission" json:"permission,omitempty"`
	Parent               *uint64           `protobuf:"varint,3,opt,name=parent" json:"parent,omitempty"`
	Auth                 *EosAuthorization `protobuf:"bytes,4,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EosActionUpdateAuth) Reset()         { *m = EosActionUpdateAuth{} }
func (m *EosActionUpdateAuth) String() string { return proto.CompactTextString(m) }
func (*EosActionUpdateAuth) ProtoMessage()    {}
func (*EosActionUpdateAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{21}
}
func (m *EosActionUpdateAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionUpdateAuth.Unmarshal(m, b)
}
func (m *EosActionUpdateAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionUpdateAuth.Marshal(b, m, deterministic)
}
func (dst *EosActionUpdateAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionUpdateAuth.Merge(dst, src)
}
func (m *EosActionUpdateAuth) XXX_Size() int {
	return xxx_messageInfo_EosActionUpdateAuth.Size(m)
}
func (m *EosActionUpdateAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionUpdateAuth.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionUpdateAuth proto.InternalMessageInfo

func (m *EosActionUpdateAuth) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionUpdateAuth) GetPermission() uint64 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *EosActionUpdateAuth) GetParent() uint64 {
	if m != nil && m.Parent != nil {
		return *m.Parent
	}
	return 0
}

func (m *EosActionUpdateAuth) GetAuth() *EosAuthorization {
	if m != nil {
		return m.Auth
	}
	return nil
}

// *
// Structure representing delete authorization.
type EosActionDeleteAuth struct {
	Account              *uint64  `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Permission           *uint64  `protobuf:"varint,2,opt,name=permission" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionDeleteAuth) Reset()         { *m = EosActionDeleteAuth{} }
func (m *EosActionDeleteAuth) String() string { return proto.CompactTextString(m) }
func (*EosActionDeleteAuth) ProtoMessage()    {}
func (*EosActionDeleteAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{22}
}
func (m *EosActionDeleteAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionDeleteAuth.Unmarshal(m, b)
}
func (m *EosActionDeleteAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionDeleteAuth.Marshal(b, m, deterministic)
}
func (dst *EosActionDeleteAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionDeleteAuth.Merge(dst, src)
}
func (m *EosActionDeleteAuth) XXX_Size() int {
	return xxx_messageInfo_EosActionDeleteAuth.Size(m)
}
func (m *EosActionDeleteAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionDeleteAuth.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionDeleteAuth proto.InternalMessageInfo

func (m *EosActionDeleteAuth) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionDeleteAuth) GetPermission() uint64 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

// *
// Structure representing link authorization to action.
type EosActionLinkAuth struct {
	Account              *uint64  `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Code                 *uint64  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Type                 *uint64  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Requirement          *uint64  `protobuf:"varint,4,opt,name=requirement" json:"requirement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionLinkAuth) Reset()         { *m = EosActionLinkAuth{} }
func (m *EosActionLinkAuth) String() string { return proto.CompactTextString(m) }
func (*EosActionLinkAuth) ProtoMessage()    {}
func (*EosActionLinkAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{23}
}
func (m *EosActionLinkAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionLinkAuth.Unmarshal(m, b)
}
func (m *EosActionLinkAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionLinkAuth.Marshal(b, m, deterministic)
}
func (dst *EosActionLinkAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionLinkAuth.Merge(dst, src)
}
func (m *EosActionLinkAuth) XXX_Size() int {
	return xxx_messageInfo_EosActionLinkAuth.Size(m)
}
func (m *EosActionLinkAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionLinkAuth.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionLinkAuth proto.InternalMessageInfo

func (m *EosActionLinkAuth) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionLinkAuth) GetCode() uint64 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *EosActionLinkAuth) GetType() uint64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *EosActionLinkAuth) GetRequirement() uint64 {
	if m != nil && m.Requirement != nil {
		return *m.Requirement
	}
	return 0
}

// *
// Structure representing unlink authorization from action.
type EosActionUnlinkAuth struct {
	Account              *uint64  `protobuf:"varint,1,opt,name=account" json:"account,omitempty"`
	Code                 *uint64  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Type                 *uint64  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionUnlinkAuth) Reset()         { *m = EosActionUnlinkAuth{} }
func (m *EosActionUnlinkAuth) String() string { return proto.CompactTextString(m) }
func (*EosActionUnlinkAuth) ProtoMessage()    {}
func (*EosActionUnlinkAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{24}
}
func (m *EosActionUnlinkAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionUnlinkAuth.Unmarshal(m, b)
}
func (m *EosActionUnlinkAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionUnlinkAuth.Marshal(b, m, deterministic)
}
func (dst *EosActionUnlinkAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionUnlinkAuth.Merge(dst, src)
}
func (m *EosActionUnlinkAuth) XXX_Size() int {
	return xxx_messageInfo_EosActionUnlinkAuth.Size(m)
}
func (m *EosActionUnlinkAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionUnlinkAuth.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionUnlinkAuth proto.InternalMessageInfo

func (m *EosActionUnlinkAuth) GetAccount() uint64 {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return 0
}

func (m *EosActionUnlinkAuth) GetCode() uint64 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *EosActionUnlinkAuth) GetType() uint64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// *
// Structure representing creation of a new account.
type EosActionNewAccount struct {
	Creator              *uint64           `protobuf:"varint,1,opt,name=creator" json:"creator,omitempty"`
	Name                 *uint64           `protobuf:"varint,2,opt,name=name" json:"name,omitempty"`
	Owner                *EosAuthorization `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Active               *EosAuthorization `protobuf:"bytes,4,opt,name=active" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EosActionNewAccount) Reset()         { *m = EosActionNewAccount{} }
func (m *EosActionNewAccount) String() string { return proto.CompactTextString(m) }
func (*EosActionNewAccount) ProtoMessage()    {}
func (*EosActionNewAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{25}
}
func (m *EosActionNewAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionNewAccount.Unmarshal(m, b)
}
func (m *EosActionNewAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionNewAccount.Marshal(b, m, deterministic)
}
func (dst *EosActionNewAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionNewAccount.Merge(dst, src)
}
func (m *EosActionNewAccount) XXX_Size() int {
	return xxx_messageInfo_EosActionNewAccount.Size(m)
}
func (m *EosActionNewAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionNewAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionNewAccount proto.InternalMessageInfo

func (m *EosActionNewAccount) GetCreator() uint64 {
	if m != nil && m.Creator != nil {
		return *m.Creator
	}
	return 0
}

func (m *EosActionNewAccount) GetName() uint64 {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return 0
}

func (m *EosActionNewAccount) GetOwner() *EosAuthorization {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *EosActionNewAccount) GetActive() *EosAuthorization {
	if m != nil {
		return m.Active
	}
	return nil
}

// *
// Structure representing actions not implemented above.
type EosActionUnknown struct {
	DataSize             *uint32  `protobuf:"varint,1,opt,name=data_size,json=dataSize" json:"data_size,omitempty"`
	DataChunk            []byte   `protobuf:"bytes,2,opt,name=data_chunk,json=dataChunk" json:"data_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosActionUnknown) Reset()         { *m = EosActionUnknown{} }
func (m *EosActionUnknown) String() string { return proto.CompactTextString(m) }
func (*EosActionUnknown) ProtoMessage()    {}
func (*EosActionUnknown) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{26}
}
func (m *EosActionUnknown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosActionUnknown.Unmarshal(m, b)
}
func (m *EosActionUnknown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosActionUnknown.Marshal(b, m, deterministic)
}
func (dst *EosActionUnknown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosActionUnknown.Merge(dst, src)
}
func (m *EosActionUnknown) XXX_Size() int {
	return xxx_messageInfo_EosActionUnknown.Size(m)
}
func (m *EosActionUnknown) XXX_DiscardUnknown() {
	xxx_messageInfo_EosActionUnknown.DiscardUnknown(m)
}

var xxx_messageInfo_EosActionUnknown proto.InternalMessageInfo

func (m *EosActionUnknown) GetDataSize() uint32 {
	if m != nil && m.DataSize != nil {
		return *m.DataSize
	}
	return 0
}

func (m *EosActionUnknown) GetDataChunk() []byte {
	if m != nil {
		return m.DataChunk
	}
	return nil
}

// *
// Response: Device returns the signature.
// The signature_* fields contain the computed transaction signature. All three fields will be present.
// @end
type EosSignedTx struct {
	SignatureV           *uint32  `protobuf:"varint,1,opt,name=signature_v,json=signatureV" json:"signature_v,omitempty"`
	SignatureR           []byte   `protobuf:"bytes,2,opt,name=signature_r,json=signatureR" json:"signature_r,omitempty"`
	SignatureS           []byte   `protobuf:"bytes,3,opt,name=signature_s,json=signatureS" json:"signature_s,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EosSignedTx) Reset()         { *m = EosSignedTx{} }
func (m *EosSignedTx) String() string { return proto.CompactTextString(m) }
func (*EosSignedTx) ProtoMessage()    {}
func (*EosSignedTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_eos_eb6c58745a44fac6, []int{27}
}
func (m *EosSignedTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EosSignedTx.Unmarshal(m, b)
}
func (m *EosSignedTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EosSignedTx.Marshal(b, m, deterministic)
}
func (dst *EosSignedTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EosSignedTx.Merge(dst, src)
}
func (m *EosSignedTx) XXX_Size() int {
	return xxx_messageInfo_EosSignedTx.Size(m)
}
func (m *EosSignedTx) XXX_DiscardUnknown() {
	xxx_messageInfo_EosSignedTx.DiscardUnknown(m)
}

var xxx_messageInfo_EosSignedTx proto.InternalMessageInfo

func (m *EosSignedTx) GetSignatureV() uint32 {
	if m != nil && m.SignatureV != nil {
		return *m.SignatureV
	}
	return 0
}

func (m *EosSignedTx) GetSignatureR() []byte {
	if m != nil {
		return m.SignatureR
	}
	return nil
}

func (m *EosSignedTx) GetSignatureS() []byte {
	if m != nil {
		return m.SignatureS
	}
	return nil
}

func (m *EosSignedTx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*EosGetPublicKey)(nil), "EosGetPublicKey")
	proto.RegisterType((*EosPublicKey)(nil), "EosPublicKey")
	proto.RegisterType((*EosSignTx)(nil), "EosSignTx")
	proto.RegisterType((*EosTxHeader)(nil), "EosTxHeader")
	proto.RegisterType((*EosTxActionRequest)(nil), "EosTxActionRequest")
	proto.RegisterType((*EosTxActionAck)(nil), "EosTxActionAck")
	proto.RegisterType((*EosAsset)(nil), "EosAsset")
	proto.RegisterType((*EosPermissionLevel)(nil), "EosPermissionLevel")
	proto.RegisterType((*EosAuthorizationKey)(nil), "EosAuthorizationKey")
	proto.RegisterType((*EosAuthorizationAccount)(nil), "EosAuthorizationAccount")
	proto.RegisterType((*EosAuthorizationWait)(nil), "EosAuthorizationWait")
	proto.RegisterType((*EosAuthorization)(nil), "EosAuthorization")
	proto.RegisterType((*EosActionCommon)(nil), "EosActionCommon")
	proto.RegisterType((*EosActionTransfer)(nil), "EosActionTransfer")
	proto.RegisterType((*EosActionDelegate)(nil), "EosActionDelegate")
	proto.RegisterType((*EosActionUndelegate)(nil), "EosActionUndelegate")
	proto.RegisterType((*EosActionRefund)(nil), "EosActionRefund")
	proto.RegisterType((*EosActionBuyRam)(nil), "EosActionBuyRam")
	proto.RegisterType((*EosActionBuyRamBytes)(nil), "EosActionBuyRamBytes")
	proto.RegisterType((*EosActionSellRam)(nil), "EosActionSellRam")
	proto.RegisterType((*EosActionVoteProducer)(nil), "EosActionVoteProducer")
	proto.RegisterType((*EosActionUpdateAuth)(nil), "EosActionUpdateAuth")
	proto.RegisterType((*EosActionDeleteAuth)(nil), "EosActionDeleteAuth")
	proto.RegisterType((*EosActionLinkAuth)(nil), "EosActionLinkAuth")
	proto.RegisterType((*EosActionUnlinkAuth)(nil), "EosActionUnlinkAuth")
	proto.RegisterType((*EosActionNewAccount)(nil), "EosActionNewAccount")
	proto.RegisterType((*EosActionUnknown)(nil), "EosActionUnknown")
	proto.RegisterType((*EosSignedTx)(nil), "EosSignedTx")
	proto.RegisterEnum("EosPublicKeyKind", EosPublicKeyKind_name, EosPublicKeyKind_value)
}

func init() { proto.RegisterFile("messages-eos.proto", fileDescriptor_messages_eos_eb6c58745a44fac6) }

var fileDescriptor_messages_eos_eb6c58745a44fac6 = []byte{
	// 1514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4b, 0x73, 0x1b, 0xc7,
	0x11, 0x0e, 0x88, 0x25, 0x1e, 0x0d, 0x80, 0x02, 0x47, 0x94, 0xb2, 0x51, 0x5e, 0xc8, 0x46, 0x2a,
	0x41, 0x91, 0x84, 0x94, 0x14, 0xa5, 0x2a, 0x8f, 0x13, 0x29, 0xb1, 0x12, 0x85, 0x11, 0xc5, 0x0c,
	0x28, 0xa9, 0x2a, 0x07, 0xaf, 0x07, 0xbb, 0x0d, 0x62, 0x8d, 0x7d, 0x69, 0x67, 0x97, 0x00, 0x78,
	0x74, 0xd9, 0x17, 0x1f, 0x7c, 0xf5, 0x2f, 0xf0, 0xcf, 0x70, 0xf9, 0x2f, 0xf9, 0x27, 0xb8, 0xe6,
	0xb1, 0x0f, 0x80, 0xa2, 0x5c, 0xa5, 0xd2, 0xc1, 0xa7, 0x9d, 0xee, 0xfe, 0xba, 0xa7, 0xa7, 0x67,
	0xe6, 0xeb, 0x1d, 0x20, 0x01, 0x72, 0xce, 0xce, 0x90, 0x3f, 0xc4, 0x88, 0x8f, 0xe2, 0x24, 0x4a,
	0x23, 0x6b, 0x09, 0xd7, 0x0e, 0x23, 0xfe, 0x2f, 0x4c, 0x4f, 0xb2, 0x89, 0xef, 0x39, 0x47, 0xb8,
	0x22, 0xbf, 0x86, 0x36, 0x73, 0xdd, 0x04, 0x39, 0xb7, 0x43, 0xb3, 0x36, 0xa8, 0x0f, 0x7b, 0xb4,
	0xa5, 0x15, 0xc7, 0xe4, 0x0f, 0xd0, 0xe5, 0xb3, 0x68, 0x61, 0xbb, 0x1e, 0x8f, 0x7d, 0xb6, 0x32,
	0xb7, 0x06, 0xb5, 0x61, 0x8b, 0x76, 0x84, 0xee, 0x99, 0x52, 0x91, 0x3b, 0x60, 0xcc, 0xbd, 0xd0,
	0x35, 0xeb, 0x83, 0xda, 0x70, 0xe7, 0xf1, 0xee, 0xe8, 0x30, 0xe2, 0x45, 0xf0, 0x23, 0x2f, 0x74,
	0xa9, 0x34, 0x5b, 0xff, 0x87, 0x6e, 0xd5, 0x42, 0x6e, 0xc3, 0xce, 0xc2, 0x9b, 0xda, 0xb1, 0x54,
	0xd8, 0x73, 0x5c, 0x99, 0xb5, 0x41, 0x6d, 0xd8, 0xa6, 0xdd, 0x85, 0x37, 0x5d, 0x43, 0x25, 0x6c,
	0x51, 0x45, 0x89, 0x0c, 0xba, 0xb4, 0x9b, 0xb0, 0x45, 0x81, 0xb2, 0xbe, 0xaa, 0x41, 0xfb, 0x30,
	0xe2, 0x63, 0xef, 0x2c, 0x3c, 0x5d, 0xbe, 0x7f, 0x41, 0xbf, 0x82, 0x96, 0x33, 0x63, 0x5e, 0x68,
	0x7b, 0xae, 0x0e, 0xd5, 0x94, 0xf2, 0x73, 0x97, 0xdc, 0x86, 0xc6, 0x0c, 0x99, 0x8b, 0x89, 0x5c,
	0x4a, 0xe7, 0x71, 0x57, 0x2c, 0xe5, 0x74, 0xf9, 0x6f, 0xa9, 0xa3, 0xda, 0x46, 0x7e, 0x0f, 0x9d,
	0x30, 0x0b, 0x6c, 0xe6, 0xa4, 0x5e, 0x14, 0x72, 0xd3, 0x18, 0xd4, 0x86, 0x3d, 0x0a, 0x61, 0x16,
	0xec, 0x2b, 0x8d, 0xf5, 0x43, 0x0d, 0x3a, 0x15, 0x47, 0xf2, 0x3b, 0x00, 0x5c, 0xc6, 0x5e, 0xc2,
	0x84, 0xd9, 0xac, 0x0d, 0xb6, 0x04, 0xbe, 0xd4, 0x10, 0x0b, 0x7a, 0x09, 0x4e, 0xed, 0x89, 0x1f,
	0x39, 0x73, 0x3b, 0xcc, 0x02, 0x73, 0x4b, 0x42, 0x3a, 0x09, 0x4e, 0x0f, 0x84, 0xee, 0x38, 0x0b,
	0xc8, 0x10, 0xfa, 0x25, 0x26, 0x4e, 0x70, 0xea, 0x2d, 0xcd, 0xba, 0x84, 0xed, 0xe4, 0xb0, 0x13,
	0xa9, 0x25, 0x0f, 0xe1, 0x7a, 0xc0, 0x96, 0x76, 0x88, 0xa9, 0x9d, 0x89, 0xcd, 0xb7, 0x17, 0x51,
	0xe2, 0x8a, 0x34, 0x05, 0xb8, 0x1f, 0xb0, 0xe5, 0x31, 0xa6, 0xaf, 0x84, 0xe1, 0x8d, 0xd0, 0x93,
	0xbb, 0x20, 0x74, 0xb6, 0x13, 0x67, 0x1a, 0x1e, 0x70, 0x73, 0x5b, 0x62, 0x7b, 0x01, 0x5b, 0x3e,
	0x8d, 0x33, 0x89, 0x7d, 0xc1, 0x45, 0x51, 0x5d, 0xf4, 0xd9, 0xca, 0xe6, 0xe8, 0x98, 0x0d, 0x89,
	0x68, 0x49, 0xc5, 0x18, 0x1d, 0x6b, 0x0f, 0x88, 0x5c, 0xb1, 0x2a, 0x01, 0xc5, 0xb7, 0x19, 0xf2,
	0xd4, 0xfa, 0xb2, 0x01, 0x3b, 0x15, 0xf5, 0xbe, 0x33, 0x27, 0x43, 0x68, 0x38, 0x51, 0x10, 0xc8,
	0x3a, 0x88, 0x12, 0xf7, 0x45, 0x89, 0x95, 0xf9, 0xa9, 0xd4, 0x53, 0x6d, 0x27, 0x23, 0x68, 0xa5,
	0x09, 0x0b, 0xf9, 0x14, 0x13, 0xb9, 0x4f, 0x9d, 0xc7, 0xa4, 0xc4, 0x9e, 0x6a, 0x0b, 0x2d, 0x30,
	0x02, 0xef, 0xa2, 0x8f, 0x67, 0x2c, 0x45, 0xbd, 0x7d, 0x15, 0xfc, 0x33, 0x6d, 0xa1, 0x05, 0x86,
	0x3c, 0x01, 0xc8, 0xc2, 0xc2, 0xc3, 0x90, 0x1e, 0x7b, 0xa5, 0xc7, 0xab, 0xc2, 0x46, 0x2b, 0x38,
	0x91, 0x7f, 0x82, 0xd3, 0x2c, 0x74, 0xcd, 0xed, 0xcd, 0xfc, 0xa9, 0xd4, 0x53, 0x6d, 0x27, 0xf7,
	0xa0, 0x39, 0xc9, 0x56, 0x76, 0xc2, 0x02, 0xb3, 0xb1, 0x09, 0x3d, 0xc8, 0x56, 0x94, 0x05, 0xb4,
	0x31, 0x91, 0x5f, 0xf2, 0x77, 0xe8, 0x69, 0xa8, 0x3d, 0x59, 0xa5, 0xc8, 0xcd, 0xa6, 0x74, 0xb8,
	0xb1, 0xe9, 0x70, 0x20, 0x8c, 0xb4, 0x33, 0x29, 0x05, 0xf2, 0x00, 0x5a, 0x1c, 0x7d, 0x5f, 0x4e,
	0xd3, 0x92, 0x5e, 0xbb, 0xa5, 0xd7, 0x18, 0x7d, 0x5f, 0xcc, 0xd3, 0xe4, 0x6a, 0x40, 0xfe, 0x09,
	0xbd, 0xf3, 0x28, 0x45, 0x3b, 0x4e, 0x22, 0x37, 0x73, 0x30, 0x31, 0xdb, 0xd2, 0xe5, 0x66, 0xe9,
	0xf2, 0x3a, 0x4a, 0xf1, 0x44, 0x5b, 0x69, 0xf7, 0xbc, 0x22, 0x91, 0xbf, 0x42, 0x27, 0x8b, 0x5d,
	0x96, 0xa2, 0xcd, 0xb2, 0x74, 0x66, 0xc2, 0xa5, 0x8a, 0x49, 0xe3, 0x7e, 0x96, 0xce, 0x28, 0x64,
	0xc5, 0x58, 0xb8, 0x89, 0xea, 0xe5, 0x6e, 0x9d, 0x4d, 0xb7, 0x67, 0xd2, 0xa8, 0xdc, 0xdc, 0x62,
	0x4c, 0xfe, 0x0c, 0x6d, 0xdf, 0x0b, 0xe7, 0xca, 0xa9, 0xbb, 0xb9, 0x9f, 0xff, 0xf5, 0xc2, 0xb9,
	0x74, 0x69, 0xf9, 0x7a, 0x24, 0xd3, 0x0b, 0x4b, 0x97, 0xde, 0xe5, 0x0d, 0xcd, 0xa1, 0x62, 0x43,
	0xab, 0x6e, 0x21, 0x2e, 0x6c, 0xe6, 0x38, 0x51, 0x16, 0xa6, 0xe6, 0xce, 0xa6, 0xdb, 0x31, 0x2e,
	0xf6, 0x95, 0x8d, 0x42, 0x58, 0x8c, 0xc9, 0x7d, 0x68, 0x66, 0xe1, 0x3c, 0x8c, 0x16, 0xa1, 0x79,
	0x6d, 0xb3, 0xec, 0xaf, 0x94, 0x81, 0xe6, 0x08, 0xeb, 0x1f, 0xd0, 0x12, 0x46, 0xce, 0x31, 0x25,
	0x37, 0xa1, 0xc1, 0x02, 0x39, 0x95, 0xb8, 0x00, 0x84, 0x6a, 0x49, 0xe8, 0xf9, 0x2a, 0x98, 0x44,
	0xbe, 0x3c, 0xec, 0x06, 0xd5, 0x92, 0xf5, 0x1f, 0x79, 0xb3, 0x4e, 0x30, 0x09, 0x3c, 0xce, 0xc5,
	0xca, 0xf1, 0x1c, 0x7d, 0xb2, 0x07, 0xdb, 0xcc, 0x49, 0xa3, 0x44, 0x06, 0x31, 0xa8, 0x12, 0x04,
	0xd1, 0xc4, 0x05, 0x50, 0xc7, 0xa9, 0x68, 0xac, 0x18, 0xae, 0x8b, 0x3c, 0xb2, 0x74, 0x16, 0x25,
	0xde, 0x85, 0x24, 0x1f, 0x41, 0xb1, 0x04, 0x8c, 0x74, 0x15, 0xa3, 0x8c, 0xd5, 0xa3, 0x72, 0x4c,
	0xfa, 0x50, 0x2f, 0xb9, 0x56, 0x0c, 0x45, 0x82, 0x0b, 0xf4, 0xce, 0x66, 0xa9, 0xbc, 0x5d, 0x3d,
	0xaa, 0xa5, 0x75, 0xb2, 0x35, 0xd6, 0xc9, 0xd6, 0xfa, 0x14, 0x7e, 0xb9, 0x39, 0x63, 0x5e, 0xc1,
	0x87, 0xd0, 0xcc, 0x8b, 0xae, 0xa8, 0xe0, 0xfa, 0xe8, 0xf2, 0x42, 0x69, 0x8e, 0xa9, 0x4c, 0xbf,
	0x55, 0x9d, 0xde, 0x7a, 0x0e, 0x7b, 0x9b, 0x33, 0xbc, 0x61, 0x5e, 0x2a, 0x68, 0x7e, 0xc1, 0xbc,
	0x54, 0xb2, 0x95, 0x5a, 0x58, 0x53, 0xc8, 0x63, 0x74, 0xae, 0x0c, 0xf5, 0x5d, 0x0d, 0xfa, 0x9b,
	0xb1, 0xc8, 0x6f, 0xa0, 0x9d, 0xce, 0x12, 0xe4, 0xb3, 0xc8, 0x77, 0x75, 0xa0, 0x52, 0x41, 0x86,
	0x60, 0xcc, 0x71, 0xc5, 0xcd, 0xad, 0x41, 0xbd, 0x38, 0x36, 0x1b, 0xe5, 0xa5, 0x12, 0x41, 0x9e,
	0x40, 0x4b, 0x2f, 0x85, 0x9b, 0x75, 0x89, 0x36, 0x47, 0x57, 0x94, 0x86, 0x16, 0x48, 0x72, 0x1f,
	0xb6, 0x45, 0xd6, 0x5c, 0x16, 0x36, 0x67, 0x84, 0xcd, 0xb5, 0x52, 0x85, 0xb1, 0x2e, 0x64, 0x6b,
	0xaf, 0x92, 0x29, 0x31, 0xd7, 0x8b, 0x6c, 0x94, 0xf5, 0x24, 0x60, 0x84, 0x2c, 0x40, 0x7d, 0x4a,
	0xe4, 0x58, 0xf0, 0x10, 0xab, 0x06, 0xd7, 0x89, 0xbe, 0x73, 0x63, 0xd6, 0x91, 0xd6, 0xe7, 0x35,
	0xd8, 0xbd, 0xc4, 0xce, 0xf2, 0x50, 0x63, 0x28, 0x1a, 0x6a, 0x4d, 0x1f, 0x6a, 0x29, 0x91, 0x5b,
	0xd0, 0x4a, 0xd0, 0x41, 0xef, 0x5c, 0x73, 0xbb, 0x41, 0x0b, 0x99, 0xdc, 0x81, 0xd6, 0xdb, 0x8c,
	0x85, 0xa9, 0x97, 0xae, 0x34, 0x8f, 0xb7, 0x47, 0xf9, 0xed, 0xa1, 0x85, 0x49, 0xe4, 0x1f, 0x60,
	0x10, 0x49, 0xe2, 0x6e, 0x53, 0x39, 0xb6, 0xbe, 0xaf, 0x26, 0x91, 0x53, 0xfe, 0x07, 0x25, 0xf1,
	0x00, 0xba, 0xa2, 0x81, 0x5e, 0x9d, 0x48, 0x27, 0xc4, 0xf4, 0x7f, 0x79, 0x2e, 0x0f, 0xa0, 0x2b,
	0xfa, 0x67, 0x81, 0x36, 0x2e, 0xa1, 0x9d, 0x38, 0x2b, 0xd0, 0xb7, 0x2a, 0x8d, 0x6d, 0x5b, 0xfe,
	0x4d, 0x15, 0xb2, 0xf5, 0x6d, 0x4d, 0x5d, 0xd1, 0x8d, 0x16, 0xf4, 0x73, 0x5b, 0x83, 0x75, 0xb7,
	0x72, 0xd4, 0x54, 0xdf, 0x13, 0x94, 0x14, 0x2d, 0xc2, 0x22, 0x43, 0x25, 0x58, 0x9f, 0x55, 0x80,
	0xaa, 0x89, 0x09, 0x60, 0xcc, 0x56, 0x25, 0x50, 0x0a, 0x1f, 0xe1, 0x48, 0x58, 0x9f, 0x28, 0x2a,
	0xd8, 0x6c, 0x98, 0x1f, 0x30, 0xe1, 0x1e, 0x6c, 0xab, 0x46, 0xac, 0xa8, 0x4e, 0x09, 0xd6, 0x81,
	0xa2, 0x87, 0x6a, 0x6b, 0x7d, 0xcf, 0x05, 0x2b, 0x62, 0x6c, 0x49, 0x9e, 0xd7, 0x31, 0x18, 0xdc,
	0x78, 0x67, 0xaf, 0x15, 0x70, 0xd1, 0x6d, 0x8b, 0x24, 0xa5, 0x20, 0x53, 0x4f, 0xa2, 0xe5, 0x4a,
	0x67, 0xa8, 0x04, 0xc1, 0x49, 0x79, 0x07, 0x57, 0x64, 0x62, 0xd0, 0x52, 0x61, 0x7d, 0xbd, 0x76,
	0x86, 0xca, 0x46, 0x7c, 0x75, 0xaa, 0x3f, 0xd1, 0x37, 0xc4, 0xe9, 0x8b, 0x59, 0x82, 0xa1, 0xa2,
	0x7e, 0x83, 0x6a, 0x49, 0xfc, 0xf8, 0xcb, 0x5e, 0x6b, 0x54, 0x3a, 0x60, 0x95, 0x15, 0xa8, 0x34,
	0x5b, 0x2f, 0x2b, 0xf9, 0x94, 0xdd, 0xfe, 0xc3, 0xf3, 0xb1, 0x16, 0x95, 0x6b, 0x9e, 0xff, 0x09,
	0xbc, 0x9f, 0xea, 0x9c, 0xc8, 0x2d, 0xa8, 0x4e, 0x8c, 0x8b, 0x9e, 0xa7, 0x16, 0xa4, 0x7a, 0xde,
	0x00, 0x3a, 0x09, 0xbe, 0xcd, 0xbc, 0x04, 0x03, 0xb1, 0x56, 0x43, 0x9a, 0xaa, 0x2a, 0xeb, 0xcd,
	0xda, 0xed, 0xf4, 0x3f, 0xda, 0xd4, 0xd6, 0x37, 0xd5, 0x3d, 0x2b, 0x7f, 0x39, 0x44, 0x64, 0x27,
	0x41, 0x56, 0x76, 0xfa, 0x5c, 0x7c, 0x27, 0x7f, 0xdf, 0xcd, 0xaf, 0x60, 0xfd, 0xaa, 0x0d, 0x51,
	0x76, 0x72, 0x0f, 0x1a, 0xe2, 0xf9, 0x72, 0x8e, 0x57, 0x6f, 0x9d, 0x06, 0x58, 0xc7, 0x95, 0x43,
	0xaf, 0x7f, 0x6c, 0xe4, 0x53, 0x80, 0xa5, 0xcc, 0xe6, 0xde, 0x45, 0xfe, 0xd7, 0xd0, 0x12, 0x8a,
	0xb1, 0x77, 0x81, 0xe4, 0xb7, 0x00, 0xd2, 0xe8, 0xcc, 0xb2, 0x70, 0xae, 0x7f, 0x20, 0x24, 0xfc,
	0xa9, 0x50, 0x58, 0x5f, 0xa8, 0xc7, 0x91, 0x78, 0xa9, 0xa1, 0x7b, 0xba, 0x14, 0xaf, 0x29, 0xee,
	0x9d, 0x85, 0x2c, 0xcd, 0x12, 0xb4, 0xcf, 0x75, 0x34, 0x28, 0x54, 0xaf, 0xd7, 0x01, 0x89, 0x0e,
	0x58, 0x02, 0xe8, 0x3a, 0x40, 0x5d, 0xd9, 0x2a, 0x60, 0x2c, 0x4a, 0x35, 0x63, 0x5c, 0x1d, 0xd3,
	0x2e, 0x95, 0xe3, 0x3f, 0xfd, 0x45, 0x2e, 0x6b, 0xed, 0x99, 0x4a, 0x9a, 0x50, 0x3f, 0x7c, 0x39,
	0xee, 0xff, 0x82, 0x00, 0x34, 0x0e, 0x5f, 0x8e, 0xed, 0xa3, 0x47, 0xfd, 0x5a, 0x3e, 0xa6, 0x8f,
	0xfa, 0x5b, 0x07, 0x7f, 0x83, 0x3f, 0x3a, 0x51, 0x30, 0xe2, 0x33, 0x16, 0x23, 0x9f, 0x79, 0xd3,
	0x74, 0x34, 0x47, 0x8c, 0xe7, 0xb8, 0x1a, 0xf9, 0xde, 0x44, 0xbd, 0xaf, 0x27, 0xd9, 0xf4, 0x60,
	0xf7, 0x08, 0x31, 0x3e, 0xc2, 0xd5, 0x0b, 0xf5, 0xfa, 0x3e, 0x8c, 0xf8, 0x8f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0xb2, 0xb7, 0xe5, 0x8a, 0x0f, 0x00, 0x00,
}
