// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package kkProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Type of failures returned by Failure message
// @used_in Failure
type FailureType int32

const (
	FailureType_Failure_UnexpectedMessage FailureType = 1
	FailureType_Failure_ButtonExpected    FailureType = 2
	FailureType_Failure_SyntaxError       FailureType = 3
	FailureType_Failure_ActionCancelled   FailureType = 4
	FailureType_Failure_PinExpected       FailureType = 5
	FailureType_Failure_PinCancelled      FailureType = 6
	FailureType_Failure_PinInvalid        FailureType = 7
	FailureType_Failure_InvalidSignature  FailureType = 8
	FailureType_Failure_Other             FailureType = 9
	FailureType_Failure_NotEnoughFunds    FailureType = 10
	FailureType_Failure_NotInitialized    FailureType = 11
	FailureType_Failure_PinMismatch       FailureType = 12
	FailureType_Failure_FirmwareError     FailureType = 99
)

var FailureType_name = map[int32]string{
	1:  "Failure_UnexpectedMessage",
	2:  "Failure_ButtonExpected",
	3:  "Failure_SyntaxError",
	4:  "Failure_ActionCancelled",
	5:  "Failure_PinExpected",
	6:  "Failure_PinCancelled",
	7:  "Failure_PinInvalid",
	8:  "Failure_InvalidSignature",
	9:  "Failure_Other",
	10: "Failure_NotEnoughFunds",
	11: "Failure_NotInitialized",
	12: "Failure_PinMismatch",
	99: "Failure_FirmwareError",
}
var FailureType_value = map[string]int32{
	"Failure_UnexpectedMessage": 1,
	"Failure_ButtonExpected":    2,
	"Failure_SyntaxError":       3,
	"Failure_ActionCancelled":   4,
	"Failure_PinExpected":       5,
	"Failure_PinCancelled":      6,
	"Failure_PinInvalid":        7,
	"Failure_InvalidSignature":  8,
	"Failure_Other":             9,
	"Failure_NotEnoughFunds":    10,
	"Failure_NotInitialized":    11,
	"Failure_PinMismatch":       12,
	"Failure_FirmwareError":     99,
}

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}
func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}
func (x *FailureType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FailureType_value, data, "FailureType")
	if err != nil {
		return err
	}
	*x = FailureType(value)
	return nil
}
func (FailureType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{0}
}

// *
// Type of script which will be used for transaction output
// @used_in TxOutputType
type OutputScriptType int32

const (
	OutputScriptType_PAYTOADDRESS     OutputScriptType = 0
	OutputScriptType_PAYTOSCRIPTHASH  OutputScriptType = 1
	OutputScriptType_PAYTOMULTISIG    OutputScriptType = 2
	OutputScriptType_PAYTOOPRETURN    OutputScriptType = 3
	OutputScriptType_PAYTOWITNESS     OutputScriptType = 4
	OutputScriptType_PAYTOP2SHWITNESS OutputScriptType = 5
)

var OutputScriptType_name = map[int32]string{
	0: "PAYTOADDRESS",
	1: "PAYTOSCRIPTHASH",
	2: "PAYTOMULTISIG",
	3: "PAYTOOPRETURN",
	4: "PAYTOWITNESS",
	5: "PAYTOP2SHWITNESS",
}
var OutputScriptType_value = map[string]int32{
	"PAYTOADDRESS":     0,
	"PAYTOSCRIPTHASH":  1,
	"PAYTOMULTISIG":    2,
	"PAYTOOPRETURN":    3,
	"PAYTOWITNESS":     4,
	"PAYTOP2SHWITNESS": 5,
}

func (x OutputScriptType) Enum() *OutputScriptType {
	p := new(OutputScriptType)
	*p = x
	return p
}
func (x OutputScriptType) String() string {
	return proto.EnumName(OutputScriptType_name, int32(x))
}
func (x *OutputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputScriptType_value, data, "OutputScriptType")
	if err != nil {
		return err
	}
	*x = OutputScriptType(value)
	return nil
}
func (OutputScriptType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{1}
}

// *
// Type of script which will be used for transaction output
// @used_in TxInputType
type InputScriptType int32

const (
	InputScriptType_SPENDADDRESS     InputScriptType = 0
	InputScriptType_SPENDMULTISIG    InputScriptType = 1
	InputScriptType_EXTERNAL         InputScriptType = 2
	InputScriptType_SPENDWITNESS     InputScriptType = 3
	InputScriptType_SPENDP2SHWITNESS InputScriptType = 4
)

var InputScriptType_name = map[int32]string{
	0: "SPENDADDRESS",
	1: "SPENDMULTISIG",
	2: "EXTERNAL",
	3: "SPENDWITNESS",
	4: "SPENDP2SHWITNESS",
}
var InputScriptType_value = map[string]int32{
	"SPENDADDRESS":     0,
	"SPENDMULTISIG":    1,
	"EXTERNAL":         2,
	"SPENDWITNESS":     3,
	"SPENDP2SHWITNESS": 4,
}

func (x InputScriptType) Enum() *InputScriptType {
	p := new(InputScriptType)
	*p = x
	return p
}
func (x InputScriptType) String() string {
	return proto.EnumName(InputScriptType_name, int32(x))
}
func (x *InputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InputScriptType_value, data, "InputScriptType")
	if err != nil {
		return err
	}
	*x = InputScriptType(value)
	return nil
}
func (InputScriptType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{2}
}

// *
// Type of information required by transaction signing process
// @used_in TxRequest
type RequestType int32

const (
	RequestType_TXINPUT     RequestType = 0
	RequestType_TXOUTPUT    RequestType = 1
	RequestType_TXMETA      RequestType = 2
	RequestType_TXFINISHED  RequestType = 3
	RequestType_TXEXTRADATA RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "TXINPUT",
	1: "TXOUTPUT",
	2: "TXMETA",
	3: "TXFINISHED",
	4: "TXEXTRADATA",
}
var RequestType_value = map[string]int32{
	"TXINPUT":     0,
	"TXOUTPUT":    1,
	"TXMETA":      2,
	"TXFINISHED":  3,
	"TXEXTRADATA": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{3}
}

// *
// Type of ouput address specify in transaction
// @used_in TxOutputType
type OutputAddressType int32

const (
	OutputAddressType_SPEND    OutputAddressType = 0
	OutputAddressType_TRANSFER OutputAddressType = 1
	OutputAddressType_CHANGE   OutputAddressType = 2
	OutputAddressType_EXCHANGE OutputAddressType = 3
)

var OutputAddressType_name = map[int32]string{
	0: "SPEND",
	1: "TRANSFER",
	2: "CHANGE",
	3: "EXCHANGE",
}
var OutputAddressType_value = map[string]int32{
	"SPEND":    0,
	"TRANSFER": 1,
	"CHANGE":   2,
	"EXCHANGE": 3,
}

func (x OutputAddressType) Enum() *OutputAddressType {
	p := new(OutputAddressType)
	*p = x
	return p
}
func (x OutputAddressType) String() string {
	return proto.EnumName(OutputAddressType_name, int32(x))
}
func (x *OutputAddressType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputAddressType_value, data, "OutputAddressType")
	if err != nil {
		return err
	}
	*x = OutputAddressType(value)
	return nil
}
func (OutputAddressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{4}
}

// *
// Type of button request
// @used_in ButtonRequest
type ButtonRequestType int32

const (
	ButtonRequestType_ButtonRequest_Other                     ButtonRequestType = 1
	ButtonRequestType_ButtonRequest_FeeOverThreshold          ButtonRequestType = 2
	ButtonRequestType_ButtonRequest_ConfirmOutput             ButtonRequestType = 3
	ButtonRequestType_ButtonRequest_ResetDevice               ButtonRequestType = 4
	ButtonRequestType_ButtonRequest_ConfirmWord               ButtonRequestType = 5
	ButtonRequestType_ButtonRequest_WipeDevice                ButtonRequestType = 6
	ButtonRequestType_ButtonRequest_ProtectCall               ButtonRequestType = 7
	ButtonRequestType_ButtonRequest_SignTx                    ButtonRequestType = 8
	ButtonRequestType_ButtonRequest_FirmwareCheck             ButtonRequestType = 9
	ButtonRequestType_ButtonRequest_Address                   ButtonRequestType = 10
	ButtonRequestType_ButtonRequest_FirmwareErase             ButtonRequestType = 11
	ButtonRequestType_ButtonRequest_ConfirmTransferToAccount  ButtonRequestType = 12
	ButtonRequestType_ButtonRequest_ConfirmTransferToNodePath ButtonRequestType = 13
	ButtonRequestType_ButtonRequest_ChangeLabel               ButtonRequestType = 14
	ButtonRequestType_ButtonRequest_ChangeLanguage            ButtonRequestType = 15
	ButtonRequestType_ButtonRequest_EnablePassphrase          ButtonRequestType = 16
	ButtonRequestType_ButtonRequest_DisablePassphrase         ButtonRequestType = 17
	ButtonRequestType_ButtonRequest_EncryptAndSignMessage     ButtonRequestType = 18
	ButtonRequestType_ButtonRequest_EncryptMessage            ButtonRequestType = 19
	ButtonRequestType_ButtonRequest_ImportPrivateKey          ButtonRequestType = 20
	ButtonRequestType_ButtonRequest_ImportRecoverySentence    ButtonRequestType = 21
	ButtonRequestType_ButtonRequest_SignIdentity              ButtonRequestType = 22
	ButtonRequestType_ButtonRequest_Ping                      ButtonRequestType = 23
	ButtonRequestType_ButtonRequest_RemovePin                 ButtonRequestType = 24
	ButtonRequestType_ButtonRequest_ChangePin                 ButtonRequestType = 25
	ButtonRequestType_ButtonRequest_CreatePin                 ButtonRequestType = 26
	ButtonRequestType_ButtonRequest_GetEntropy                ButtonRequestType = 27
	ButtonRequestType_ButtonRequest_SignMessage               ButtonRequestType = 28
	ButtonRequestType_ButtonRequest_ApplyPolicies             ButtonRequestType = 29
	ButtonRequestType_ButtonRequest_SignExchange              ButtonRequestType = 30
	ButtonRequestType_ButtonRequest_AutoLockDelayMs           ButtonRequestType = 31
	ButtonRequestType_ButtonRequest_U2FCounter                ButtonRequestType = 32
	ButtonRequestType_ButtonRequest_ConfirmEosAction          ButtonRequestType = 33
	ButtonRequestType_ButtonRequest_ConfirmEosBudget          ButtonRequestType = 34
	ButtonRequestType_ButtonRequest_ConfirmMemo               ButtonRequestType = 35
)

var ButtonRequestType_name = map[int32]string{
	1:  "ButtonRequest_Other",
	2:  "ButtonRequest_FeeOverThreshold",
	3:  "ButtonRequest_ConfirmOutput",
	4:  "ButtonRequest_ResetDevice",
	5:  "ButtonRequest_ConfirmWord",
	6:  "ButtonRequest_WipeDevice",
	7:  "ButtonRequest_ProtectCall",
	8:  "ButtonRequest_SignTx",
	9:  "ButtonRequest_FirmwareCheck",
	10: "ButtonRequest_Address",
	11: "ButtonRequest_FirmwareErase",
	12: "ButtonRequest_ConfirmTransferToAccount",
	13: "ButtonRequest_ConfirmTransferToNodePath",
	14: "ButtonRequest_ChangeLabel",
	15: "ButtonRequest_ChangeLanguage",
	16: "ButtonRequest_EnablePassphrase",
	17: "ButtonRequest_DisablePassphrase",
	18: "ButtonRequest_EncryptAndSignMessage",
	19: "ButtonRequest_EncryptMessage",
	20: "ButtonRequest_ImportPrivateKey",
	21: "ButtonRequest_ImportRecoverySentence",
	22: "ButtonRequest_SignIdentity",
	23: "ButtonRequest_Ping",
	24: "ButtonRequest_RemovePin",
	25: "ButtonRequest_ChangePin",
	26: "ButtonRequest_CreatePin",
	27: "ButtonRequest_GetEntropy",
	28: "ButtonRequest_SignMessage",
	29: "ButtonRequest_ApplyPolicies",
	30: "ButtonRequest_SignExchange",
	31: "ButtonRequest_AutoLockDelayMs",
	32: "ButtonRequest_U2FCounter",
	33: "ButtonRequest_ConfirmEosAction",
	34: "ButtonRequest_ConfirmEosBudget",
	35: "ButtonRequest_ConfirmMemo",
}
var ButtonRequestType_value = map[string]int32{
	"ButtonRequest_Other":                     1,
	"ButtonRequest_FeeOverThreshold":          2,
	"ButtonRequest_ConfirmOutput":             3,
	"ButtonRequest_ResetDevice":               4,
	"ButtonRequest_ConfirmWord":               5,
	"ButtonRequest_WipeDevice":                6,
	"ButtonRequest_ProtectCall":               7,
	"ButtonRequest_SignTx":                    8,
	"ButtonRequest_FirmwareCheck":             9,
	"ButtonRequest_Address":                   10,
	"ButtonRequest_FirmwareErase":             11,
	"ButtonRequest_ConfirmTransferToAccount":  12,
	"ButtonRequest_ConfirmTransferToNodePath": 13,
	"ButtonRequest_ChangeLabel":               14,
	"ButtonRequest_ChangeLanguage":            15,
	"ButtonRequest_EnablePassphrase":          16,
	"ButtonRequest_DisablePassphrase":         17,
	"ButtonRequest_EncryptAndSignMessage":     18,
	"ButtonRequest_EncryptMessage":            19,
	"ButtonRequest_ImportPrivateKey":          20,
	"ButtonRequest_ImportRecoverySentence":    21,
	"ButtonRequest_SignIdentity":              22,
	"ButtonRequest_Ping":                      23,
	"ButtonRequest_RemovePin":                 24,
	"ButtonRequest_ChangePin":                 25,
	"ButtonRequest_CreatePin":                 26,
	"ButtonRequest_GetEntropy":                27,
	"ButtonRequest_SignMessage":               28,
	"ButtonRequest_ApplyPolicies":             29,
	"ButtonRequest_SignExchange":              30,
	"ButtonRequest_AutoLockDelayMs":           31,
	"ButtonRequest_U2FCounter":                32,
	"ButtonRequest_ConfirmEosAction":          33,
	"ButtonRequest_ConfirmEosBudget":          34,
	"ButtonRequest_ConfirmMemo":               35,
}

func (x ButtonRequestType) Enum() *ButtonRequestType {
	p := new(ButtonRequestType)
	*p = x
	return p
}
func (x ButtonRequestType) String() string {
	return proto.EnumName(ButtonRequestType_name, int32(x))
}
func (x *ButtonRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ButtonRequestType_value, data, "ButtonRequestType")
	if err != nil {
		return err
	}
	*x = ButtonRequestType(value)
	return nil
}
func (ButtonRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{5}
}

// *
// Type of PIN request
// @used_in PinMatrixRequest
type PinMatrixRequestType int32

const (
	PinMatrixRequestType_PinMatrixRequestType_Current   PinMatrixRequestType = 1
	PinMatrixRequestType_PinMatrixRequestType_NewFirst  PinMatrixRequestType = 2
	PinMatrixRequestType_PinMatrixRequestType_NewSecond PinMatrixRequestType = 3
)

var PinMatrixRequestType_name = map[int32]string{
	1: "PinMatrixRequestType_Current",
	2: "PinMatrixRequestType_NewFirst",
	3: "PinMatrixRequestType_NewSecond",
}
var PinMatrixRequestType_value = map[string]int32{
	"PinMatrixRequestType_Current":   1,
	"PinMatrixRequestType_NewFirst":  2,
	"PinMatrixRequestType_NewSecond": 3,
}

func (x PinMatrixRequestType) Enum() *PinMatrixRequestType {
	p := new(PinMatrixRequestType)
	*p = x
	return p
}
func (x PinMatrixRequestType) String() string {
	return proto.EnumName(PinMatrixRequestType_name, int32(x))
}
func (x *PinMatrixRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PinMatrixRequestType_value, data, "PinMatrixRequestType")
	if err != nil {
		return err
	}
	*x = PinMatrixRequestType(value)
	return nil
}
func (PinMatrixRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{6}
}

// *
// Structure representing BIP32 (hierarchical deterministic) node
// Used for imports of private key into the device and exporting public key out of device
// @used_in PublicKey
// @used_in LoadDevice
// @used_in DebugLinkState
// @used_in Storage
type HDNodeType struct {
	Depth                *uint32  `protobuf:"varint,1,req,name=depth" json:"depth,omitempty"`
	Fingerprint          *uint32  `protobuf:"varint,2,req,name=fingerprint" json:"fingerprint,omitempty"`
	ChildNum             *uint32  `protobuf:"varint,3,req,name=child_num,json=childNum" json:"child_num,omitempty"`
	ChainCode            []byte   `protobuf:"bytes,4,req,name=chain_code,json=chainCode" json:"chain_code,omitempty"`
	PrivateKey           []byte   `protobuf:"bytes,5,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,6,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HDNodeType) Reset()         { *m = HDNodeType{} }
func (m *HDNodeType) String() string { return proto.CompactTextString(m) }
func (*HDNodeType) ProtoMessage()    {}
func (*HDNodeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{0}
}
func (m *HDNodeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HDNodeType.Unmarshal(m, b)
}
func (m *HDNodeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HDNodeType.Marshal(b, m, deterministic)
}
func (dst *HDNodeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HDNodeType.Merge(dst, src)
}
func (m *HDNodeType) XXX_Size() int {
	return xxx_messageInfo_HDNodeType.Size(m)
}
func (m *HDNodeType) XXX_DiscardUnknown() {
	xxx_messageInfo_HDNodeType.DiscardUnknown(m)
}

var xxx_messageInfo_HDNodeType proto.InternalMessageInfo

func (m *HDNodeType) GetDepth() uint32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *HDNodeType) GetFingerprint() uint32 {
	if m != nil && m.Fingerprint != nil {
		return *m.Fingerprint
	}
	return 0
}

func (m *HDNodeType) GetChildNum() uint32 {
	if m != nil && m.ChildNum != nil {
		return *m.ChildNum
	}
	return 0
}

func (m *HDNodeType) GetChainCode() []byte {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

func (m *HDNodeType) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HDNodeType) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HDNodePathType struct {
	Node                 *HDNodeType `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	AddressN             []uint32    `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HDNodePathType) Reset()         { *m = HDNodePathType{} }
func (m *HDNodePathType) String() string { return proto.CompactTextString(m) }
func (*HDNodePathType) ProtoMessage()    {}
func (*HDNodePathType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{1}
}
func (m *HDNodePathType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HDNodePathType.Unmarshal(m, b)
}
func (m *HDNodePathType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HDNodePathType.Marshal(b, m, deterministic)
}
func (dst *HDNodePathType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HDNodePathType.Merge(dst, src)
}
func (m *HDNodePathType) XXX_Size() int {
	return xxx_messageInfo_HDNodePathType.Size(m)
}
func (m *HDNodePathType) XXX_DiscardUnknown() {
	xxx_messageInfo_HDNodePathType.DiscardUnknown(m)
}

var xxx_messageInfo_HDNodePathType proto.InternalMessageInfo

func (m *HDNodePathType) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HDNodePathType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

// *
// Structure representing Coin
// @used_in Features
type CoinType struct {
	CoinName        *string `protobuf:"bytes,1,opt,name=coin_name,json=coinName" json:"coin_name,omitempty"`
	CoinShortcut    *string `protobuf:"bytes,2,opt,name=coin_shortcut,json=coinShortcut" json:"coin_shortcut,omitempty"`
	AddressType     *uint32 `protobuf:"varint,3,opt,name=address_type,json=addressType,def=0" json:"address_type,omitempty"`
	MaxfeeKb        *uint64 `protobuf:"varint,4,opt,name=maxfee_kb,json=maxfeeKb" json:"maxfee_kb,omitempty"`
	AddressTypeP2Sh *uint32 `protobuf:"varint,5,opt,name=address_type_p2sh,json=addressTypeP2sh,def=5" json:"address_type_p2sh,omitempty"`
	// optional uint32 address_type_p2wpkh = 6 [default=6]; REMOVED
	// optional uint32 address_type_p2wsh = 7 [default=10]; REMOVED
	SignedMessageHeader *string `protobuf:"bytes,8,opt,name=signed_message_header,json=signedMessageHeader" json:"signed_message_header,omitempty"`
	Bip44AccountPath    *uint32 `protobuf:"varint,9,opt,name=bip44_account_path,json=bip44AccountPath" json:"bip44_account_path,omitempty"`
	Forkid              *uint32 `protobuf:"varint,12,opt,name=forkid" json:"forkid,omitempty"`
	Decimals            *uint32 `protobuf:"varint,13,opt,name=decimals" json:"decimals,omitempty"`
	ContractAddress     []byte  `protobuf:"bytes,14,opt,name=contract_address,json=contractAddress" json:"contract_address,omitempty"`
	// optional bytes gas_limit = 15; REMOVED
	XpubMagic *uint32 `protobuf:"varint,16,opt,name=xpub_magic,json=xpubMagic,def=76067358" json:"xpub_magic,omitempty"`
	// optional uint32 xprv_magic = 17 [default=76066276]; REMOVED
	Segwit         *bool   `protobuf:"varint,18,opt,name=segwit" json:"segwit,omitempty"`
	ForceBip143    *bool   `protobuf:"varint,19,opt,name=force_bip143,json=forceBip143" json:"force_bip143,omitempty"`
	CurveName      *string `protobuf:"bytes,20,opt,name=curve_name,json=curveName" json:"curve_name,omitempty"`
	CashaddrPrefix *string `protobuf:"bytes,21,opt,name=cashaddr_prefix,json=cashaddrPrefix" json:"cashaddr_prefix,omitempty"`
	Bech32Prefix   *string `protobuf:"bytes,22,opt,name=bech32_prefix,json=bech32Prefix" json:"bech32_prefix,omitempty"`
	Decred         *bool   `protobuf:"varint,23,opt,name=decred" json:"decred,omitempty"`
	// optional uint32 version_group_id = 24; REMOVED
	XpubMagicSegwitP2Sh   *uint32  `protobuf:"varint,25,opt,name=xpub_magic_segwit_p2sh,json=xpubMagicSegwitP2sh" json:"xpub_magic_segwit_p2sh,omitempty"`
	XpubMagicSegwitNative *uint32  `protobuf:"varint,26,opt,name=xpub_magic_segwit_native,json=xpubMagicSegwitNative" json:"xpub_magic_segwit_native,omitempty"`
	NanoaddrPrefix        *string  `protobuf:"bytes,27,opt,name=nanoaddr_prefix,json=nanoaddrPrefix" json:"nanoaddr_prefix,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CoinType) Reset()         { *m = CoinType{} }
func (m *CoinType) String() string { return proto.CompactTextString(m) }
func (*CoinType) ProtoMessage()    {}
func (*CoinType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{2}
}
func (m *CoinType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinType.Unmarshal(m, b)
}
func (m *CoinType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinType.Marshal(b, m, deterministic)
}
func (dst *CoinType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinType.Merge(dst, src)
}
func (m *CoinType) XXX_Size() int {
	return xxx_messageInfo_CoinType.Size(m)
}
func (m *CoinType) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinType.DiscardUnknown(m)
}

var xxx_messageInfo_CoinType proto.InternalMessageInfo

const Default_CoinType_AddressType uint32 = 0
const Default_CoinType_AddressTypeP2Sh uint32 = 5
const Default_CoinType_XpubMagic uint32 = 76067358

func (m *CoinType) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return ""
}

func (m *CoinType) GetCoinShortcut() string {
	if m != nil && m.CoinShortcut != nil {
		return *m.CoinShortcut
	}
	return ""
}

func (m *CoinType) GetAddressType() uint32 {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return Default_CoinType_AddressType
}

func (m *CoinType) GetMaxfeeKb() uint64 {
	if m != nil && m.MaxfeeKb != nil {
		return *m.MaxfeeKb
	}
	return 0
}

func (m *CoinType) GetAddressTypeP2Sh() uint32 {
	if m != nil && m.AddressTypeP2Sh != nil {
		return *m.AddressTypeP2Sh
	}
	return Default_CoinType_AddressTypeP2Sh
}

func (m *CoinType) GetSignedMessageHeader() string {
	if m != nil && m.SignedMessageHeader != nil {
		return *m.SignedMessageHeader
	}
	return ""
}

func (m *CoinType) GetBip44AccountPath() uint32 {
	if m != nil && m.Bip44AccountPath != nil {
		return *m.Bip44AccountPath
	}
	return 0
}

func (m *CoinType) GetForkid() uint32 {
	if m != nil && m.Forkid != nil {
		return *m.Forkid
	}
	return 0
}

func (m *CoinType) GetDecimals() uint32 {
	if m != nil && m.Decimals != nil {
		return *m.Decimals
	}
	return 0
}

func (m *CoinType) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *CoinType) GetXpubMagic() uint32 {
	if m != nil && m.XpubMagic != nil {
		return *m.XpubMagic
	}
	return Default_CoinType_XpubMagic
}

func (m *CoinType) GetSegwit() bool {
	if m != nil && m.Segwit != nil {
		return *m.Segwit
	}
	return false
}

func (m *CoinType) GetForceBip143() bool {
	if m != nil && m.ForceBip143 != nil {
		return *m.ForceBip143
	}
	return false
}

func (m *CoinType) GetCurveName() string {
	if m != nil && m.CurveName != nil {
		return *m.CurveName
	}
	return ""
}

func (m *CoinType) GetCashaddrPrefix() string {
	if m != nil && m.CashaddrPrefix != nil {
		return *m.CashaddrPrefix
	}
	return ""
}

func (m *CoinType) GetBech32Prefix() string {
	if m != nil && m.Bech32Prefix != nil {
		return *m.Bech32Prefix
	}
	return ""
}

func (m *CoinType) GetDecred() bool {
	if m != nil && m.Decred != nil {
		return *m.Decred
	}
	return false
}

func (m *CoinType) GetXpubMagicSegwitP2Sh() uint32 {
	if m != nil && m.XpubMagicSegwitP2Sh != nil {
		return *m.XpubMagicSegwitP2Sh
	}
	return 0
}

func (m *CoinType) GetXpubMagicSegwitNative() uint32 {
	if m != nil && m.XpubMagicSegwitNative != nil {
		return *m.XpubMagicSegwitNative
	}
	return 0
}

func (m *CoinType) GetNanoaddrPrefix() string {
	if m != nil && m.NanoaddrPrefix != nil {
		return *m.NanoaddrPrefix
	}
	return ""
}

// *
// Type of redeem script used in input
// @used_in TxInputType
type MultisigRedeemScriptType struct {
	Pubkeys              []*HDNodePathType `protobuf:"bytes,1,rep,name=pubkeys" json:"pubkeys,omitempty"`
	Signatures           [][]byte          `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
	M                    *uint32           `protobuf:"varint,3,opt,name=m" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MultisigRedeemScriptType) Reset()         { *m = MultisigRedeemScriptType{} }
func (m *MultisigRedeemScriptType) String() string { return proto.CompactTextString(m) }
func (*MultisigRedeemScriptType) ProtoMessage()    {}
func (*MultisigRedeemScriptType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{3}
}
func (m *MultisigRedeemScriptType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultisigRedeemScriptType.Unmarshal(m, b)
}
func (m *MultisigRedeemScriptType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultisigRedeemScriptType.Marshal(b, m, deterministic)
}
func (dst *MultisigRedeemScriptType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultisigRedeemScriptType.Merge(dst, src)
}
func (m *MultisigRedeemScriptType) XXX_Size() int {
	return xxx_messageInfo_MultisigRedeemScriptType.Size(m)
}
func (m *MultisigRedeemScriptType) XXX_DiscardUnknown() {
	xxx_messageInfo_MultisigRedeemScriptType.DiscardUnknown(m)
}

var xxx_messageInfo_MultisigRedeemScriptType proto.InternalMessageInfo

func (m *MultisigRedeemScriptType) GetPubkeys() []*HDNodePathType {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetM() uint32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

// *
// Structure representing transaction input
// @used_in TransactionType
type TxInputType struct {
	AddressN             []uint32                  `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	PrevHash             []byte                    `protobuf:"bytes,2,req,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	PrevIndex            *uint32                   `protobuf:"varint,3,req,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	ScriptSig            []byte                    `protobuf:"bytes,4,opt,name=script_sig,json=scriptSig" json:"script_sig,omitempty"`
	Sequence             *uint32                   `protobuf:"varint,5,opt,name=sequence,def=4294967295" json:"sequence,omitempty"`
	ScriptType           *InputScriptType          `protobuf:"varint,6,opt,name=script_type,json=scriptType,enum=InputScriptType,def=0" json:"script_type,omitempty"`
	Multisig             *MultisigRedeemScriptType `protobuf:"bytes,7,opt,name=multisig" json:"multisig,omitempty"`
	Amount               *uint64                   `protobuf:"varint,8,opt,name=amount" json:"amount,omitempty"`
	DecredTree           *uint32                   `protobuf:"varint,9,opt,name=decred_tree,json=decredTree" json:"decred_tree,omitempty"`
	DecredScriptVersion  *uint32                   `protobuf:"varint,10,opt,name=decred_script_version,json=decredScriptVersion" json:"decred_script_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TxInputType) Reset()         { *m = TxInputType{} }
func (m *TxInputType) String() string { return proto.CompactTextString(m) }
func (*TxInputType) ProtoMessage()    {}
func (*TxInputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{4}
}
func (m *TxInputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInputType.Unmarshal(m, b)
}
func (m *TxInputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInputType.Marshal(b, m, deterministic)
}
func (dst *TxInputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInputType.Merge(dst, src)
}
func (m *TxInputType) XXX_Size() int {
	return xxx_messageInfo_TxInputType.Size(m)
}
func (m *TxInputType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInputType.DiscardUnknown(m)
}

var xxx_messageInfo_TxInputType proto.InternalMessageInfo

const Default_TxInputType_Sequence uint32 = 4294967295
const Default_TxInputType_ScriptType InputScriptType = InputScriptType_SPENDADDRESS

func (m *TxInputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxInputType) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxInputType) GetPrevIndex() uint32 {
	if m != nil && m.PrevIndex != nil {
		return *m.PrevIndex
	}
	return 0
}

func (m *TxInputType) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *TxInputType) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return Default_TxInputType_Sequence
}

func (m *TxInputType) GetScriptType() InputScriptType {
	if m != nil && m.ScriptType != nil {
		return *m.ScriptType
	}
	return Default_TxInputType_ScriptType
}

func (m *TxInputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxInputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxInputType) GetDecredTree() uint32 {
	if m != nil && m.DecredTree != nil {
		return *m.DecredTree
	}
	return 0
}

func (m *TxInputType) GetDecredScriptVersion() uint32 {
	if m != nil && m.DecredScriptVersion != nil {
		return *m.DecredScriptVersion
	}
	return 0
}

// *
// Structure representing transaction output
// @used_in TransactionType
type TxOutputType struct {
	Address              *string                   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AddressN             []uint32                  `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Amount               *uint64                   `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	ScriptType           *OutputScriptType         `protobuf:"varint,4,req,name=script_type,json=scriptType,enum=OutputScriptType" json:"script_type,omitempty"`
	Multisig             *MultisigRedeemScriptType `protobuf:"bytes,5,opt,name=multisig" json:"multisig,omitempty"`
	OpReturnData         []byte                    `protobuf:"bytes,6,opt,name=op_return_data,json=opReturnData" json:"op_return_data,omitempty"`
	AddressType          *OutputAddressType        `protobuf:"varint,7,opt,name=address_type,json=addressType,enum=OutputAddressType" json:"address_type,omitempty"`
	ExchangeType         *ExchangeType             `protobuf:"bytes,8,opt,name=exchange_type,json=exchangeType" json:"exchange_type,omitempty"`
	DecredScriptVersion  *uint32                   `protobuf:"varint,9,opt,name=decred_script_version,json=decredScriptVersion" json:"decred_script_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TxOutputType) Reset()         { *m = TxOutputType{} }
func (m *TxOutputType) String() string { return proto.CompactTextString(m) }
func (*TxOutputType) ProtoMessage()    {}
func (*TxOutputType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{5}
}
func (m *TxOutputType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutputType.Unmarshal(m, b)
}
func (m *TxOutputType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutputType.Marshal(b, m, deterministic)
}
func (dst *TxOutputType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutputType.Merge(dst, src)
}
func (m *TxOutputType) XXX_Size() int {
	return xxx_messageInfo_TxOutputType.Size(m)
}
func (m *TxOutputType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutputType.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutputType proto.InternalMessageInfo

func (m *TxOutputType) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *TxOutputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxOutputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputType) GetScriptType() OutputScriptType {
	if m != nil && m.ScriptType != nil {
		return *m.ScriptType
	}
	return OutputScriptType_PAYTOADDRESS
}

func (m *TxOutputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxOutputType) GetOpReturnData() []byte {
	if m != nil {
		return m.OpReturnData
	}
	return nil
}

func (m *TxOutputType) GetAddressType() OutputAddressType {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return OutputAddressType_SPEND
}

func (m *TxOutputType) GetExchangeType() *ExchangeType {
	if m != nil {
		return m.ExchangeType
	}
	return nil
}

func (m *TxOutputType) GetDecredScriptVersion() uint32 {
	if m != nil && m.DecredScriptVersion != nil {
		return *m.DecredScriptVersion
	}
	return 0
}

// *
// Structure representing compiled transaction output
// @used_in TransactionType
type TxOutputBinType struct {
	Amount               *uint64  `protobuf:"varint,1,req,name=amount" json:"amount,omitempty"`
	ScriptPubkey         []byte   `protobuf:"bytes,2,req,name=script_pubkey,json=scriptPubkey" json:"script_pubkey,omitempty"`
	DecredScriptVersion  *uint32  `protobuf:"varint,3,opt,name=decred_script_version,json=decredScriptVersion" json:"decred_script_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutputBinType) Reset()         { *m = TxOutputBinType{} }
func (m *TxOutputBinType) String() string { return proto.CompactTextString(m) }
func (*TxOutputBinType) ProtoMessage()    {}
func (*TxOutputBinType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{6}
}
func (m *TxOutputBinType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutputBinType.Unmarshal(m, b)
}
func (m *TxOutputBinType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutputBinType.Marshal(b, m, deterministic)
}
func (dst *TxOutputBinType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutputBinType.Merge(dst, src)
}
func (m *TxOutputBinType) XXX_Size() int {
	return xxx_messageInfo_TxOutputBinType.Size(m)
}
func (m *TxOutputBinType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutputBinType.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutputBinType proto.InternalMessageInfo

func (m *TxOutputBinType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputBinType) GetScriptPubkey() []byte {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

func (m *TxOutputBinType) GetDecredScriptVersion() uint32 {
	if m != nil && m.DecredScriptVersion != nil {
		return *m.DecredScriptVersion
	}
	return 0
}

// *
// Structure representing transaction
type TransactionType struct {
	Version              *uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Inputs               []*TxInputType     `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	BinOutputs           []*TxOutputBinType `protobuf:"bytes,3,rep,name=bin_outputs,json=binOutputs" json:"bin_outputs,omitempty"`
	Outputs              []*TxOutputType    `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	LockTime             *uint32            `protobuf:"varint,4,opt,name=lock_time,json=lockTime" json:"lock_time,omitempty"`
	InputsCnt            *uint32            `protobuf:"varint,6,opt,name=inputs_cnt,json=inputsCnt" json:"inputs_cnt,omitempty"`
	OutputsCnt           *uint32            `protobuf:"varint,7,opt,name=outputs_cnt,json=outputsCnt" json:"outputs_cnt,omitempty"`
	ExtraData            []byte             `protobuf:"bytes,8,opt,name=extra_data,json=extraData" json:"extra_data,omitempty"`
	ExtraDataLen         *uint32            `protobuf:"varint,9,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	Expiry               *uint32            `protobuf:"varint,10,opt,name=expiry" json:"expiry,omitempty"`
	Overwintered         *bool              `protobuf:"varint,11,opt,name=overwintered" json:"overwintered,omitempty"`
	VersionGroupId       *uint32            `protobuf:"varint,12,opt,name=version_group_id,json=versionGroupId" json:"version_group_id,omitempty"`
	BranchId             *uint32            `protobuf:"varint,13,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransactionType) Reset()         { *m = TransactionType{} }
func (m *TransactionType) String() string { return proto.CompactTextString(m) }
func (*TransactionType) ProtoMessage()    {}
func (*TransactionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{7}
}
func (m *TransactionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionType.Unmarshal(m, b)
}
func (m *TransactionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionType.Marshal(b, m, deterministic)
}
func (dst *TransactionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionType.Merge(dst, src)
}
func (m *TransactionType) XXX_Size() int {
	return xxx_messageInfo_TransactionType.Size(m)
}
func (m *TransactionType) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionType.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionType proto.InternalMessageInfo

func (m *TransactionType) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *TransactionType) GetInputs() []*TxInputType {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionType) GetBinOutputs() []*TxOutputBinType {
	if m != nil {
		return m.BinOutputs
	}
	return nil
}

func (m *TransactionType) GetOutputs() []*TxOutputType {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *TransactionType) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return 0
}

func (m *TransactionType) GetInputsCnt() uint32 {
	if m != nil && m.InputsCnt != nil {
		return *m.InputsCnt
	}
	return 0
}

func (m *TransactionType) GetOutputsCnt() uint32 {
	if m != nil && m.OutputsCnt != nil {
		return *m.OutputsCnt
	}
	return 0
}

func (m *TransactionType) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *TransactionType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

func (m *TransactionType) GetExpiry() uint32 {
	if m != nil && m.Expiry != nil {
		return *m.Expiry
	}
	return 0
}

func (m *TransactionType) GetOverwintered() bool {
	if m != nil && m.Overwintered != nil {
		return *m.Overwintered
	}
	return false
}

func (m *TransactionType) GetVersionGroupId() uint32 {
	if m != nil && m.VersionGroupId != nil {
		return *m.VersionGroupId
	}
	return 0
}

func (m *TransactionType) GetBranchId() uint32 {
	if m != nil && m.BranchId != nil {
		return *m.BranchId
	}
	return 0
}

// *
// Structure representing raw transaction
// @used_in RawTxAck
type RawTransactionType struct {
	Payload              []byte   `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawTransactionType) Reset()         { *m = RawTransactionType{} }
func (m *RawTransactionType) String() string { return proto.CompactTextString(m) }
func (*RawTransactionType) ProtoMessage()    {}
func (*RawTransactionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{8}
}
func (m *RawTransactionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawTransactionType.Unmarshal(m, b)
}
func (m *RawTransactionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawTransactionType.Marshal(b, m, deterministic)
}
func (dst *RawTransactionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawTransactionType.Merge(dst, src)
}
func (m *RawTransactionType) XXX_Size() int {
	return xxx_messageInfo_RawTransactionType.Size(m)
}
func (m *RawTransactionType) XXX_DiscardUnknown() {
	xxx_messageInfo_RawTransactionType.DiscardUnknown(m)
}

var xxx_messageInfo_RawTransactionType proto.InternalMessageInfo

func (m *RawTransactionType) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// *
// Structure representing request details
// @used_in TxRequest
type TxRequestDetailsType struct {
	RequestIndex         *uint32  `protobuf:"varint,1,opt,name=request_index,json=requestIndex" json:"request_index,omitempty"`
	TxHash               []byte   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	ExtraDataLen         *uint32  `protobuf:"varint,3,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	ExtraDataOffset      *uint32  `protobuf:"varint,4,opt,name=extra_data_offset,json=extraDataOffset" json:"extra_data_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequestDetailsType) Reset()         { *m = TxRequestDetailsType{} }
func (m *TxRequestDetailsType) String() string { return proto.CompactTextString(m) }
func (*TxRequestDetailsType) ProtoMessage()    {}
func (*TxRequestDetailsType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{9}
}
func (m *TxRequestDetailsType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequestDetailsType.Unmarshal(m, b)
}
func (m *TxRequestDetailsType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequestDetailsType.Marshal(b, m, deterministic)
}
func (dst *TxRequestDetailsType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequestDetailsType.Merge(dst, src)
}
func (m *TxRequestDetailsType) XXX_Size() int {
	return xxx_messageInfo_TxRequestDetailsType.Size(m)
}
func (m *TxRequestDetailsType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequestDetailsType.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequestDetailsType proto.InternalMessageInfo

func (m *TxRequestDetailsType) GetRequestIndex() uint32 {
	if m != nil && m.RequestIndex != nil {
		return *m.RequestIndex
	}
	return 0
}

func (m *TxRequestDetailsType) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxRequestDetailsType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

func (m *TxRequestDetailsType) GetExtraDataOffset() uint32 {
	if m != nil && m.ExtraDataOffset != nil {
		return *m.ExtraDataOffset
	}
	return 0
}

// *
// Structure representing serialized data
// @used_in TxRequest
type TxRequestSerializedType struct {
	SignatureIndex       *uint32  `protobuf:"varint,1,opt,name=signature_index,json=signatureIndex" json:"signature_index,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	SerializedTx         []byte   `protobuf:"bytes,3,opt,name=serialized_tx,json=serializedTx" json:"serialized_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequestSerializedType) Reset()         { *m = TxRequestSerializedType{} }
func (m *TxRequestSerializedType) String() string { return proto.CompactTextString(m) }
func (*TxRequestSerializedType) ProtoMessage()    {}
func (*TxRequestSerializedType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{10}
}
func (m *TxRequestSerializedType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequestSerializedType.Unmarshal(m, b)
}
func (m *TxRequestSerializedType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequestSerializedType.Marshal(b, m, deterministic)
}
func (dst *TxRequestSerializedType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequestSerializedType.Merge(dst, src)
}
func (m *TxRequestSerializedType) XXX_Size() int {
	return xxx_messageInfo_TxRequestSerializedType.Size(m)
}
func (m *TxRequestSerializedType) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequestSerializedType.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequestSerializedType proto.InternalMessageInfo

func (m *TxRequestSerializedType) GetSignatureIndex() uint32 {
	if m != nil && m.SignatureIndex != nil {
		return *m.SignatureIndex
	}
	return 0
}

func (m *TxRequestSerializedType) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TxRequestSerializedType) GetSerializedTx() []byte {
	if m != nil {
		return m.SerializedTx
	}
	return nil
}

// *
// Structure representing identity data
// @used_in IdentityType
type IdentityType struct {
	Proto                *string  `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	User                 *string  `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Host                 *string  `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port                 *string  `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Path                 *string  `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	Index                *uint32  `protobuf:"varint,6,opt,name=index,def=0" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityType) Reset()         { *m = IdentityType{} }
func (m *IdentityType) String() string { return proto.CompactTextString(m) }
func (*IdentityType) ProtoMessage()    {}
func (*IdentityType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{11}
}
func (m *IdentityType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityType.Unmarshal(m, b)
}
func (m *IdentityType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityType.Marshal(b, m, deterministic)
}
func (dst *IdentityType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityType.Merge(dst, src)
}
func (m *IdentityType) XXX_Size() int {
	return xxx_messageInfo_IdentityType.Size(m)
}
func (m *IdentityType) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityType.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityType proto.InternalMessageInfo

const Default_IdentityType_Index uint32 = 0

func (m *IdentityType) GetProto() string {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return ""
}

func (m *IdentityType) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *IdentityType) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *IdentityType) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *IdentityType) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *IdentityType) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_IdentityType_Index
}

// *
// Structure representing policy data
// @used_in ApplyPolicy
type PolicyType struct {
	PolicyName           *string  `protobuf:"bytes,1,opt,name=policy_name,json=policyName" json:"policy_name,omitempty"`
	Enabled              *bool    `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolicyType) Reset()         { *m = PolicyType{} }
func (m *PolicyType) String() string { return proto.CompactTextString(m) }
func (*PolicyType) ProtoMessage()    {}
func (*PolicyType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{12}
}
func (m *PolicyType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyType.Unmarshal(m, b)
}
func (m *PolicyType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyType.Marshal(b, m, deterministic)
}
func (dst *PolicyType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyType.Merge(dst, src)
}
func (m *PolicyType) XXX_Size() int {
	return xxx_messageInfo_PolicyType.Size(m)
}
func (m *PolicyType) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyType.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyType proto.InternalMessageInfo

func (m *PolicyType) GetPolicyName() string {
	if m != nil && m.PolicyName != nil {
		return *m.PolicyName
	}
	return ""
}

func (m *PolicyType) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

// *
// Structure representing exchange data
// @used_in TxOutputType
type ExchangeType struct {
	SignedExchangeResponse *SignedExchangeResponse `protobuf:"bytes,1,opt,name=signed_exchange_response,json=signedExchangeResponse" json:"signed_exchange_response,omitempty"`
	WithdrawalCoinName     *string                 `protobuf:"bytes,2,opt,name=withdrawal_coin_name,json=withdrawalCoinName,def=Bitcoin" json:"withdrawal_coin_name,omitempty"`
	WithdrawalAddressN     []uint32                `protobuf:"varint,3,rep,name=withdrawal_address_n,json=withdrawalAddressN" json:"withdrawal_address_n,omitempty"`
	ReturnAddressN         []uint32                `protobuf:"varint,4,rep,name=return_address_n,json=returnAddressN" json:"return_address_n,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *ExchangeType) Reset()         { *m = ExchangeType{} }
func (m *ExchangeType) String() string { return proto.CompactTextString(m) }
func (*ExchangeType) ProtoMessage()    {}
func (*ExchangeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_84956a461f104c82, []int{13}
}
func (m *ExchangeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeType.Unmarshal(m, b)
}
func (m *ExchangeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeType.Marshal(b, m, deterministic)
}
func (dst *ExchangeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeType.Merge(dst, src)
}
func (m *ExchangeType) XXX_Size() int {
	return xxx_messageInfo_ExchangeType.Size(m)
}
func (m *ExchangeType) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeType.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeType proto.InternalMessageInfo

const Default_ExchangeType_WithdrawalCoinName string = "Bitcoin"

func (m *ExchangeType) GetSignedExchangeResponse() *SignedExchangeResponse {
	if m != nil {
		return m.SignedExchangeResponse
	}
	return nil
}

func (m *ExchangeType) GetWithdrawalCoinName() string {
	if m != nil && m.WithdrawalCoinName != nil {
		return *m.WithdrawalCoinName
	}
	return Default_ExchangeType_WithdrawalCoinName
}

func (m *ExchangeType) GetWithdrawalAddressN() []uint32 {
	if m != nil {
		return m.WithdrawalAddressN
	}
	return nil
}

func (m *ExchangeType) GetReturnAddressN() []uint32 {
	if m != nil {
		return m.ReturnAddressN
	}
	return nil
}

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "wire_in",
	Tag:           "varint,50002,opt,name=wire_in,json=wireIn",
	Filename:      "types.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "wire_out",
	Tag:           "varint,50003,opt,name=wire_out,json=wireOut",
	Filename:      "types.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in,json=wireDebugIn",
	Filename:      "types.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out,json=wireDebugOut",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*HDNodeType)(nil), "HDNodeType")
	proto.RegisterType((*HDNodePathType)(nil), "HDNodePathType")
	proto.RegisterType((*CoinType)(nil), "CoinType")
	proto.RegisterType((*MultisigRedeemScriptType)(nil), "MultisigRedeemScriptType")
	proto.RegisterType((*TxInputType)(nil), "TxInputType")
	proto.RegisterType((*TxOutputType)(nil), "TxOutputType")
	proto.RegisterType((*TxOutputBinType)(nil), "TxOutputBinType")
	proto.RegisterType((*TransactionType)(nil), "TransactionType")
	proto.RegisterType((*RawTransactionType)(nil), "RawTransactionType")
	proto.RegisterType((*TxRequestDetailsType)(nil), "TxRequestDetailsType")
	proto.RegisterType((*TxRequestSerializedType)(nil), "TxRequestSerializedType")
	proto.RegisterType((*IdentityType)(nil), "IdentityType")
	proto.RegisterType((*PolicyType)(nil), "PolicyType")
	proto.RegisterType((*ExchangeType)(nil), "ExchangeType")
	proto.RegisterEnum("FailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("OutputScriptType", OutputScriptType_name, OutputScriptType_value)
	proto.RegisterEnum("InputScriptType", InputScriptType_name, InputScriptType_value)
	proto.RegisterEnum("RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("OutputAddressType", OutputAddressType_name, OutputAddressType_value)
	proto.RegisterEnum("ButtonRequestType", ButtonRequestType_name, ButtonRequestType_value)
	proto.RegisterEnum("PinMatrixRequestType", PinMatrixRequestType_name, PinMatrixRequestType_value)
	proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_84956a461f104c82) }

var fileDescriptor_types_84956a461f104c82 = []byte{
	// 2565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x5e, 0x88, 0xfa, 0x21, 0x9b, 0x20, 0x35, 0x1e, 0xcb, 0x12, 0xfc, 0x4f, 0xd3, 0xae, 0xb5,
	0x56, 0x49, 0xb8, 0xbb, 0xb4, 0xbd, 0x8e, 0x55, 0xa9, 0xa4, 0x28, 0x89, 0xb2, 0x58, 0xb6, 0x28,
	0x06, 0xa4, 0x76, 0x95, 0x13, 0x0a, 0x04, 0x46, 0xe4, 0x94, 0x48, 0x00, 0x19, 0x0c, 0x24, 0x32,
	0x97, 0x54, 0xa5, 0x2a, 0xc9, 0x69, 0x2f, 0xa9, 0x3c, 0x43, 0x9e, 0x23, 0xcf, 0xb0, 0x49, 0x5e,
	0x21, 0xcf, 0x90, 0x5b, 0x52, 0xf3, 0x03, 0xfe, 0x88, 0xd2, 0xc6, 0x37, 0xce, 0xf7, 0x75, 0xf7,
	0x74, 0xf7, 0x74, 0xf7, 0x0c, 0x01, 0x79, 0x3e, 0x8e, 0x48, 0x5c, 0x89, 0x58, 0xc8, 0xc3, 0x07,
	0xa5, 0x5e, 0x18, 0xf6, 0x06, 0xe4, 0x4b, 0xb9, 0xea, 0x26, 0xe7, 0x5f, 0xfa, 0x24, 0xf6, 0x18,
	0x8d, 0x78, 0xc8, 0xb4, 0x44, 0x91, 0x8c, 0xbc, 0xbe, 0x1b, 0xf4, 0x88, 0x5a, 0x97, 0xff, 0x6e,
	0x00, 0x1c, 0x1d, 0x34, 0x43, 0x9f, 0x74, 0xc6, 0x11, 0xc1, 0x1b, 0xb0, 0xe2, 0x93, 0x88, 0xf7,
	0x2d, 0xa3, 0xb4, 0xb4, 0x5d, 0xb0, 0xd5, 0x02, 0x97, 0x20, 0x7f, 0x4e, 0x83, 0x1e, 0x61, 0x11,
	0xa3, 0x01, 0xb7, 0x96, 0x24, 0x37, 0x0b, 0xe1, 0x87, 0x90, 0xf3, 0xfa, 0x74, 0xe0, 0x3b, 0x41,
	0x32, 0xb4, 0x32, 0x92, 0xcf, 0x4a, 0xa0, 0x99, 0x0c, 0xf1, 0x63, 0x00, 0xaf, 0xef, 0xd2, 0xc0,
	0xf1, 0x42, 0x9f, 0x58, 0xcb, 0xa5, 0xa5, 0x6d, 0xd3, 0xce, 0x49, 0x64, 0x3f, 0xf4, 0x09, 0x7e,
	0x0a, 0xf9, 0x88, 0xd1, 0x4b, 0x97, 0x13, 0xe7, 0x82, 0x8c, 0xad, 0x95, 0x92, 0xb1, 0x6d, 0xda,
	0xa0, 0xa1, 0x0f, 0x64, 0x2c, 0xf4, 0xa3, 0xa4, 0x3b, 0xa0, 0x9e, 0xe4, 0x57, 0x25, 0x9f, 0x53,
	0xc8, 0x07, 0x32, 0x2e, 0x37, 0xa1, 0xa8, 0x22, 0x68, 0xb9, 0xbc, 0x2f, 0xa3, 0x78, 0x0a, 0xcb,
	0x81, 0xd8, 0x4a, 0x04, 0x91, 0xaf, 0xe6, 0x2b, 0xd3, 0x00, 0x6d, 0x49, 0x08, 0x77, 0x5d, 0xdf,
	0x67, 0x24, 0x8e, 0x9d, 0xc0, 0x5a, 0x2a, 0x65, 0x84, 0xbb, 0x1a, 0x68, 0x96, 0xff, 0xbb, 0x02,
	0xd9, 0xfd, 0x90, 0x06, 0xd2, 0x94, 0x08, 0x2c, 0xa4, 0x81, 0x13, 0xb8, 0x43, 0x61, 0xcf, 0xd8,
	0xce, 0xd9, 0x59, 0x01, 0x34, 0xdd, 0x21, 0xc1, 0xcf, 0xa1, 0x20, 0xc9, 0xb8, 0x1f, 0x32, 0xee,
	0x25, 0x22, 0x33, 0x42, 0xc0, 0x14, 0x60, 0x5b, 0x63, 0xf8, 0x05, 0x98, 0xe9, 0x5e, 0xe2, 0xa8,
	0xac, 0x4c, 0xc9, 0xd8, 0x2e, 0xec, 0x1a, 0x5f, 0xd9, 0x79, 0x0d, 0xa7, 0xfb, 0x0c, 0xdd, 0xd1,
	0x39, 0x21, 0xce, 0x45, 0xd7, 0x5a, 0x2e, 0x19, 0xdb, 0xcb, 0x76, 0x56, 0x01, 0x1f, 0xba, 0xf8,
	0x67, 0x70, 0x67, 0xd6, 0x84, 0x13, 0x55, 0xe3, 0xbe, 0xcc, 0x53, 0x61, 0xd7, 0x78, 0x63, 0xaf,
	0xcf, 0xd8, 0x69, 0x55, 0xe3, 0x3e, 0xae, 0xc2, 0xbd, 0x98, 0xf6, 0x02, 0xe2, 0x3b, 0x43, 0x12,
	0xc7, 0x6e, 0x8f, 0x38, 0x7d, 0xe2, 0xfa, 0x84, 0x59, 0x59, 0xe9, 0xde, 0x5d, 0x45, 0x1e, 0x2b,
	0xee, 0x48, 0x52, 0xf8, 0xa7, 0x80, 0xbb, 0x34, 0x7a, 0xfd, 0xda, 0x71, 0x3d, 0x2f, 0x4c, 0x02,
	0xee, 0x44, 0x2e, 0xef, 0x5b, 0x39, 0xb1, 0x87, 0x8d, 0x24, 0x53, 0x53, 0x84, 0x48, 0x32, 0xde,
	0x84, 0xd5, 0xf3, 0x90, 0x5d, 0x50, 0xdf, 0x32, 0xa5, 0x84, 0x5e, 0xe1, 0x07, 0x90, 0xf5, 0x89,
	0x47, 0x87, 0xee, 0x20, 0xb6, 0x0a, 0x92, 0x99, 0xac, 0xf1, 0x17, 0x80, 0xbc, 0x30, 0xe0, 0xcc,
	0xf5, 0xb8, 0xa3, 0x3d, 0xb6, 0x8a, 0xf2, 0x2c, 0xd7, 0x53, 0xbc, 0xa6, 0x60, 0xfc, 0x12, 0x60,
	0x14, 0x25, 0x5d, 0x67, 0xe8, 0xf6, 0xa8, 0x67, 0x21, 0x19, 0x68, 0xf6, 0xed, 0x37, 0x5f, 0x7d,
	0xf3, 0xf6, 0xd5, 0x9b, 0x9f, 0xdb, 0x39, 0xc1, 0x1d, 0x0b, 0x4a, 0xf8, 0x11, 0x93, 0xde, 0x15,
	0xe5, 0x16, 0x2e, 0x19, 0xdb, 0x59, 0x5b, 0xaf, 0xf0, 0x33, 0x30, 0xcf, 0x43, 0xe6, 0x11, 0xa7,
	0x4b, 0xa3, 0xaf, 0x5f, 0xbf, 0xb2, 0xee, 0x4a, 0x36, 0x2f, 0xb1, 0x3d, 0x09, 0xc9, 0xa2, 0x4c,
	0xd8, 0x25, 0x51, 0x27, 0xbb, 0x21, 0x33, 0x93, 0x93, 0x88, 0x3c, 0xda, 0x97, 0xb0, 0xee, 0xb9,
	0x71, 0x5f, 0x38, 0xea, 0x44, 0x8c, 0x9c, 0xd3, 0x91, 0x75, 0x4f, 0xca, 0x14, 0x53, 0xb8, 0x25,
	0x51, 0x51, 0x03, 0x5d, 0xe2, 0xf5, 0x5f, 0x55, 0x53, 0xb1, 0x4d, 0x55, 0x03, 0x0a, 0xd4, 0x42,
	0x9b, 0xb0, 0xea, 0x13, 0x8f, 0x11, 0xdf, 0xda, 0x52, 0x7e, 0xaa, 0x15, 0x7e, 0x05, 0x9b, 0xd3,
	0x40, 0x1d, 0xe5, 0xbc, 0x3a, 0xdd, 0xfb, 0x32, 0x7b, 0x77, 0x27, 0xa1, 0xb6, 0x25, 0x27, 0x8f,
	0xf7, 0x2d, 0x58, 0x8b, 0x4a, 0x81, 0xcb, 0xe9, 0x25, 0xb1, 0x1e, 0x48, 0xb5, 0x7b, 0xd7, 0xd4,
	0x9a, 0x92, 0x14, 0x31, 0x05, 0x6e, 0x10, 0xce, 0xc6, 0xf4, 0x50, 0xc5, 0x94, 0xc2, 0xca, 0xdd,
	0x72, 0x0c, 0xd6, 0x71, 0x32, 0xe0, 0x34, 0xa6, 0x3d, 0x9b, 0xf8, 0x84, 0x0c, 0xdb, 0x72, 0x88,
	0xc8, 0x42, 0xfd, 0x02, 0xd6, 0xa2, 0xa4, 0x7b, 0x41, 0xc6, 0xb1, 0x65, 0x94, 0x32, 0xdb, 0xf9,
	0xea, 0x7a, 0x65, 0xbe, 0xfb, 0xec, 0x94, 0xc7, 0x4f, 0x00, 0x44, 0xa9, 0xb9, 0x3c, 0x61, 0x24,
	0x96, 0x6d, 0x66, 0xda, 0x33, 0x08, 0x36, 0xc1, 0x18, 0xaa, 0x76, 0xb0, 0x8d, 0x61, 0xf9, 0x2f,
	0x19, 0xc8, 0x77, 0x46, 0x8d, 0x20, 0x4a, 0x78, 0xda, 0x11, 0xd3, 0x1e, 0x35, 0xe6, 0x7b, 0x54,
	0x90, 0x11, 0x23, 0x97, 0x4e, 0xdf, 0x8d, 0xfb, 0x72, 0x1e, 0x99, 0x76, 0x56, 0x00, 0x47, 0x6e,
	0xdc, 0x97, 0xf3, 0x42, 0x90, 0x34, 0xf0, 0xc9, 0x48, 0x4f, 0x23, 0x29, 0xde, 0x10, 0x80, 0xa0,
	0xd5, 0x50, 0x74, 0x62, 0xda, 0x93, 0xbd, 0x66, 0xda, 0x39, 0x85, 0xb4, 0x69, 0x0f, 0x7f, 0x0e,
	0xd9, 0x98, 0xfc, 0x36, 0x21, 0x81, 0x47, 0x74, 0x8f, 0xc1, 0xeb, 0xea, 0xbb, 0xd7, 0xef, 0xbe,
	0x79, 0x5b, 0x7d, 0xf7, 0xc6, 0x9e, 0x70, 0xf8, 0x57, 0x90, 0xd7, 0x66, 0x64, 0x5b, 0x8b, 0xb1,
	0x54, 0xac, 0xa2, 0x8a, 0x0c, 0x60, 0x9a, 0xaf, 0x5d, 0xb3, 0xdd, 0xaa, 0x37, 0x0f, 0x6a, 0x07,
	0x07, 0x76, 0xbd, 0xdd, 0xb6, 0xf5, 0xce, 0x32, 0xc0, 0x37, 0x90, 0x1d, 0xea, 0x2c, 0x5b, 0x6b,
	0x25, 0x63, 0x3b, 0x5f, 0xbd, 0x5f, 0xb9, 0x2d, 0xed, 0xf6, 0x44, 0x54, 0xd4, 0x92, 0x3b, 0x14,
	0x9d, 0x28, 0xdb, 0x79, 0xd9, 0xd6, 0x2b, 0x31, 0x46, 0x55, 0x55, 0x39, 0x9c, 0x11, 0xa2, 0x5b,
	0x17, 0x14, 0xd4, 0x61, 0x84, 0x88, 0xb1, 0xa0, 0x05, 0xb4, 0xdf, 0x97, 0x84, 0xc5, 0x34, 0x0c,
	0x2c, 0x50, 0xb5, 0xa6, 0x48, 0xb5, 0xe7, 0xb7, 0x8a, 0x2a, 0x7f, 0x9f, 0x01, 0xb3, 0x33, 0x3a,
	0x49, 0x78, 0x7a, 0x2a, 0x16, 0xac, 0xa5, 0xcd, 0xab, 0xa6, 0x61, 0xba, 0xfc, 0xd1, 0x99, 0x3a,
	0xe3, 0xb4, 0x38, 0x8e, 0xa9, 0xd3, 0xd5, 0xf9, 0x24, 0x8a, 0xbb, 0xa1, 0x58, 0xbd, 0x53, 0x51,
	0x1b, 0xce, 0x84, 0x7f, 0x5b, 0xde, 0x56, 0x3e, 0x3d, 0x6f, 0x2f, 0xa0, 0x18, 0x46, 0x0e, 0x23,
	0x3c, 0x61, 0x81, 0xe3, 0xbb, 0xdc, 0xd5, 0x37, 0x89, 0x19, 0x46, 0xb6, 0x04, 0x0f, 0x5c, 0xee,
	0xe2, 0x37, 0xd7, 0xa6, 0xf5, 0x9a, 0x3c, 0x56, 0xac, 0x3d, 0xaa, 0x4d, 0x27, 0xed, 0xfc, 0xf8,
	0xae, 0x42, 0x21, 0xbd, 0x58, 0x95, 0x5e, 0x56, 0x3a, 0x56, 0xa8, 0xd4, 0x35, 0x2a, 0x55, 0x4c,
	0x32, 0xb3, 0xba, 0xfd, 0x3c, 0x72, 0xb7, 0x9f, 0xc7, 0x1f, 0x0c, 0x58, 0x4f, 0xcf, 0x63, 0x4f,
	0x5f, 0x51, 0xd3, 0xdc, 0x1a, 0x73, 0xb9, 0x7d, 0x0e, 0x05, 0x6d, 0x58, 0x35, 0xa4, 0xee, 0x13,
	0x53, 0x81, 0x2d, 0x89, 0xdd, 0xee, 0x44, 0xe6, 0x76, 0x27, 0x7e, 0xc8, 0xc0, 0x7a, 0x87, 0xb9,
	0x41, 0xec, 0x7a, 0x9c, 0x86, 0x41, 0x5a, 0x17, 0xa9, 0xa6, 0x21, 0x35, 0xd3, 0x25, 0x7e, 0x01,
	0xab, 0x54, 0xf4, 0x84, 0x9a, 0x00, 0xf9, 0xaa, 0x59, 0x99, 0xe9, 0x72, 0x5b, 0x73, 0xf8, 0x6b,
	0xc8, 0x77, 0x69, 0xe0, 0x84, 0x32, 0xb2, 0xd8, 0xca, 0x48, 0x51, 0x54, 0xb9, 0x16, 0xab, 0x0d,
	0x5d, 0x1a, 0x28, 0x44, 0xdc, 0x12, 0x6b, 0xa9, 0xf8, 0x8a, 0x14, 0x2f, 0x54, 0x66, 0x4b, 0xd5,
	0x4e, 0x59, 0x51, 0x99, 0x83, 0xd0, 0xbb, 0x70, 0x38, 0x1d, 0x12, 0xd9, 0xef, 0x05, 0x3b, 0x2b,
	0x80, 0x0e, 0x1d, 0x12, 0x31, 0x0d, 0x94, 0x0b, 0x8e, 0x17, 0x70, 0x59, 0x12, 0x05, 0x3b, 0xa7,
	0x90, 0x7d, 0xd5, 0x55, 0xda, 0x8c, 0xe4, 0xd7, 0x54, 0x57, 0x69, 0x48, 0x08, 0x3c, 0x06, 0x20,
	0x23, 0xce, 0x5c, 0x55, 0x52, 0x59, 0x35, 0x4d, 0x24, 0x22, 0xeb, 0xe9, 0x05, 0x14, 0xa7, 0xb4,
	0x33, 0x20, 0xe9, 0xe9, 0x9a, 0x13, 0x91, 0x8f, 0x24, 0x10, 0x47, 0x48, 0x46, 0x11, 0x65, 0x63,
	0xdd, 0x8b, 0x7a, 0x85, 0xcb, 0x60, 0x86, 0x97, 0x84, 0x5d, 0xd1, 0x80, 0x13, 0x71, 0x7b, 0xe4,
	0xe5, 0xed, 0x31, 0x87, 0xe1, 0x6d, 0x40, 0x3a, 0xd5, 0x4e, 0x8f, 0x85, 0x49, 0xe4, 0x4c, 0x6e,
	0xe5, 0xa2, 0xc6, 0xdf, 0x0b, 0xb8, 0xe1, 0x8b, 0x3c, 0x74, 0x99, 0x1b, 0x78, 0x7d, 0x21, 0xa2,
	0xaf, 0x67, 0x05, 0x34, 0xfc, 0x72, 0x05, 0xb0, 0xed, 0x5e, 0xdd, 0x70, 0xac, 0x91, 0x3b, 0x1e,
	0x84, 0xae, 0x2f, 0x8b, 0xcb, 0xb4, 0xd3, 0x65, 0xf9, 0x6f, 0x06, 0x6c, 0x74, 0x46, 0xb6, 0x98,
	0x86, 0x31, 0x3f, 0x20, 0xdc, 0xa5, 0x03, 0xd5, 0x0a, 0xcf, 0xa1, 0xc0, 0x14, 0xaa, 0x07, 0xb0,
	0xaa, 0x07, 0x53, 0x83, 0x6a, 0x06, 0x6f, 0xc1, 0x1a, 0x1f, 0xa5, 0xd3, 0x5b, 0xa4, 0x6c, 0x95,
	0x8f, 0xe4, 0xec, 0x5e, 0xcc, 0x57, 0xe6, 0x86, 0x7c, 0xed, 0xc0, 0x9d, 0x19, 0xa9, 0xf0, 0xfc,
	0x3c, 0x26, 0x5c, 0x9f, 0xec, 0xfa, 0x44, 0xf0, 0x44, 0xc2, 0xe5, 0x3f, 0x1a, 0xb0, 0x35, 0x71,
	0xb4, 0x4d, 0x18, 0x75, 0x07, 0xf4, 0x77, 0xc4, 0x97, 0xbe, 0xbe, 0x84, 0xf5, 0xc9, 0x7d, 0x34,
	0xe7, 0x6d, 0x71, 0x02, 0x2b, 0x7f, 0x1f, 0x41, 0x6e, 0x82, 0x68, 0x8f, 0xa7, 0x80, 0xec, 0xb4,
	0x89, 0x61, 0x87, 0x8f, 0xa4, 0xcf, 0xa2, 0xd3, 0xa6, 0xbb, 0x8d, 0xca, 0xdf, 0x1b, 0x60, 0x36,
	0x7c, 0x12, 0x70, 0xca, 0xc7, 0xe9, 0x5b, 0x5b, 0xbe, 0xc1, 0xf5, 0x20, 0x55, 0x0b, 0x8c, 0x61,
	0x39, 0x89, 0x09, 0xd3, 0x4f, 0x49, 0xf9, 0x5b, 0x60, 0xfd, 0x30, 0xe6, 0xd2, 0x6c, 0xce, 0x96,
	0xbf, 0x05, 0x16, 0x85, 0x4c, 0x45, 0x9d, 0xb3, 0xe5, 0x6f, 0x89, 0x89, 0x67, 0xdb, 0x8a, 0xc6,
	0xc4, 0x53, 0x6d, 0x0b, 0x56, 0x54, 0x60, 0xab, 0xe9, 0xbb, 0x53, 0xad, 0xcb, 0xef, 0x01, 0x5a,
	0xe1, 0x80, 0x7a, 0x63, 0xfd, 0x64, 0xce, 0x47, 0x72, 0x35, 0xfb, 0xd2, 0x05, 0x05, 0xc9, 0x07,
	0x91, 0x05, 0x6b, 0x24, 0x70, 0xbb, 0x03, 0xe2, 0x4b, 0xd7, 0xb2, 0x76, 0xba, 0x2c, 0xff, 0xc7,
	0x00, 0x73, 0x76, 0xcc, 0xe1, 0x5f, 0x83, 0xa5, 0xdf, 0x9f, 0x93, 0x99, 0xc8, 0x48, 0x1c, 0x85,
	0x41, 0xac, 0x0c, 0xe7, 0xab, 0x5b, 0x95, 0xb6, 0x14, 0x48, 0xd5, 0x6c, 0x4d, 0xdb, 0x9b, 0xf1,
	0x8d, 0x38, 0x7e, 0x07, 0x1b, 0x57, 0x94, 0xf7, 0x7d, 0xe6, 0x5e, 0xb9, 0x03, 0x67, 0xfa, 0x22,
	0x97, 0x59, 0xda, 0x5d, 0xdb, 0xa3, 0x5c, 0x60, 0x36, 0x9e, 0x0a, 0xed, 0xa7, 0x8f, 0xf4, 0xaf,
	0xe6, 0x54, 0xa7, 0x57, 0x54, 0x46, 0x5e, 0x51, 0x33, 0x1a, 0xb5, 0xf4, 0xb2, 0xda, 0x06, 0xa4,
	0xaf, 0x89, 0xa9, 0xf4, 0xb2, 0x94, 0x2e, 0x2a, 0x3c, 0x95, 0xdc, 0xf9, 0xf7, 0x12, 0xe4, 0x0f,
	0x5d, 0x3a, 0x48, 0x98, 0x8a, 0xfc, 0x31, 0xdc, 0xd7, 0x4b, 0xe7, 0x34, 0x20, 0xa3, 0x88, 0x78,
	0x7c, 0xf2, 0xd0, 0x46, 0x06, 0x7e, 0x00, 0x9b, 0x29, 0xbd, 0x97, 0x70, 0x1e, 0x06, 0x75, 0x2d,
	0x82, 0x96, 0xf0, 0x16, 0xdc, 0x4d, 0xb9, 0xf6, 0x38, 0xe0, 0xee, 0xa8, 0xce, 0x58, 0xc8, 0x50,
	0x06, 0x3f, 0x84, 0xad, 0x94, 0xa8, 0xc9, 0xc6, 0xdc, 0x77, 0x03, 0x8f, 0x0c, 0x06, 0xc4, 0x47,
	0xcb, 0xb3, 0x5a, 0x2d, 0x3a, 0x35, 0xb7, 0x82, 0x2d, 0xd8, 0x98, 0x21, 0xa6, 0x2a, 0xab, 0x78,
	0x13, 0xf0, 0x0c, 0xd3, 0x08, 0x2e, 0xdd, 0x01, 0xf5, 0xd1, 0x1a, 0x7e, 0x04, 0x56, 0x8a, 0x6b,
	0xb0, 0x9d, 0x16, 0x38, 0xca, 0xe2, 0x3b, 0x50, 0x48, 0xd9, 0x13, 0xde, 0x27, 0x0c, 0xe5, 0x66,
	0xa3, 0x69, 0x86, 0xbc, 0x1e, 0x84, 0x49, 0xaf, 0x7f, 0x98, 0x04, 0x7e, 0x8c, 0xe0, 0x1a, 0xd7,
	0x08, 0x28, 0xd7, 0x8d, 0x80, 0xf2, 0xd7, 0x7c, 0x3e, 0xa6, 0xf1, 0xd0, 0xe5, 0x5e, 0x1f, 0x99,
	0xf8, 0x3e, 0xdc, 0x4b, 0x89, 0x43, 0xca, 0x86, 0x57, 0x2e, 0x23, 0x2a, 0x09, 0xde, 0xce, 0x9f,
	0x0d, 0x40, 0xd7, 0x1f, 0x05, 0x18, 0x81, 0xd9, 0xaa, 0xfd, 0xa6, 0x73, 0xa2, 0x1f, 0x57, 0xe8,
	0x33, 0x7c, 0x17, 0xd6, 0x25, 0xd2, 0xde, 0xb7, 0x1b, 0xad, 0xce, 0x51, 0xad, 0x7d, 0x84, 0x0c,
	0xe1, 0xba, 0x04, 0x8f, 0x4f, 0x3f, 0x76, 0x1a, 0xed, 0xc6, 0x7b, 0xb4, 0x34, 0x81, 0x4e, 0x5a,
	0x76, 0xbd, 0x73, 0x6a, 0x37, 0x51, 0x66, 0x62, 0xec, 0xbb, 0x46, 0xa7, 0x29, 0x8c, 0x2d, 0xe3,
	0x0d, 0x40, 0x12, 0x69, 0x55, 0xdb, 0x47, 0x29, 0xba, 0xb2, 0x33, 0x80, 0xf5, 0x6b, 0x4f, 0x3c,
	0xa1, 0x3a, 0xfb, 0xc8, 0x43, 0x9f, 0x09, 0xfb, 0x12, 0x99, 0x6c, 0x69, 0x60, 0x13, 0xb2, 0xf5,
	0xb3, 0x4e, 0xdd, 0x6e, 0xd6, 0x3e, 0xa2, 0xa5, 0x89, 0x4a, 0x6a, 0x37, 0x23, 0x76, 0x93, 0xc8,
	0xec, 0x6e, 0xcb, 0x3b, 0xa7, 0x90, 0xd7, 0x93, 0x4b, 0xee, 0x94, 0x87, 0xb5, 0xce, 0x59, 0xa3,
	0xd9, 0x3a, 0xed, 0xa0, 0xcf, 0x84, 0xc5, 0xce, 0xd9, 0xc9, 0x69, 0x47, 0xac, 0x0c, 0x0c, 0xb0,
	0xda, 0x39, 0x3b, 0xae, 0x77, 0x6a, 0x68, 0x09, 0x17, 0x01, 0x3a, 0x67, 0x87, 0x8d, 0x66, 0xa3,
	0x7d, 0x54, 0x3f, 0x40, 0x19, 0xbc, 0x0e, 0xf9, 0xce, 0x59, 0xfd, 0xac, 0x63, 0xd7, 0x0e, 0x6a,
	0x9d, 0x1a, 0x5a, 0xde, 0x39, 0x84, 0x3b, 0x0b, 0x0f, 0x1a, 0x9c, 0x83, 0x15, 0xe9, 0x81, 0x36,
	0x6d, 0xd7, 0x9a, 0xed, 0xc3, 0xba, 0xad, 0x4c, 0xef, 0x1f, 0xd5, 0x9a, 0xef, 0xeb, 0x68, 0x49,
	0x85, 0xa1, 0x57, 0x99, 0x9d, 0xbf, 0xe6, 0xe0, 0x8e, 0xaa, 0xe4, 0x59, 0x2f, 0xb7, 0xe0, 0xee,
	0x1c, 0xa8, 0x2b, 0xc6, 0xc0, 0x65, 0x78, 0x32, 0x4f, 0x1c, 0x12, 0x72, 0x72, 0x49, 0x58, 0xa7,
	0xcf, 0x48, 0xdc, 0x0f, 0x07, 0xa2, 0x0f, 0x9e, 0xc2, 0xc3, 0x79, 0x99, 0xfd, 0x30, 0x38, 0xa7,
	0x6c, 0xa8, 0xfc, 0x45, 0x19, 0xd1, 0x63, 0xf3, 0x02, 0x36, 0x89, 0x09, 0x3f, 0x20, 0x97, 0xd4,
	0x23, 0x68, 0x79, 0x91, 0xd6, 0xfa, 0xdf, 0x85, 0x4c, 0xf4, 0xc5, 0x23, 0xb0, 0xe6, 0xe9, 0xef,
	0x68, 0x44, 0xb4, 0xf2, 0xea, 0xa2, 0x72, 0x8b, 0x85, 0x9c, 0x78, 0x7c, 0xdf, 0x1d, 0x0c, 0xd0,
	0x9a, 0x68, 0xaa, 0x79, 0x5a, 0x74, 0x48, 0x67, 0x84, 0xb2, 0x8b, 0x5e, 0xa7, 0x05, 0xbc, 0xdf,
	0x27, 0xde, 0x05, 0xca, 0x89, 0xda, 0x9e, 0x17, 0xd0, 0x99, 0x47, 0x70, 0xbb, 0x6e, 0x9d, 0xb9,
	0x31, 0x41, 0x79, 0xbc, 0x03, 0x9f, 0xdf, 0x18, 0x92, 0xbc, 0xac, 0xcf, 0x09, 0xeb, 0x84, 0xfa,
	0xbf, 0x39, 0x32, 0xf1, 0x4f, 0xe0, 0xe5, 0xff, 0x91, 0x4d, 0xff, 0xab, 0xa1, 0xc2, 0x0d, 0xb9,
	0x92, 0x53, 0xf7, 0xa3, 0xdb, 0x25, 0x03, 0x54, 0xc4, 0x25, 0x78, 0x74, 0x33, 0x1d, 0xf4, 0x12,
	0x31, 0xd0, 0xd6, 0x17, 0x0f, 0xb4, 0x2e, 0xef, 0x84, 0x96, 0x1b, 0xc7, 0x51, 0x5f, 0x7a, 0x8f,
	0xf0, 0x73, 0x78, 0x3a, 0x2f, 0x73, 0x40, 0xe3, 0x6b, 0x42, 0x77, 0xf0, 0x4b, 0x78, 0x7e, 0xdd,
	0x90, 0xc7, 0xc6, 0x11, 0xaf, 0x05, 0x72, 0x0a, 0xa5, 0x23, 0x14, 0x2f, 0xfa, 0xa4, 0x05, 0x53,
	0x89, 0xbb, 0x8b, 0x3e, 0x35, 0x86, 0xe2, 0x72, 0x6c, 0x4d, 0xbe, 0x27, 0xa1, 0x0d, 0xbc, 0x0d,
	0x2f, 0x6e, 0x92, 0xb1, 0x89, 0x27, 0x9e, 0x56, 0xe3, 0x36, 0x09, 0xb8, 0xf8, 0x8f, 0x87, 0xee,
	0xe1, 0x27, 0xf0, 0x60, 0xf1, 0xc8, 0xd3, 0x6b, 0x1c, 0x6d, 0x8a, 0x69, 0x7a, 0xad, 0x62, 0x68,
	0xd0, 0x43, 0x5b, 0x62, 0x6a, 0x5f, 0xaf, 0xd2, 0x61, 0x78, 0x49, 0x5a, 0x34, 0x40, 0xd6, 0x22,
	0xa9, 0x12, 0x2b, 0xc8, 0xfb, 0x37, 0x90, 0x8c, 0xb8, 0x5c, 0x92, 0x0f, 0x16, 0xcb, 0xf7, 0x3d,
	0xe1, 0xf5, 0x80, 0xb3, 0x30, 0x1a, 0xa3, 0x87, 0x8b, 0xe7, 0x39, 0x9b, 0xbb, 0x47, 0x8b, 0x85,
	0x56, 0x8b, 0xa2, 0xc1, 0x58, 0x3e, 0x02, 0x28, 0x89, 0xd1, 0xe3, 0x9b, 0x83, 0x4d, 0xef, 0x62,
	0xf4, 0x04, 0x3f, 0x83, 0xc7, 0xd7, 0x0c, 0x24, 0x3c, 0xfc, 0x18, 0x7a, 0x17, 0x07, 0x64, 0xe0,
	0x8e, 0x8f, 0x63, 0xf4, 0x74, 0xd1, 0xc1, 0xd3, 0xea, 0xe1, 0xbe, 0xa8, 0x4d, 0xc2, 0x50, 0x69,
	0xf1, 0x6c, 0x74, 0x75, 0xd6, 0xc3, 0x58, 0xdd, 0x6d, 0xe8, 0xd9, 0x8f, 0xc9, 0xec, 0x25, 0x7e,
	0x8f, 0x70, 0x54, 0xbe, 0xb5, 0xc9, 0x8f, 0xc9, 0x30, 0x44, 0xcf, 0x77, 0x7e, 0x0f, 0x1b, 0xe2,
	0x66, 0x71, 0x39, 0xa3, 0xa3, 0xd9, 0xc1, 0x54, 0x82, 0x47, 0x37, 0xe1, 0xce, 0x7e, 0xc2, 0x18,
	0x09, 0x38, 0x32, 0x44, 0x84, 0x37, 0x4a, 0x34, 0xc9, 0xd5, 0x21, 0x65, 0x31, 0x47, 0x4b, 0xc2,
	0xbf, 0xdb, 0x44, 0xda, 0xc4, 0x0b, 0x03, 0x1f, 0x65, 0x76, 0x7f, 0x01, 0x6b, 0x57, 0x54, 0x3e,
	0x29, 0xf1, 0xb3, 0x8a, 0xfa, 0x26, 0x5b, 0x49, 0xbf, 0xc9, 0x56, 0xea, 0x41, 0x32, 0xfc, 0xd6,
	0x1d, 0x24, 0xe4, 0x24, 0x12, 0x21, 0xc7, 0xd6, 0x0f, 0x7f, 0xca, 0xa8, 0xaf, 0x42, 0x42, 0xa7,
	0x11, 0xec, 0xfe, 0x12, 0xb2, 0x52, 0x3b, 0x4c, 0xf8, 0xa7, 0xa8, 0xff, 0x43, 0xab, 0xcb, 0x2d,
	0x4f, 0x12, 0xbe, 0xfb, 0x1e, 0x0a, 0x52, 0xdf, 0x27, 0xdd, 0xa4, 0xf7, 0x89, 0x3e, 0xfc, 0x53,
	0x1b, 0xc9, 0x0b, 0xcd, 0x03, 0xa1, 0xd8, 0x08, 0x76, 0x1b, 0x50, 0x9c, 0x31, 0xf4, 0x89, 0xee,
	0xfc, 0x4b, 0x5b, 0x32, 0x27, 0x96, 0x4e, 0x12, 0xbe, 0xf7, 0x05, 0x3c, 0xf0, 0xc2, 0x61, 0xe5,
	0x82, 0x90, 0xe8, 0x82, 0x8c, 0x2b, 0xbe, 0x9c, 0xb8, 0xd2, 0x88, 0x17, 0x0e, 0xf6, 0xf2, 0x1f,
	0x08, 0x89, 0x3e, 0x10, 0xf9, 0x14, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x4e, 0xd2,
	0x53, 0xd2, 0x16, 0x00, 0x00,
}
