# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/daemon/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/daemon/messages.proto',
  package='solipsis.gkk.daemon',
  syntax='proto3',
  serialized_pb=_b('\n\x19rpc/daemon/messages.proto\x12\x13solipsis.gkk.daemon\"K\n\nPingParams\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0f\n\x07\x64isplay\x18\x02 \x01(\x08\x12\x0b\n\x03pin\x18\x03 \x01(\x08\x12\x12\n\npassphrase\x18\x04 \x01(\x08\" \n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t2T\n\x06\x44\x61\x65mon\x12J\n\x04Ping\x12\x1f.solipsis.gkk.daemon.PingParams\x1a!.solipsis.gkk.daemon.PingResponseB\x08Z\x06\x64\x61\x65monb\x06proto3')
)




_PINGPARAMS = _descriptor.Descriptor(
  name='PingParams',
  full_name='solipsis.gkk.daemon.PingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='solipsis.gkk.daemon.PingParams.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display', full_name='solipsis.gkk.daemon.PingParams.display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='solipsis.gkk.daemon.PingParams.pin', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passphrase', full_name='solipsis.gkk.daemon.PingParams.passphrase', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=125,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='solipsis.gkk.daemon.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='solipsis.gkk.daemon.PingResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['PingParams'] = _PINGPARAMS
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingParams = _reflection.GeneratedProtocolMessageType('PingParams', (_message.Message,), dict(
  DESCRIPTOR = _PINGPARAMS,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PingParams)
  ))
_sym_db.RegisterMessage(PingParams)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'rpc.daemon.messages_pb2'
  # @@protoc_insertion_point(class_scope:solipsis.gkk.daemon.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\006daemon'))

_DAEMON = _descriptor.ServiceDescriptor(
  name='Daemon',
  full_name='solipsis.gkk.daemon.Daemon',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=161,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='solipsis.gkk.daemon.Daemon.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGPARAMS,
    output_type=_PINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAEMON)

DESCRIPTOR.services_by_name['Daemon'] = _DAEMON

# @@protoc_insertion_point(module_scope)
