# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/daemon/messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "solipsis.gkk.daemon.PingRequest" do
    optional :params, :message, 1, "solipsis.gkk.daemon.PingParams"
  end
  add_message "solipsis.gkk.daemon.PingParams" do
    optional :msg, :string, 1
    optional :display, :bool, 2
    optional :pin, :bool, 3
    optional :passphrase, :bool, 4
  end
  add_message "solipsis.gkk.daemon.PingResponse" do
    optional :response, :string, 1
    optional :auth_request, :message, 2, "solipsis.gkk.daemon.AuthRequest"
  end
  add_message "solipsis.gkk.daemon.AuthRequest" do
    optional :button, :message, 1, "solipsis.gkk.daemon.ButtonRequest"
    optional :pin, :message, 2, "solipsis.gkk.daemon.PinRequest"
    optional :pass, :message, 3, "solipsis.gkk.daemon.PassphraseRequest"
  end
  add_message "solipsis.gkk.daemon.ButtonRequest" do
  end
  add_message "solipsis.gkk.daemon.PinRequest" do
  end
  add_message "solipsis.gkk.daemon.PassphraseRequest" do
  end
  add_message "solipsis.gkk.daemon.AuthResponse" do
    optional :button, :message, 1, "solipsis.gkk.daemon.ButtonResponse"
    optional :pin, :message, 2, "solipsis.gkk.daemon.PinResponse"
    optional :pass, :message, 3, "solipsis.gkk.daemon.PassphraseResponse"
  end
  add_message "solipsis.gkk.daemon.ButtonResponse" do
  end
  add_message "solipsis.gkk.daemon.PinResponse" do
    optional :pin, :string, 1
  end
  add_message "solipsis.gkk.daemon.PassphraseResponse" do
    optional :passphrase, :string, 1
  end
end

module Solipsis
  module Gkk
    module Daemon
      PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PingRequest").msgclass
      PingParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PingParams").msgclass
      PingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PingResponse").msgclass
      AuthRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.AuthRequest").msgclass
      ButtonRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.ButtonRequest").msgclass
      PinRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PinRequest").msgclass
      PassphraseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PassphraseRequest").msgclass
      AuthResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.AuthResponse").msgclass
      ButtonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.ButtonResponse").msgclass
      PinResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PinResponse").msgclass
      PassphraseResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("solipsis.gkk.daemon.PassphraseResponse").msgclass
    end
  end
end
