// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/daemon/messages.proto

package daemon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Test documenattion
type PingParams struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Display              bool     `protobuf:"varint,2,opt,name=display,proto3" json:"display,omitempty"`
	Pin                  bool     `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Passphrase           bool     `protobuf:"varint,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingParams) Reset()         { *m = PingParams{} }
func (m *PingParams) String() string { return proto.CompactTextString(m) }
func (*PingParams) ProtoMessage()    {}
func (*PingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_e2ae39757c0e93bc, []int{0}
}
func (m *PingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingParams.Unmarshal(m, b)
}
func (m *PingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingParams.Marshal(b, m, deterministic)
}
func (dst *PingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingParams.Merge(dst, src)
}
func (m *PingParams) XXX_Size() int {
	return xxx_messageInfo_PingParams.Size(m)
}
func (m *PingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PingParams.DiscardUnknown(m)
}

var xxx_messageInfo_PingParams proto.InternalMessageInfo

func (m *PingParams) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PingParams) GetDisplay() bool {
	if m != nil {
		return m.Display
	}
	return false
}

func (m *PingParams) GetPin() bool {
	if m != nil {
		return m.Pin
	}
	return false
}

func (m *PingParams) GetPassphrase() bool {
	if m != nil {
		return m.Passphrase
	}
	return false
}

// TEst repsopnse stuff
type PingResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_e2ae39757c0e93bc, []int{1}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*PingParams)(nil), "solipsis.gkk.daemon.PingParams")
	proto.RegisterType((*PingResponse)(nil), "solipsis.gkk.daemon.PingResponse")
}

func init() { proto.RegisterFile("rpc/daemon/messages.proto", fileDescriptor_messages_e2ae39757c0e93bc) }

var fileDescriptor_messages_e2ae39757c0e93bc = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0x87, 0x30,
	0x14, 0xc4, 0x83, 0x10, 0xc4, 0x17, 0x07, 0x53, 0x97, 0xca, 0xa0, 0xc8, 0x44, 0x1c, 0x4a, 0xa2,
	0xdf, 0xc0, 0x38, 0x39, 0x11, 0xe2, 0xe4, 0x56, 0xa5, 0xa9, 0x15, 0xda, 0xbe, 0xf4, 0xb9, 0xf8,
	0xed, 0x4d, 0x0b, 0xa8, 0xc3, 0xff, 0xbf, 0xdd, 0x5d, 0xaf, 0xb9, 0x5f, 0x1e, 0x5c, 0x05, 0x7c,
	0xef, 0x27, 0xa9, 0xac, 0x77, 0xbd, 0x55, 0x44, 0x52, 0x2b, 0x12, 0x18, 0xfc, 0x97, 0x67, 0x97,
	0xe4, 0x17, 0x83, 0x64, 0x48, 0xe8, 0x79, 0x16, 0x6b, 0xa7, 0xfd, 0x04, 0x18, 0x8c, 0xd3, 0x83,
	0x0c, 0xd2, 0x12, 0xbb, 0x80, 0xdc, 0x92, 0xe6, 0x59, 0x93, 0x75, 0x67, 0x63, 0x94, 0x8c, 0xc3,
	0xe9, 0x64, 0x08, 0x17, 0xf9, 0xcd, 0x4f, 0x9a, 0xac, 0xab, 0xc6, 0xdd, 0xc6, 0x2e, 0x1a, 0xc7,
	0xf3, 0x94, 0x46, 0xc9, 0xae, 0x01, 0x50, 0x12, 0xe1, 0x47, 0x90, 0xa4, 0x78, 0x91, 0x1e, 0xfe,
	0x25, 0xed, 0x1d, 0x9c, 0xc7, 0xad, 0x51, 0x11, 0x7a, 0x47, 0x8a, 0xd5, 0x50, 0x85, 0x4d, 0x6f,
	0x93, 0xbf, 0xfe, 0xfe, 0x05, 0xca, 0xa7, 0x44, 0xc8, 0x9e, 0xa1, 0x88, 0xbf, 0xd8, 0x8d, 0x38,
	0xc0, 0x2f, 0xfe, 0xe0, 0xeb, 0xdb, 0xa3, 0x85, 0x7d, 0xf1, 0xb1, 0x7a, 0x2d, 0xd7, 0xf8, 0xad,
	0x4c, 0x37, 0x79, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x29, 0x89, 0x9e, 0x30, 0x01, 0x00,
	0x00,
}
