// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package keepkey

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
// Type of failures returned by Failure message
// @used_in Failure
type FailureType int32

const (
	FailureType_Failure_UnexpectedMessage FailureType = 1
	FailureType_Failure_ButtonExpected    FailureType = 2
	FailureType_Failure_SyntaxError       FailureType = 3
	FailureType_Failure_ActionCancelled   FailureType = 4
	FailureType_Failure_PinExpected       FailureType = 5
	FailureType_Failure_PinCancelled      FailureType = 6
	FailureType_Failure_PinInvalid        FailureType = 7
	FailureType_Failure_InvalidSignature  FailureType = 8
	FailureType_Failure_Other             FailureType = 9
	FailureType_Failure_NotEnoughFunds    FailureType = 10
	FailureType_Failure_NotInitialized    FailureType = 11
	FailureType_Failure_FirmwareError     FailureType = 99
)

var FailureType_name = map[int32]string{
	1:  "Failure_UnexpectedMessage",
	2:  "Failure_ButtonExpected",
	3:  "Failure_SyntaxError",
	4:  "Failure_ActionCancelled",
	5:  "Failure_PinExpected",
	6:  "Failure_PinCancelled",
	7:  "Failure_PinInvalid",
	8:  "Failure_InvalidSignature",
	9:  "Failure_Other",
	10: "Failure_NotEnoughFunds",
	11: "Failure_NotInitialized",
	99: "Failure_FirmwareError",
}
var FailureType_value = map[string]int32{
	"Failure_UnexpectedMessage": 1,
	"Failure_ButtonExpected":    2,
	"Failure_SyntaxError":       3,
	"Failure_ActionCancelled":   4,
	"Failure_PinExpected":       5,
	"Failure_PinCancelled":      6,
	"Failure_PinInvalid":        7,
	"Failure_InvalidSignature":  8,
	"Failure_Other":             9,
	"Failure_NotEnoughFunds":    10,
	"Failure_NotInitialized":    11,
	"Failure_FirmwareError":     99,
}

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}
func (x FailureType) String() string {
	return proto.EnumName(FailureType_name, int32(x))
}
func (x *FailureType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FailureType_value, data, "FailureType")
	if err != nil {
		return err
	}
	*x = FailureType(value)
	return nil
}
func (FailureType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// *
// Type of script which will be used for transaction output
// @used_in TxOutputType
type OutputScriptType int32

const (
	OutputScriptType_PAYTOADDRESS     OutputScriptType = 0
	OutputScriptType_PAYTOSCRIPTHASH  OutputScriptType = 1
	OutputScriptType_PAYTOMULTISIG    OutputScriptType = 2
	OutputScriptType_PAYTOOPRETURN    OutputScriptType = 3
	OutputScriptType_PAYTOWITNESS     OutputScriptType = 4
	OutputScriptType_PAYTOP2SHWITNESS OutputScriptType = 5
)

var OutputScriptType_name = map[int32]string{
	0: "PAYTOADDRESS",
	1: "PAYTOSCRIPTHASH",
	2: "PAYTOMULTISIG",
	3: "PAYTOOPRETURN",
	4: "PAYTOWITNESS",
	5: "PAYTOP2SHWITNESS",
}
var OutputScriptType_value = map[string]int32{
	"PAYTOADDRESS":     0,
	"PAYTOSCRIPTHASH":  1,
	"PAYTOMULTISIG":    2,
	"PAYTOOPRETURN":    3,
	"PAYTOWITNESS":     4,
	"PAYTOP2SHWITNESS": 5,
}

func (x OutputScriptType) Enum() *OutputScriptType {
	p := new(OutputScriptType)
	*p = x
	return p
}
func (x OutputScriptType) String() string {
	return proto.EnumName(OutputScriptType_name, int32(x))
}
func (x *OutputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputScriptType_value, data, "OutputScriptType")
	if err != nil {
		return err
	}
	*x = OutputScriptType(value)
	return nil
}
func (OutputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// *
// Type of script which will be used for transaction output
// @used_in TxInputType
type InputScriptType int32

const (
	InputScriptType_SPENDADDRESS     InputScriptType = 0
	InputScriptType_SPENDMULTISIG    InputScriptType = 1
	InputScriptType_EXTERNAL         InputScriptType = 2
	InputScriptType_SPENDWITNESS     InputScriptType = 3
	InputScriptType_SPENDP2SHWITNESS InputScriptType = 4
)

var InputScriptType_name = map[int32]string{
	0: "SPENDADDRESS",
	1: "SPENDMULTISIG",
	2: "EXTERNAL",
	3: "SPENDWITNESS",
	4: "SPENDP2SHWITNESS",
}
var InputScriptType_value = map[string]int32{
	"SPENDADDRESS":     0,
	"SPENDMULTISIG":    1,
	"EXTERNAL":         2,
	"SPENDWITNESS":     3,
	"SPENDP2SHWITNESS": 4,
}

func (x InputScriptType) Enum() *InputScriptType {
	p := new(InputScriptType)
	*p = x
	return p
}
func (x InputScriptType) String() string {
	return proto.EnumName(InputScriptType_name, int32(x))
}
func (x *InputScriptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(InputScriptType_value, data, "InputScriptType")
	if err != nil {
		return err
	}
	*x = InputScriptType(value)
	return nil
}
func (InputScriptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// *
// Type of information required by transaction signing process
// @used_in TxRequest
type RequestType int32

const (
	RequestType_TXINPUT     RequestType = 0
	RequestType_TXOUTPUT    RequestType = 1
	RequestType_TXMETA      RequestType = 2
	RequestType_TXFINISHED  RequestType = 3
	RequestType_TXEXTRADATA RequestType = 4
)

var RequestType_name = map[int32]string{
	0: "TXINPUT",
	1: "TXOUTPUT",
	2: "TXMETA",
	3: "TXFINISHED",
	4: "TXEXTRADATA",
}
var RequestType_value = map[string]int32{
	"TXINPUT":     0,
	"TXOUTPUT":    1,
	"TXMETA":      2,
	"TXFINISHED":  3,
	"TXEXTRADATA": 4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// *
// Type of ouput address specify in transaction
// @used_in TxOutputType
type OutputAddressType int32

const (
	OutputAddressType_SPEND    OutputAddressType = 0
	OutputAddressType_TRANSFER OutputAddressType = 1
	OutputAddressType_CHANGE   OutputAddressType = 2
	OutputAddressType_EXCHANGE OutputAddressType = 3
)

var OutputAddressType_name = map[int32]string{
	0: "SPEND",
	1: "TRANSFER",
	2: "CHANGE",
	3: "EXCHANGE",
}
var OutputAddressType_value = map[string]int32{
	"SPEND":    0,
	"TRANSFER": 1,
	"CHANGE":   2,
	"EXCHANGE": 3,
}

func (x OutputAddressType) Enum() *OutputAddressType {
	p := new(OutputAddressType)
	*p = x
	return p
}
func (x OutputAddressType) String() string {
	return proto.EnumName(OutputAddressType_name, int32(x))
}
func (x *OutputAddressType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputAddressType_value, data, "OutputAddressType")
	if err != nil {
		return err
	}
	*x = OutputAddressType(value)
	return nil
}
func (OutputAddressType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// *
// Type of button request
// @used_in ButtonRequest
type ButtonRequestType int32

const (
	ButtonRequestType_ButtonRequest_Other                     ButtonRequestType = 1
	ButtonRequestType_ButtonRequest_FeeOverThreshold          ButtonRequestType = 2
	ButtonRequestType_ButtonRequest_ConfirmOutput             ButtonRequestType = 3
	ButtonRequestType_ButtonRequest_ResetDevice               ButtonRequestType = 4
	ButtonRequestType_ButtonRequest_ConfirmWord               ButtonRequestType = 5
	ButtonRequestType_ButtonRequest_WipeDevice                ButtonRequestType = 6
	ButtonRequestType_ButtonRequest_ProtectCall               ButtonRequestType = 7
	ButtonRequestType_ButtonRequest_SignTx                    ButtonRequestType = 8
	ButtonRequestType_ButtonRequest_FirmwareCheck             ButtonRequestType = 9
	ButtonRequestType_ButtonRequest_Address                   ButtonRequestType = 10
	ButtonRequestType_ButtonRequest_FirmwareErase             ButtonRequestType = 11
	ButtonRequestType_ButtonRequest_ConfirmTransferToAccount  ButtonRequestType = 12
	ButtonRequestType_ButtonRequest_ConfirmTransferToNodePath ButtonRequestType = 13
	ButtonRequestType_ButtonRequest_ChangeLabel               ButtonRequestType = 14
	ButtonRequestType_ButtonRequest_ChangeLanguage            ButtonRequestType = 15
	ButtonRequestType_ButtonRequest_EnablePassphrase          ButtonRequestType = 16
	ButtonRequestType_ButtonRequest_DisablePassphrase         ButtonRequestType = 17
	ButtonRequestType_ButtonRequest_EncryptAndSignMessage     ButtonRequestType = 18
	ButtonRequestType_ButtonRequest_EncryptMessage            ButtonRequestType = 19
	ButtonRequestType_ButtonRequest_ImportPrivateKey          ButtonRequestType = 20
	ButtonRequestType_ButtonRequest_ImportRecoverySentence    ButtonRequestType = 21
	ButtonRequestType_ButtonRequest_SignIdentity              ButtonRequestType = 22
	ButtonRequestType_ButtonRequest_Ping                      ButtonRequestType = 23
	ButtonRequestType_ButtonRequest_RemovePin                 ButtonRequestType = 24
	ButtonRequestType_ButtonRequest_ChangePin                 ButtonRequestType = 25
	ButtonRequestType_ButtonRequest_CreatePin                 ButtonRequestType = 26
	ButtonRequestType_ButtonRequest_GetEntropy                ButtonRequestType = 27
	ButtonRequestType_ButtonRequest_SignMessage               ButtonRequestType = 28
	ButtonRequestType_ButtonRequest_ApplyPolicies             ButtonRequestType = 29
	ButtonRequestType_ButtonRequest_SignExchange              ButtonRequestType = 30
)

var ButtonRequestType_name = map[int32]string{
	1:  "ButtonRequest_Other",
	2:  "ButtonRequest_FeeOverThreshold",
	3:  "ButtonRequest_ConfirmOutput",
	4:  "ButtonRequest_ResetDevice",
	5:  "ButtonRequest_ConfirmWord",
	6:  "ButtonRequest_WipeDevice",
	7:  "ButtonRequest_ProtectCall",
	8:  "ButtonRequest_SignTx",
	9:  "ButtonRequest_FirmwareCheck",
	10: "ButtonRequest_Address",
	11: "ButtonRequest_FirmwareErase",
	12: "ButtonRequest_ConfirmTransferToAccount",
	13: "ButtonRequest_ConfirmTransferToNodePath",
	14: "ButtonRequest_ChangeLabel",
	15: "ButtonRequest_ChangeLanguage",
	16: "ButtonRequest_EnablePassphrase",
	17: "ButtonRequest_DisablePassphrase",
	18: "ButtonRequest_EncryptAndSignMessage",
	19: "ButtonRequest_EncryptMessage",
	20: "ButtonRequest_ImportPrivateKey",
	21: "ButtonRequest_ImportRecoverySentence",
	22: "ButtonRequest_SignIdentity",
	23: "ButtonRequest_Ping",
	24: "ButtonRequest_RemovePin",
	25: "ButtonRequest_ChangePin",
	26: "ButtonRequest_CreatePin",
	27: "ButtonRequest_GetEntropy",
	28: "ButtonRequest_SignMessage",
	29: "ButtonRequest_ApplyPolicies",
	30: "ButtonRequest_SignExchange",
}
var ButtonRequestType_value = map[string]int32{
	"ButtonRequest_Other":                     1,
	"ButtonRequest_FeeOverThreshold":          2,
	"ButtonRequest_ConfirmOutput":             3,
	"ButtonRequest_ResetDevice":               4,
	"ButtonRequest_ConfirmWord":               5,
	"ButtonRequest_WipeDevice":                6,
	"ButtonRequest_ProtectCall":               7,
	"ButtonRequest_SignTx":                    8,
	"ButtonRequest_FirmwareCheck":             9,
	"ButtonRequest_Address":                   10,
	"ButtonRequest_FirmwareErase":             11,
	"ButtonRequest_ConfirmTransferToAccount":  12,
	"ButtonRequest_ConfirmTransferToNodePath": 13,
	"ButtonRequest_ChangeLabel":               14,
	"ButtonRequest_ChangeLanguage":            15,
	"ButtonRequest_EnablePassphrase":          16,
	"ButtonRequest_DisablePassphrase":         17,
	"ButtonRequest_EncryptAndSignMessage":     18,
	"ButtonRequest_EncryptMessage":            19,
	"ButtonRequest_ImportPrivateKey":          20,
	"ButtonRequest_ImportRecoverySentence":    21,
	"ButtonRequest_SignIdentity":              22,
	"ButtonRequest_Ping":                      23,
	"ButtonRequest_RemovePin":                 24,
	"ButtonRequest_ChangePin":                 25,
	"ButtonRequest_CreatePin":                 26,
	"ButtonRequest_GetEntropy":                27,
	"ButtonRequest_SignMessage":               28,
	"ButtonRequest_ApplyPolicies":             29,
	"ButtonRequest_SignExchange":              30,
}

func (x ButtonRequestType) Enum() *ButtonRequestType {
	p := new(ButtonRequestType)
	*p = x
	return p
}
func (x ButtonRequestType) String() string {
	return proto.EnumName(ButtonRequestType_name, int32(x))
}
func (x *ButtonRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ButtonRequestType_value, data, "ButtonRequestType")
	if err != nil {
		return err
	}
	*x = ButtonRequestType(value)
	return nil
}
func (ButtonRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

// *
// Type of PIN request
// @used_in PinMatrixRequest
type PinMatrixRequestType int32

const (
	PinMatrixRequestType_PinMatrixRequestType_Current   PinMatrixRequestType = 1
	PinMatrixRequestType_PinMatrixRequestType_NewFirst  PinMatrixRequestType = 2
	PinMatrixRequestType_PinMatrixRequestType_NewSecond PinMatrixRequestType = 3
)

var PinMatrixRequestType_name = map[int32]string{
	1: "PinMatrixRequestType_Current",
	2: "PinMatrixRequestType_NewFirst",
	3: "PinMatrixRequestType_NewSecond",
}
var PinMatrixRequestType_value = map[string]int32{
	"PinMatrixRequestType_Current":   1,
	"PinMatrixRequestType_NewFirst":  2,
	"PinMatrixRequestType_NewSecond": 3,
}

func (x PinMatrixRequestType) Enum() *PinMatrixRequestType {
	p := new(PinMatrixRequestType)
	*p = x
	return p
}
func (x PinMatrixRequestType) String() string {
	return proto.EnumName(PinMatrixRequestType_name, int32(x))
}
func (x *PinMatrixRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PinMatrixRequestType_value, data, "PinMatrixRequestType")
	if err != nil {
		return err
	}
	*x = PinMatrixRequestType(value)
	return nil
}
func (PinMatrixRequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

// *
// Structure representing BIP32 (hierarchical deterministic) node
// Used for imports of private key into the device and exporting public key out of device
// @used_in PublicKey
// @used_in LoadDevice
// @used_in DebugLinkState
// @used_in Storage
type HDNodeType struct {
	Depth            *uint32 `protobuf:"varint,1,req,name=depth" json:"depth,omitempty"`
	Fingerprint      *uint32 `protobuf:"varint,2,req,name=fingerprint" json:"fingerprint,omitempty"`
	ChildNum         *uint32 `protobuf:"varint,3,req,name=child_num,json=childNum" json:"child_num,omitempty"`
	ChainCode        []byte  `protobuf:"bytes,4,req,name=chain_code,json=chainCode" json:"chain_code,omitempty"`
	PrivateKey       []byte  `protobuf:"bytes,5,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	PublicKey        []byte  `protobuf:"bytes,6,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HDNodeType) Reset()                    { *m = HDNodeType{} }
func (m *HDNodeType) String() string            { return proto.CompactTextString(m) }
func (*HDNodeType) ProtoMessage()               {}
func (*HDNodeType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *HDNodeType) GetDepth() uint32 {
	if m != nil && m.Depth != nil {
		return *m.Depth
	}
	return 0
}

func (m *HDNodeType) GetFingerprint() uint32 {
	if m != nil && m.Fingerprint != nil {
		return *m.Fingerprint
	}
	return 0
}

func (m *HDNodeType) GetChildNum() uint32 {
	if m != nil && m.ChildNum != nil {
		return *m.ChildNum
	}
	return 0
}

func (m *HDNodeType) GetChainCode() []byte {
	if m != nil {
		return m.ChainCode
	}
	return nil
}

func (m *HDNodeType) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HDNodeType) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type HDNodePathType struct {
	Node             *HDNodeType `protobuf:"bytes,1,req,name=node" json:"node,omitempty"`
	AddressN         []uint32    `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *HDNodePathType) Reset()                    { *m = HDNodePathType{} }
func (m *HDNodePathType) String() string            { return proto.CompactTextString(m) }
func (*HDNodePathType) ProtoMessage()               {}
func (*HDNodePathType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *HDNodePathType) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HDNodePathType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

// *
// Structure representing Coin
// @used_in Features
type CoinType struct {
	CoinName            *string `protobuf:"bytes,1,opt,name=coin_name,json=coinName" json:"coin_name,omitempty"`
	CoinShortcut        *string `protobuf:"bytes,2,opt,name=coin_shortcut,json=coinShortcut" json:"coin_shortcut,omitempty"`
	AddressType         *uint32 `protobuf:"varint,3,opt,name=address_type,json=addressType,def=0" json:"address_type,omitempty"`
	MaxfeeKb            *uint64 `protobuf:"varint,4,opt,name=maxfee_kb,json=maxfeeKb" json:"maxfee_kb,omitempty"`
	AddressTypeP2Sh     *uint32 `protobuf:"varint,5,opt,name=address_type_p2sh,json=addressTypeP2sh,def=5" json:"address_type_p2sh,omitempty"`
	AddressTypeP2Wpkh   *uint32 `protobuf:"varint,6,opt,name=address_type_p2wpkh,json=addressTypeP2wpkh,def=6" json:"address_type_p2wpkh,omitempty"`
	AddressTypeP2Wsh    *uint32 `protobuf:"varint,7,opt,name=address_type_p2wsh,json=addressTypeP2wsh,def=10" json:"address_type_p2wsh,omitempty"`
	SignedMessageHeader *string `protobuf:"bytes,8,opt,name=signed_message_header,json=signedMessageHeader" json:"signed_message_header,omitempty"`
	Bip44AccountPath    *uint32 `protobuf:"varint,9,opt,name=bip44_account_path,json=bip44AccountPath" json:"bip44_account_path,omitempty"`
	Forkid              *uint32 `protobuf:"varint,12,opt,name=forkid" json:"forkid,omitempty"`
	Decimals            *uint32 `protobuf:"varint,13,opt,name=decimals" json:"decimals,omitempty"`
	ContractAddress     *string `protobuf:"bytes,14,opt,name=contract_address,json=contractAddress" json:"contract_address,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CoinType) Reset()                    { *m = CoinType{} }
func (m *CoinType) String() string            { return proto.CompactTextString(m) }
func (*CoinType) ProtoMessage()               {}
func (*CoinType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

const Default_CoinType_AddressType uint32 = 0
const Default_CoinType_AddressTypeP2Sh uint32 = 5
const Default_CoinType_AddressTypeP2Wpkh uint32 = 6
const Default_CoinType_AddressTypeP2Wsh uint32 = 10

func (m *CoinType) GetCoinName() string {
	if m != nil && m.CoinName != nil {
		return *m.CoinName
	}
	return ""
}

func (m *CoinType) GetCoinShortcut() string {
	if m != nil && m.CoinShortcut != nil {
		return *m.CoinShortcut
	}
	return ""
}

func (m *CoinType) GetAddressType() uint32 {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return Default_CoinType_AddressType
}

func (m *CoinType) GetMaxfeeKb() uint64 {
	if m != nil && m.MaxfeeKb != nil {
		return *m.MaxfeeKb
	}
	return 0
}

func (m *CoinType) GetAddressTypeP2Sh() uint32 {
	if m != nil && m.AddressTypeP2Sh != nil {
		return *m.AddressTypeP2Sh
	}
	return Default_CoinType_AddressTypeP2Sh
}

func (m *CoinType) GetAddressTypeP2Wpkh() uint32 {
	if m != nil && m.AddressTypeP2Wpkh != nil {
		return *m.AddressTypeP2Wpkh
	}
	return Default_CoinType_AddressTypeP2Wpkh
}

func (m *CoinType) GetAddressTypeP2Wsh() uint32 {
	if m != nil && m.AddressTypeP2Wsh != nil {
		return *m.AddressTypeP2Wsh
	}
	return Default_CoinType_AddressTypeP2Wsh
}

func (m *CoinType) GetSignedMessageHeader() string {
	if m != nil && m.SignedMessageHeader != nil {
		return *m.SignedMessageHeader
	}
	return ""
}

func (m *CoinType) GetBip44AccountPath() uint32 {
	if m != nil && m.Bip44AccountPath != nil {
		return *m.Bip44AccountPath
	}
	return 0
}

func (m *CoinType) GetForkid() uint32 {
	if m != nil && m.Forkid != nil {
		return *m.Forkid
	}
	return 0
}

func (m *CoinType) GetDecimals() uint32 {
	if m != nil && m.Decimals != nil {
		return *m.Decimals
	}
	return 0
}

func (m *CoinType) GetContractAddress() string {
	if m != nil && m.ContractAddress != nil {
		return *m.ContractAddress
	}
	return ""
}

// *
// Type of redeem script used in input
// @used_in TxInputType
type MultisigRedeemScriptType struct {
	Pubkeys          []*HDNodePathType `protobuf:"bytes,1,rep,name=pubkeys" json:"pubkeys,omitempty"`
	Signatures       [][]byte          `protobuf:"bytes,2,rep,name=signatures" json:"signatures,omitempty"`
	M                *uint32           `protobuf:"varint,3,opt,name=m" json:"m,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MultisigRedeemScriptType) Reset()                    { *m = MultisigRedeemScriptType{} }
func (m *MultisigRedeemScriptType) String() string            { return proto.CompactTextString(m) }
func (*MultisigRedeemScriptType) ProtoMessage()               {}
func (*MultisigRedeemScriptType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MultisigRedeemScriptType) GetPubkeys() []*HDNodePathType {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetSignatures() [][]byte {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *MultisigRedeemScriptType) GetM() uint32 {
	if m != nil && m.M != nil {
		return *m.M
	}
	return 0
}

// *
// Structure representing transaction input
// @used_in SimpleSignTx
// @used_in TransactionType
type TxInputType struct {
	AddressN         []uint32                  `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	PrevHash         []byte                    `protobuf:"bytes,2,req,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	PrevIndex        *uint32                   `protobuf:"varint,3,req,name=prev_index,json=prevIndex" json:"prev_index,omitempty"`
	ScriptSig        []byte                    `protobuf:"bytes,4,opt,name=script_sig,json=scriptSig" json:"script_sig,omitempty"`
	Sequence         *uint32                   `protobuf:"varint,5,opt,name=sequence,def=4294967295" json:"sequence,omitempty"`
	ScriptType       *InputScriptType          `protobuf:"varint,6,opt,name=script_type,json=scriptType,enum=InputScriptType,def=0" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,7,opt,name=multisig" json:"multisig,omitempty"`
	Amount           *uint64                   `protobuf:"varint,8,opt,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxInputType) Reset()                    { *m = TxInputType{} }
func (m *TxInputType) String() string            { return proto.CompactTextString(m) }
func (*TxInputType) ProtoMessage()               {}
func (*TxInputType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

const Default_TxInputType_Sequence uint32 = 4294967295
const Default_TxInputType_ScriptType InputScriptType = InputScriptType_SPENDADDRESS

func (m *TxInputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxInputType) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *TxInputType) GetPrevIndex() uint32 {
	if m != nil && m.PrevIndex != nil {
		return *m.PrevIndex
	}
	return 0
}

func (m *TxInputType) GetScriptSig() []byte {
	if m != nil {
		return m.ScriptSig
	}
	return nil
}

func (m *TxInputType) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return Default_TxInputType_Sequence
}

func (m *TxInputType) GetScriptType() InputScriptType {
	if m != nil && m.ScriptType != nil {
		return *m.ScriptType
	}
	return Default_TxInputType_ScriptType
}

func (m *TxInputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxInputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// *
// Structure representing transaction output
// @used_in SimpleSignTx
// @used_in TransactionType
type TxOutputType struct {
	Address          *string                   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AddressN         []uint32                  `protobuf:"varint,2,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Amount           *uint64                   `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	ScriptType       *OutputScriptType         `protobuf:"varint,4,req,name=script_type,json=scriptType,enum=OutputScriptType" json:"script_type,omitempty"`
	Multisig         *MultisigRedeemScriptType `protobuf:"bytes,5,opt,name=multisig" json:"multisig,omitempty"`
	OpReturnData     []byte                    `protobuf:"bytes,6,opt,name=op_return_data,json=opReturnData" json:"op_return_data,omitempty"`
	AddressType      *OutputAddressType        `protobuf:"varint,7,opt,name=address_type,json=addressType,enum=OutputAddressType" json:"address_type,omitempty"`
	ExchangeType     *ExchangeType             `protobuf:"bytes,8,opt,name=exchange_type,json=exchangeType" json:"exchange_type,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *TxOutputType) Reset()                    { *m = TxOutputType{} }
func (m *TxOutputType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputType) ProtoMessage()               {}
func (*TxOutputType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *TxOutputType) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *TxOutputType) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *TxOutputType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputType) GetScriptType() OutputScriptType {
	if m != nil && m.ScriptType != nil {
		return *m.ScriptType
	}
	return OutputScriptType_PAYTOADDRESS
}

func (m *TxOutputType) GetMultisig() *MultisigRedeemScriptType {
	if m != nil {
		return m.Multisig
	}
	return nil
}

func (m *TxOutputType) GetOpReturnData() []byte {
	if m != nil {
		return m.OpReturnData
	}
	return nil
}

func (m *TxOutputType) GetAddressType() OutputAddressType {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return OutputAddressType_SPEND
}

func (m *TxOutputType) GetExchangeType() *ExchangeType {
	if m != nil {
		return m.ExchangeType
	}
	return nil
}

// *
// Structure representing compiled transaction output
// @used_in TransactionType
type TxOutputBinType struct {
	Amount           *uint64 `protobuf:"varint,1,req,name=amount" json:"amount,omitempty"`
	ScriptPubkey     []byte  `protobuf:"bytes,2,req,name=script_pubkey,json=scriptPubkey" json:"script_pubkey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxOutputBinType) Reset()                    { *m = TxOutputBinType{} }
func (m *TxOutputBinType) String() string            { return proto.CompactTextString(m) }
func (*TxOutputBinType) ProtoMessage()               {}
func (*TxOutputBinType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *TxOutputBinType) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *TxOutputBinType) GetScriptPubkey() []byte {
	if m != nil {
		return m.ScriptPubkey
	}
	return nil
}

// *
// Structure representing transaction
// @used_in SimpleSignTx,
type TransactionType struct {
	Version          *uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Inputs           []*TxInputType     `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	BinOutputs       []*TxOutputBinType `protobuf:"bytes,3,rep,name=bin_outputs,json=binOutputs" json:"bin_outputs,omitempty"`
	Outputs          []*TxOutputType    `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	LockTime         *uint32            `protobuf:"varint,4,opt,name=lock_time,json=lockTime" json:"lock_time,omitempty"`
	InputsCnt        *uint32            `protobuf:"varint,6,opt,name=inputs_cnt,json=inputsCnt" json:"inputs_cnt,omitempty"`
	OutputsCnt       *uint32            `protobuf:"varint,7,opt,name=outputs_cnt,json=outputsCnt" json:"outputs_cnt,omitempty"`
	ExtraData        []byte             `protobuf:"bytes,8,opt,name=extra_data,json=extraData" json:"extra_data,omitempty"`
	ExtraDataLen     *uint32            `protobuf:"varint,9,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TransactionType) Reset()                    { *m = TransactionType{} }
func (m *TransactionType) String() string            { return proto.CompactTextString(m) }
func (*TransactionType) ProtoMessage()               {}
func (*TransactionType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *TransactionType) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *TransactionType) GetInputs() []*TxInputType {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionType) GetBinOutputs() []*TxOutputBinType {
	if m != nil {
		return m.BinOutputs
	}
	return nil
}

func (m *TransactionType) GetOutputs() []*TxOutputType {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *TransactionType) GetLockTime() uint32 {
	if m != nil && m.LockTime != nil {
		return *m.LockTime
	}
	return 0
}

func (m *TransactionType) GetInputsCnt() uint32 {
	if m != nil && m.InputsCnt != nil {
		return *m.InputsCnt
	}
	return 0
}

func (m *TransactionType) GetOutputsCnt() uint32 {
	if m != nil && m.OutputsCnt != nil {
		return *m.OutputsCnt
	}
	return 0
}

func (m *TransactionType) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *TransactionType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

// *
// Structure representing raw transaction
// @used_in RawTxAck
type RawTransactionType struct {
	Payload          []byte `protobuf:"bytes,1,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RawTransactionType) Reset()                    { *m = RawTransactionType{} }
func (m *RawTransactionType) String() string            { return proto.CompactTextString(m) }
func (*RawTransactionType) ProtoMessage()               {}
func (*RawTransactionType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *RawTransactionType) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// *
// Structure representing request details
// @used_in TxRequest
type TxRequestDetailsType struct {
	RequestIndex     *uint32 `protobuf:"varint,1,opt,name=request_index,json=requestIndex" json:"request_index,omitempty"`
	TxHash           []byte  `protobuf:"bytes,2,opt,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
	ExtraDataLen     *uint32 `protobuf:"varint,3,opt,name=extra_data_len,json=extraDataLen" json:"extra_data_len,omitempty"`
	ExtraDataOffset  *uint32 `protobuf:"varint,4,opt,name=extra_data_offset,json=extraDataOffset" json:"extra_data_offset,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestDetailsType) Reset()                    { *m = TxRequestDetailsType{} }
func (m *TxRequestDetailsType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestDetailsType) ProtoMessage()               {}
func (*TxRequestDetailsType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *TxRequestDetailsType) GetRequestIndex() uint32 {
	if m != nil && m.RequestIndex != nil {
		return *m.RequestIndex
	}
	return 0
}

func (m *TxRequestDetailsType) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *TxRequestDetailsType) GetExtraDataLen() uint32 {
	if m != nil && m.ExtraDataLen != nil {
		return *m.ExtraDataLen
	}
	return 0
}

func (m *TxRequestDetailsType) GetExtraDataOffset() uint32 {
	if m != nil && m.ExtraDataOffset != nil {
		return *m.ExtraDataOffset
	}
	return 0
}

// *
// Structure representing serialized data
// @used_in TxRequest
type TxRequestSerializedType struct {
	SignatureIndex   *uint32 `protobuf:"varint,1,opt,name=signature_index,json=signatureIndex" json:"signature_index,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	SerializedTx     []byte  `protobuf:"bytes,3,opt,name=serialized_tx,json=serializedTx" json:"serialized_tx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TxRequestSerializedType) Reset()                    { *m = TxRequestSerializedType{} }
func (m *TxRequestSerializedType) String() string            { return proto.CompactTextString(m) }
func (*TxRequestSerializedType) ProtoMessage()               {}
func (*TxRequestSerializedType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *TxRequestSerializedType) GetSignatureIndex() uint32 {
	if m != nil && m.SignatureIndex != nil {
		return *m.SignatureIndex
	}
	return 0
}

func (m *TxRequestSerializedType) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TxRequestSerializedType) GetSerializedTx() []byte {
	if m != nil {
		return m.SerializedTx
	}
	return nil
}

// *
// Structure representing identity data
// @used_in IdentityType
type IdentityType struct {
	Proto            *string `protobuf:"bytes,1,opt,name=proto" json:"proto,omitempty"`
	User             *string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Host             *string `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port             *string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
	Path             *string `protobuf:"bytes,5,opt,name=path" json:"path,omitempty"`
	Index            *uint32 `protobuf:"varint,6,opt,name=index,def=0" json:"index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IdentityType) Reset()                    { *m = IdentityType{} }
func (m *IdentityType) String() string            { return proto.CompactTextString(m) }
func (*IdentityType) ProtoMessage()               {}
func (*IdentityType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

const Default_IdentityType_Index uint32 = 0

func (m *IdentityType) GetProto() string {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return ""
}

func (m *IdentityType) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *IdentityType) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *IdentityType) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *IdentityType) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *IdentityType) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_IdentityType_Index
}

// *
// Structure representing policy data
// @used_in ApplyPolicy
type PolicyType struct {
	PolicyName       *string `protobuf:"bytes,1,opt,name=policy_name,json=policyName" json:"policy_name,omitempty"`
	Enabled          *bool   `protobuf:"varint,2,opt,name=enabled" json:"enabled,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PolicyType) Reset()                    { *m = PolicyType{} }
func (m *PolicyType) String() string            { return proto.CompactTextString(m) }
func (*PolicyType) ProtoMessage()               {}
func (*PolicyType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *PolicyType) GetPolicyName() string {
	if m != nil && m.PolicyName != nil {
		return *m.PolicyName
	}
	return ""
}

func (m *PolicyType) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

// *
// Structure representing exchange data
// @used_in TxOutputType
type ExchangeType struct {
	SignedExchangeResponse *SignedExchangeResponse `protobuf:"bytes,1,opt,name=signed_exchange_response,json=signedExchangeResponse" json:"signed_exchange_response,omitempty"`
	WithdrawalCoinName     *string                 `protobuf:"bytes,2,opt,name=withdrawal_coin_name,json=withdrawalCoinName,def=Bitcoin" json:"withdrawal_coin_name,omitempty"`
	WithdrawalAddressN     []uint32                `protobuf:"varint,3,rep,name=withdrawal_address_n,json=withdrawalAddressN" json:"withdrawal_address_n,omitempty"`
	ReturnAddressN         []uint32                `protobuf:"varint,4,rep,name=return_address_n,json=returnAddressN" json:"return_address_n,omitempty"`
	XXX_unrecognized       []byte                  `json:"-"`
}

func (m *ExchangeType) Reset()                    { *m = ExchangeType{} }
func (m *ExchangeType) String() string            { return proto.CompactTextString(m) }
func (*ExchangeType) ProtoMessage()               {}
func (*ExchangeType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

const Default_ExchangeType_WithdrawalCoinName string = "Bitcoin"

func (m *ExchangeType) GetSignedExchangeResponse() *SignedExchangeResponse {
	if m != nil {
		return m.SignedExchangeResponse
	}
	return nil
}

func (m *ExchangeType) GetWithdrawalCoinName() string {
	if m != nil && m.WithdrawalCoinName != nil {
		return *m.WithdrawalCoinName
	}
	return Default_ExchangeType_WithdrawalCoinName
}

func (m *ExchangeType) GetWithdrawalAddressN() []uint32 {
	if m != nil {
		return m.WithdrawalAddressN
	}
	return nil
}

func (m *ExchangeType) GetReturnAddressN() []uint32 {
	if m != nil {
		return m.ReturnAddressN
	}
	return nil
}

var E_WireIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50002,
	Name:          "wire_in",
	Tag:           "varint,50002,opt,name=wire_in,json=wireIn",
	Filename:      "types.proto",
}

var E_WireOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50003,
	Name:          "wire_out",
	Tag:           "varint,50003,opt,name=wire_out,json=wireOut",
	Filename:      "types.proto",
}

var E_WireDebugIn = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50004,
	Name:          "wire_debug_in",
	Tag:           "varint,50004,opt,name=wire_debug_in,json=wireDebugIn",
	Filename:      "types.proto",
}

var E_WireDebugOut = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50005,
	Name:          "wire_debug_out",
	Tag:           "varint,50005,opt,name=wire_debug_out,json=wireDebugOut",
	Filename:      "types.proto",
}

func init() {
	proto.RegisterType((*HDNodeType)(nil), "HDNodeType")
	proto.RegisterType((*HDNodePathType)(nil), "HDNodePathType")
	proto.RegisterType((*CoinType)(nil), "CoinType")
	proto.RegisterType((*MultisigRedeemScriptType)(nil), "MultisigRedeemScriptType")
	proto.RegisterType((*TxInputType)(nil), "TxInputType")
	proto.RegisterType((*TxOutputType)(nil), "TxOutputType")
	proto.RegisterType((*TxOutputBinType)(nil), "TxOutputBinType")
	proto.RegisterType((*TransactionType)(nil), "TransactionType")
	proto.RegisterType((*RawTransactionType)(nil), "RawTransactionType")
	proto.RegisterType((*TxRequestDetailsType)(nil), "TxRequestDetailsType")
	proto.RegisterType((*TxRequestSerializedType)(nil), "TxRequestSerializedType")
	proto.RegisterType((*IdentityType)(nil), "IdentityType")
	proto.RegisterType((*PolicyType)(nil), "PolicyType")
	proto.RegisterType((*ExchangeType)(nil), "ExchangeType")
	proto.RegisterEnum("FailureType", FailureType_name, FailureType_value)
	proto.RegisterEnum("OutputScriptType", OutputScriptType_name, OutputScriptType_value)
	proto.RegisterEnum("InputScriptType", InputScriptType_name, InputScriptType_value)
	proto.RegisterEnum("RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("OutputAddressType", OutputAddressType_name, OutputAddressType_value)
	proto.RegisterEnum("ButtonRequestType", ButtonRequestType_name, ButtonRequestType_value)
	proto.RegisterEnum("PinMatrixRequestType", PinMatrixRequestType_name, PinMatrixRequestType_value)
	proto.RegisterExtension(E_WireIn)
	proto.RegisterExtension(E_WireOut)
	proto.RegisterExtension(E_WireDebugIn)
	proto.RegisterExtension(E_WireDebugOut)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 2255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0xf1, 0x5f, 0x90, 0x92, 0x48, 0x36, 0x49, 0x69, 0x34, 0xd6, 0x5a, 0xf0, 0xb7, 0x96, 0x76, 0xad,
	0xb5, 0xfa, 0xff, 0xc3, 0xf5, 0xb2, 0xec, 0x4d, 0x59, 0x95, 0x4a, 0x8a, 0x96, 0x28, 0x8b, 0x65,
	0x9b, 0x62, 0x86, 0x50, 0xac, 0x9c, 0x50, 0x10, 0x30, 0x22, 0xa6, 0x04, 0x0e, 0x10, 0x60, 0x20,
	0x91, 0xb9, 0xe4, 0x94, 0xe4, 0x94, 0xd7, 0xc8, 0x5b, 0xa4, 0x2a, 0x2f, 0x90, 0x4a, 0x55, 0x3e,
	0x0e, 0xb9, 0xe7, 0x98, 0x07, 0xc8, 0x31, 0x35, 0x83, 0x01, 0x3f, 0x44, 0x39, 0xf1, 0x8d, 0xf3,
	0xfb, 0x75, 0xf7, 0x74, 0xf7, 0x74, 0xf7, 0x0c, 0x08, 0x55, 0x31, 0x89, 0x68, 0xd2, 0x8c, 0xe2,
	0x50, 0x84, 0xf7, 0x77, 0x86, 0x61, 0x38, 0x0c, 0xe8, 0xb7, 0x6a, 0x75, 0x9e, 0x5e, 0x7c, 0xeb,
	0xd1, 0xc4, 0x8d, 0x59, 0x24, 0xc2, 0x58, 0x4b, 0xac, 0xd3, 0xb1, 0xeb, 0x3b, 0x7c, 0x48, 0xb3,
	0x75, 0xe3, 0x8f, 0x06, 0xc0, 0xf1, 0x61, 0x2f, 0xf4, 0xa8, 0x35, 0x89, 0x28, 0xde, 0x82, 0x55,
	0x8f, 0x46, 0xc2, 0x37, 0x8d, 0x9d, 0xc2, 0x6e, 0x9d, 0x64, 0x0b, 0xbc, 0x03, 0xd5, 0x0b, 0xc6,
	0x87, 0x34, 0x8e, 0x62, 0xc6, 0x85, 0x59, 0x50, 0xdc, 0x3c, 0x84, 0x1f, 0x40, 0xc5, 0xf5, 0x59,
	0xe0, 0xd9, 0x3c, 0x1d, 0x99, 0x45, 0xc5, 0x97, 0x15, 0xd0, 0x4b, 0x47, 0xf8, 0x11, 0x80, 0xeb,
	0x3b, 0x8c, 0xdb, 0x6e, 0xe8, 0x51, 0x73, 0x65, 0xa7, 0xb0, 0x5b, 0x23, 0x15, 0x85, 0x1c, 0x84,
	0x1e, 0xc5, 0x4f, 0xa0, 0x1a, 0xc5, 0xec, 0xca, 0x11, 0xd4, 0xbe, 0xa4, 0x13, 0x73, 0x75, 0xc7,
	0xd8, 0xad, 0x11, 0xd0, 0xd0, 0x3b, 0x3a, 0x91, 0xfa, 0x51, 0x7a, 0x1e, 0x30, 0x57, 0xf1, 0x6b,
	0x8a, 0xaf, 0x64, 0xc8, 0x3b, 0x3a, 0x69, 0xf4, 0x60, 0x3d, 0x8b, 0xa0, 0xef, 0x08, 0x5f, 0x45,
	0xf1, 0x04, 0x56, 0xb8, 0xdc, 0x4a, 0x06, 0x51, 0x6d, 0x55, 0x9b, 0xb3, 0x00, 0x89, 0x22, 0xa4,
	0xbb, 0x8e, 0xe7, 0xc5, 0x34, 0x49, 0x6c, 0x6e, 0x16, 0x76, 0x8a, 0xd2, 0x5d, 0x0d, 0xf4, 0x1a,
	0xff, 0x2c, 0x42, 0xf9, 0x20, 0x64, 0x5c, 0x99, 0x92, 0x81, 0x85, 0x8c, 0xdb, 0xdc, 0x19, 0x49,
	0x7b, 0xc6, 0x6e, 0x85, 0x94, 0x25, 0xd0, 0x73, 0x46, 0x14, 0x3f, 0x85, 0xba, 0x22, 0x13, 0x3f,
	0x8c, 0x85, 0x9b, 0xca, 0xcc, 0x48, 0x81, 0x9a, 0x04, 0x07, 0x1a, 0xc3, 0xcf, 0xa0, 0x96, 0xef,
	0x25, 0x8f, 0xca, 0x2c, 0xee, 0x18, 0xbb, 0xf5, 0x7d, 0xe3, 0x05, 0xa9, 0x6a, 0x38, 0xdf, 0x67,
	0xe4, 0x8c, 0x2f, 0x28, 0xb5, 0x2f, 0xcf, 0xcd, 0x95, 0x1d, 0x63, 0x77, 0x85, 0x94, 0x33, 0xe0,
	0xdd, 0x39, 0xfe, 0x01, 0x6c, 0xce, 0x9b, 0xb0, 0xa3, 0x56, 0xe2, 0xab, 0x3c, 0xd5, 0xf7, 0x8d,
	0x57, 0x64, 0x63, 0xce, 0x4e, 0xbf, 0x95, 0xf8, 0xf8, 0x3b, 0xb8, 0x73, 0x43, 0xfc, 0x3a, 0xba,
	0xf4, 0x55, 0xe2, 0xea, 0xfb, 0xc6, 0xf7, 0x64, 0x73, 0x41, 0x41, 0x72, 0xf8, 0x05, 0xe0, 0x9b,
	0x2a, 0x89, 0x6f, 0x96, 0x94, 0x46, 0xe1, 0xbb, 0x17, 0x04, 0x2d, 0xaa, 0x24, 0x3e, 0x6e, 0xc1,
	0x97, 0x09, 0x1b, 0x72, 0xea, 0xd9, 0x23, 0x9a, 0x24, 0xce, 0x90, 0xda, 0x3e, 0x75, 0x3c, 0x1a,
	0x9b, 0x65, 0x95, 0x83, 0x3b, 0x19, 0xf9, 0x21, 0xe3, 0x8e, 0x15, 0x85, 0xff, 0x1f, 0xf0, 0x39,
	0x8b, 0x5e, 0xbe, 0xb4, 0x1d, 0xd7, 0x0d, 0x53, 0x2e, 0xec, 0xc8, 0x11, 0xbe, 0x59, 0x91, 0xbb,
	0x10, 0xa4, 0x98, 0x76, 0x46, 0xc8, 0x93, 0xc4, 0x77, 0x61, 0xed, 0x22, 0x8c, 0x2f, 0x99, 0x67,
	0xd6, 0x94, 0x84, 0x5e, 0xe1, 0xfb, 0x50, 0xf6, 0xa8, 0xcb, 0x46, 0x4e, 0x90, 0x98, 0x75, 0xc5,
	0x4c, 0xd7, 0xf8, 0x1b, 0x40, 0x6e, 0xc8, 0x45, 0xec, 0xb8, 0xc2, 0xd6, 0x2e, 0x9b, 0xeb, 0xca,
	0xa1, 0x8d, 0x1c, 0x6f, 0x67, 0x70, 0x23, 0x01, 0xf3, 0x43, 0x1a, 0x08, 0x96, 0xb0, 0x21, 0xa1,
	0x1e, 0xa5, 0xa3, 0x81, 0xea, 0x14, 0x75, 0x1a, 0xdf, 0x40, 0x29, 0x4a, 0xcf, 0x2f, 0xe9, 0x24,
	0x31, 0x8d, 0x9d, 0xe2, 0x6e, 0xb5, 0xb5, 0xd1, 0x5c, 0x2c, 0x31, 0x92, 0xf3, 0xf8, 0x31, 0x80,
	0x0c, 0xd5, 0x11, 0x69, 0x4c, 0x13, 0x55, 0x4b, 0x35, 0x32, 0x87, 0xe0, 0x1a, 0x18, 0xa3, 0xec,
	0xcc, 0x89, 0x31, 0x6a, 0xfc, 0xa1, 0x00, 0x55, 0x6b, 0xdc, 0xe5, 0x51, 0x2a, 0xf2, 0x63, 0x9f,
	0x15, 0xa2, 0xb1, 0x58, 0x88, 0x92, 0x8c, 0x62, 0x7a, 0x65, 0xfb, 0x4e, 0xe2, 0xab, 0xa6, 0xab,
	0x91, 0xb2, 0x04, 0x8e, 0x9d, 0xc4, 0x57, 0x4d, 0x21, 0x49, 0xc6, 0x3d, 0x3a, 0xd6, 0x2d, 0xa7,
	0xc4, 0xbb, 0x12, 0x90, 0x74, 0xd6, 0xf9, 0x76, 0xc2, 0x86, 0xaa, 0xa0, 0x6a, 0xa4, 0x92, 0x21,
	0x03, 0x36, 0xc4, 0x5f, 0x43, 0x39, 0xa1, 0xbf, 0x48, 0x29, 0x77, 0xa9, 0x2e, 0x24, 0x78, 0xd9,
	0x7a, 0xfd, 0xf2, 0xf5, 0xf7, 0x3f, 0x6c, 0xbd, 0x7e, 0x45, 0xa6, 0x1c, 0xfe, 0x09, 0x54, 0xb5,
	0x19, 0x55, 0xbb, 0xb2, 0x84, 0xd6, 0x5b, 0xa8, 0xa9, 0x02, 0x98, 0xe5, 0x6b, 0xbf, 0x36, 0xe8,
	0x77, 0x7a, 0x87, 0xed, 0xc3, 0x43, 0xd2, 0x19, 0x0c, 0x88, 0xde, 0x59, 0x05, 0xf8, 0x0a, 0xca,
	0x23, 0x9d, 0x65, 0x55, 0x4e, 0xd5, 0xd6, 0xbd, 0xe6, 0xa7, 0xd2, 0x4e, 0xa6, 0xa2, 0xf2, 0xec,
	0x9d, 0x91, 0xac, 0x04, 0x55, 0x4e, 0x2b, 0x44, 0xaf, 0x1a, 0xff, 0x28, 0x40, 0xcd, 0x1a, 0x9f,
	0xa4, 0x22, 0x4f, 0xa0, 0x09, 0xa5, 0xfc, 0x9c, 0xb3, 0xee, 0xcc, 0x97, 0xff, 0xb5, 0xc7, 0xe7,
	0xec, 0xcb, 0xcc, 0x4d, 0xed, 0xe3, 0xd6, 0x62, 0xbc, 0x72, 0x56, 0xad, 0xb7, 0x36, 0x9b, 0xd9,
	0x86, 0x73, 0x9e, 0x7e, 0x2a, 0xc4, 0xd5, 0xcf, 0x0f, 0xf1, 0x19, 0xac, 0x87, 0x91, 0x1d, 0x53,
	0x91, 0xc6, 0xdc, 0xf6, 0x1c, 0xe1, 0xe8, 0xc9, 0x56, 0x0b, 0x23, 0xa2, 0xc0, 0x43, 0x47, 0x38,
	0xf8, 0xd5, 0x8d, 0xe9, 0x51, 0x52, 0x27, 0x80, 0xb5, 0x47, 0xed, 0x59, 0x57, 0x2e, 0x8e, 0x93,
	0x16, 0xd4, 0xf3, 0x41, 0x9f, 0xe9, 0x95, 0x95, 0x63, 0xf5, 0x66, 0x47, 0xa3, 0x4a, 0xa5, 0x46,
	0xe7, 0x56, 0x8d, 0x1e, 0x6c, 0xe4, 0xa9, 0x7d, 0xa3, 0xa7, 0xdf, 0x2c, 0x4d, 0xc6, 0x42, 0x9a,
	0x9e, 0x42, 0x5d, 0xa7, 0x29, 0x6b, 0x03, 0x5d, 0x9d, 0xb5, 0x0c, 0xec, 0x2b, 0xac, 0xf1, 0xe7,
	0x02, 0x6c, 0x58, 0xb1, 0xc3, 0x13, 0xc7, 0x15, 0x2c, 0xe4, 0xf9, 0x71, 0x5d, 0xd1, 0x38, 0x61,
	0x21, 0x57, 0xc7, 0x55, 0x27, 0xf9, 0x12, 0x3f, 0x83, 0x35, 0x26, 0xab, 0x2a, 0xeb, 0xa1, 0x6a,
	0xab, 0xd6, 0x9c, 0xeb, 0x13, 0xa2, 0x39, 0xfc, 0x1d, 0x54, 0xcf, 0x19, 0xb7, 0x43, 0xe5, 0x65,
	0x62, 0x16, 0x95, 0x28, 0x6a, 0xde, 0xf0, 0x9b, 0xc0, 0x39, 0xe3, 0x19, 0x92, 0xe0, 0xe7, 0x50,
	0xca, 0xc5, 0x57, 0x95, 0x78, 0xbd, 0x39, 0x5f, 0x41, 0x24, 0x67, 0x65, 0xc1, 0x04, 0xa1, 0x7b,
	0x69, 0x0b, 0x36, 0xa2, 0xaa, 0x63, 0xea, 0xa4, 0x2c, 0x01, 0x8b, 0x8d, 0xa8, 0xec, 0xa7, 0xcc,
	0x05, 0xdb, 0xe5, 0x22, 0x1b, 0xa5, 0xa4, 0x92, 0x21, 0x07, 0x5c, 0xc8, 0x3b, 0x4c, 0x9b, 0x51,
	0xbc, 0x1a, 0x9c, 0x04, 0x34, 0x24, 0x05, 0x1e, 0x01, 0xd0, 0xb1, 0x88, 0x9d, 0xec, 0xa4, 0xcb,
	0x59, 0x3f, 0x2a, 0x44, 0x1d, 0xf3, 0x33, 0x58, 0x9f, 0xd1, 0x76, 0x40, 0xb9, 0x9e, 0x8a, 0xb5,
	0xa9, 0xc8, 0x7b, 0xca, 0x1b, 0x4d, 0xc0, 0xc4, 0xb9, 0xbe, 0x25, 0xa7, 0x91, 0x33, 0x09, 0x42,
	0xc7, 0x53, 0xa7, 0x54, 0x23, 0xf9, 0xb2, 0xf1, 0x7b, 0x03, 0xb6, 0xac, 0x31, 0x91, 0xcd, 0x9c,
	0x88, 0x43, 0x2a, 0x1c, 0x16, 0x64, 0xe5, 0xf1, 0x14, 0xea, 0x71, 0x86, 0xea, 0xf9, 0x91, 0x1d,
	0x46, 0x4d, 0x83, 0xd9, 0x08, 0xd9, 0x86, 0x92, 0x18, 0xe7, 0xc3, 0x47, 0xfa, 0xbb, 0x26, 0xc6,
	0x6a, 0xf4, 0x2c, 0x3b, 0x5b, 0x5c, 0x76, 0x16, 0xef, 0xc1, 0xe6, 0x9c, 0x54, 0x78, 0x71, 0x91,
	0x50, 0xa1, 0xd3, 0xba, 0x31, 0x15, 0x3c, 0x51, 0x70, 0xe3, 0xd7, 0x06, 0x6c, 0x4f, 0x1d, 0x1d,
	0xd0, 0x98, 0x39, 0x01, 0xfb, 0x25, 0xf5, 0x94, 0xaf, 0xcf, 0x61, 0x63, 0x3a, 0x4e, 0x17, 0xbc,
	0x5d, 0x9f, 0xc2, 0x99, 0xbf, 0x0f, 0xa1, 0x32, 0x45, 0xb4, 0xc7, 0x33, 0x40, 0x95, 0xec, 0xd4,
	0xb0, 0x2d, 0xc6, 0xca, 0x67, 0x59, 0xb2, 0xb3, 0xdd, 0xc6, 0x8d, 0xdf, 0x19, 0x50, 0xeb, 0x7a,
	0x94, 0x0b, 0x26, 0x26, 0xf9, 0x7b, 0x48, 0xbd, 0x93, 0xf4, 0x70, 0xc9, 0x16, 0x18, 0xc3, 0x4a,
	0x9a, 0xd0, 0x58, 0x5f, 0xf7, 0xea, 0xb7, 0xc4, 0xfc, 0x30, 0x11, 0xca, 0x6c, 0x85, 0xa8, 0xdf,
	0x12, 0x8b, 0xc2, 0x38, 0x8b, 0xba, 0x42, 0xd4, 0x6f, 0x85, 0xc9, 0x5b, 0x6f, 0x55, 0x63, 0xf2,
	0xa6, 0xdb, 0x86, 0xd5, 0x2c, 0xb0, 0xb5, 0xfc, 0x6d, 0x90, 0xad, 0x1b, 0x6f, 0x01, 0xfa, 0x61,
	0xc0, 0xdc, 0x89, 0x7e, 0xd6, 0x54, 0x23, 0xb5, 0x9a, 0x7f, 0x8d, 0x40, 0x06, 0xa9, 0xf7, 0x88,
	0x09, 0x25, 0xca, 0x9d, 0xf3, 0x80, 0x7a, 0xca, 0xb5, 0x32, 0xc9, 0x97, 0x8d, 0x7f, 0x1b, 0x50,
	0x9b, 0x6f, 0x7d, 0xfc, 0x53, 0x30, 0xf5, 0xf5, 0x3d, 0x9d, 0x13, 0x31, 0x4d, 0xa2, 0x90, 0x27,
	0x99, 0xe1, 0x6a, 0x6b, 0xbb, 0x39, 0x50, 0x02, 0xb9, 0x1a, 0xd1, 0x34, 0xb9, 0x9b, 0xdc, 0x8a,
	0xe3, 0xd7, 0xb0, 0x75, 0xcd, 0x84, 0xef, 0xc5, 0xce, 0xb5, 0x13, 0xd8, 0xb3, 0x57, 0x93, 0xca,
	0xd2, 0x7e, 0xe9, 0x0d, 0x13, 0x12, 0x23, 0x78, 0x26, 0x74, 0x90, 0x3f, 0xa4, 0x5e, 0x2c, 0xa8,
	0xce, 0xc6, 0x76, 0x51, 0x8d, 0xed, 0x39, 0x8d, 0x76, 0x3e, 0xc0, 0x77, 0x01, 0xe9, 0xd1, 0x39,
	0x93, 0x5e, 0x51, 0xd2, 0xeb, 0x19, 0x9e, 0x4b, 0xee, 0xfd, 0xa9, 0x00, 0xd5, 0x23, 0x87, 0x05,
	0x69, 0x9c, 0x45, 0xfe, 0x08, 0xee, 0xe9, 0xa5, 0x7d, 0xca, 0xe9, 0x38, 0xa2, 0xae, 0x98, 0xbe,
	0x53, 0x90, 0x81, 0xef, 0xc3, 0xdd, 0x9c, 0x7e, 0x93, 0x0a, 0x11, 0xf2, 0x8e, 0x16, 0x41, 0x05,
	0xbc, 0x0d, 0x77, 0x72, 0x6e, 0x30, 0xe1, 0xc2, 0x19, 0x77, 0xe2, 0x38, 0x8c, 0x51, 0x11, 0x3f,
	0x80, 0xed, 0x9c, 0x68, 0xab, 0xc6, 0x3c, 0x70, 0xb8, 0x4b, 0x83, 0x80, 0x7a, 0x68, 0x65, 0x5e,
	0xab, 0xcf, 0x66, 0xe6, 0x56, 0xb1, 0x09, 0x5b, 0x73, 0xc4, 0x4c, 0x65, 0x0d, 0xdf, 0x05, 0x3c,
	0xc7, 0x74, 0xf9, 0x95, 0x13, 0x30, 0x0f, 0x95, 0xf0, 0x43, 0x30, 0x73, 0x5c, 0x83, 0x83, 0xbc,
	0xc0, 0x51, 0x19, 0x6f, 0x42, 0x3d, 0x67, 0x4f, 0x84, 0x4f, 0x63, 0x54, 0x99, 0x8f, 0xa6, 0x17,
	0x8a, 0x0e, 0x0f, 0xd3, 0xa1, 0x7f, 0x94, 0x72, 0x2f, 0x41, 0x70, 0x83, 0xeb, 0x72, 0x26, 0x74,
	0x23, 0xa0, 0x2a, 0xbe, 0x07, 0x5f, 0xe6, 0xdc, 0x11, 0x8b, 0x47, 0xd7, 0x4e, 0x4c, 0xb3, 0x58,
	0xdd, 0xbd, 0xdf, 0x1a, 0x80, 0x6e, 0xde, 0x87, 0x18, 0x41, 0xad, 0xdf, 0xfe, 0xb9, 0x75, 0xa2,
	0x9f, 0x00, 0xe8, 0x0b, 0x7c, 0x07, 0x36, 0x14, 0x32, 0x38, 0x20, 0xdd, 0xbe, 0x75, 0xdc, 0x1e,
	0x1c, 0x23, 0x43, 0x7a, 0xa8, 0xc0, 0x0f, 0xa7, 0xef, 0xad, 0xee, 0xa0, 0xfb, 0x16, 0x15, 0xa6,
	0xd0, 0x49, 0x9f, 0x74, 0xac, 0x53, 0xd2, 0x43, 0xc5, 0xa9, 0xb1, 0x8f, 0x5d, 0xab, 0x27, 0x8d,
	0xad, 0xe0, 0x2d, 0x40, 0x0a, 0xe9, 0xb7, 0x06, 0xc7, 0x39, 0xba, 0xba, 0x17, 0xc0, 0xc6, 0x8d,
	0x87, 0x88, 0x54, 0x9d, 0x7f, 0x8a, 0xa0, 0x2f, 0xa4, 0x7d, 0x85, 0x4c, 0xb7, 0x34, 0x70, 0x0d,
	0xca, 0x9d, 0x33, 0xab, 0x43, 0x7a, 0xed, 0xf7, 0xa8, 0x30, 0x55, 0xc9, 0xed, 0x16, 0xe5, 0x6e,
	0x0a, 0x99, 0xdf, 0x6d, 0x65, 0xef, 0x14, 0xaa, 0x7a, 0x40, 0xa9, 0x9d, 0xaa, 0x50, 0xb2, 0xce,
	0xba, 0xbd, 0xfe, 0xa9, 0x85, 0xbe, 0x90, 0x16, 0xad, 0xb3, 0x93, 0x53, 0x4b, 0xae, 0x0c, 0x0c,
	0xb0, 0x66, 0x9d, 0x7d, 0xe8, 0x58, 0x6d, 0x54, 0xc0, 0xeb, 0x00, 0xd6, 0xd9, 0x51, 0xb7, 0xd7,
	0x1d, 0x1c, 0x77, 0x0e, 0x51, 0x11, 0x6f, 0x40, 0xd5, 0x3a, 0xeb, 0x9c, 0x59, 0xa4, 0x7d, 0xd8,
	0xb6, 0xda, 0x68, 0x65, 0xef, 0x08, 0x36, 0x97, 0xee, 0x72, 0x5c, 0x81, 0x55, 0xe5, 0x81, 0x36,
	0x4d, 0xda, 0xbd, 0xc1, 0x51, 0x87, 0x64, 0xa6, 0x0f, 0x8e, 0xdb, 0xbd, 0xb7, 0x1d, 0x54, 0xc8,
	0xc2, 0xd0, 0xab, 0xe2, 0xde, 0xbf, 0x4a, 0xb0, 0x99, 0x15, 0xec, 0xbc, 0x97, 0xdb, 0x70, 0x67,
	0x01, 0xd4, 0x85, 0x61, 0xe0, 0x06, 0x3c, 0x5e, 0x24, 0x8e, 0x28, 0x3d, 0xb9, 0xa2, 0xb1, 0xe5,
	0xc7, 0x34, 0xf1, 0xc3, 0x40, 0x96, 0xfb, 0x13, 0x78, 0xb0, 0x28, 0x73, 0x10, 0xf2, 0x0b, 0x16,
	0x8f, 0x32, 0x7f, 0x51, 0x51, 0xb6, 0xd2, 0xa2, 0x00, 0xa1, 0x09, 0x15, 0x87, 0xf4, 0x8a, 0xb9,
	0x14, 0xad, 0x2c, 0xd3, 0x5a, 0xff, 0x63, 0x18, 0xcb, 0xf2, 0x7f, 0x08, 0xe6, 0x22, 0xfd, 0x91,
	0x45, 0x54, 0x2b, 0xaf, 0x2d, 0x2b, 0xf7, 0xe3, 0x50, 0x50, 0x57, 0x1c, 0x38, 0x41, 0x80, 0x4a,
	0xb2, 0x77, 0x16, 0x69, 0xd9, 0x08, 0xd6, 0x18, 0x95, 0x97, 0xbd, 0xce, 0x0b, 0xf8, 0xc0, 0xa7,
	0xee, 0x25, 0xaa, 0xc8, 0xda, 0x5e, 0x14, 0xd0, 0x99, 0x47, 0xf0, 0x69, 0xdd, 0x4e, 0xec, 0x24,
	0x14, 0x55, 0xf1, 0x1e, 0x7c, 0x7d, 0x6b, 0x48, 0xea, 0x4e, 0xbe, 0xa0, 0xb1, 0x15, 0xea, 0x2f,
	0x18, 0x54, 0xc3, 0xff, 0x07, 0xcf, 0xff, 0x87, 0x6c, 0xfe, 0x45, 0x81, 0xea, 0xb7, 0xe4, 0x4a,
	0x0d, 0xd7, 0xf7, 0xce, 0x39, 0x0d, 0xd0, 0x3a, 0xde, 0x81, 0x87, 0xb7, 0xd3, 0x7c, 0x98, 0xca,
	0xb9, 0xb5, 0xb1, 0x7c, 0xa0, 0x1d, 0x35, 0xfa, 0xfb, 0x4e, 0x92, 0x44, 0xbe, 0xf2, 0x1e, 0xe1,
	0xa7, 0xf0, 0x64, 0x51, 0xe6, 0x90, 0x25, 0x37, 0x84, 0x36, 0xf1, 0x73, 0x78, 0x7a, 0xd3, 0x90,
	0x1b, 0x4f, 0x22, 0xd1, 0xe6, 0x6a, 0xd8, 0xe4, 0x93, 0x12, 0x2f, 0xfb, 0xa4, 0x05, 0x73, 0x89,
	0x3b, 0xcb, 0x3e, 0x75, 0x47, 0xf2, 0x0e, 0xec, 0x4f, 0x3f, 0xed, 0xd1, 0x16, 0xde, 0x85, 0x67,
	0xb7, 0xc9, 0x10, 0xea, 0x86, 0x57, 0x34, 0x9e, 0x0c, 0x28, 0x17, 0xf2, 0x4b, 0x04, 0x7d, 0x89,
	0x1f, 0xc3, 0xfd, 0xe5, 0x23, 0xcf, 0x6f, 0x6b, 0x74, 0x57, 0x0e, 0xcd, 0x1b, 0x15, 0xc3, 0xf8,
	0x10, 0x6d, 0xcb, 0xe1, 0x7c, 0xb3, 0x4a, 0x47, 0xe1, 0x15, 0xed, 0x33, 0x8e, 0xcc, 0x65, 0x32,
	0x4b, 0xac, 0x24, 0xef, 0xdd, 0x42, 0xc6, 0xd4, 0x11, 0x8a, 0xbc, 0xbf, 0x5c, 0xbe, 0x6f, 0xa9,
	0xe8, 0x70, 0x11, 0x87, 0xd1, 0x04, 0x3d, 0x58, 0x3e, 0xcf, 0xf9, 0xdc, 0x3d, 0x5c, 0x2e, 0xb4,
	0x76, 0x14, 0x05, 0x13, 0x75, 0xd7, 0x33, 0x9a, 0xa0, 0x47, 0xb7, 0x07, 0x9b, 0x5f, 0xb9, 0xe8,
	0xf1, 0xde, 0xaf, 0x60, 0xab, 0xcf, 0xf8, 0x07, 0x47, 0xc4, 0x6c, 0x3c, 0xdf, 0xf0, 0x3b, 0xf0,
	0xf0, 0x36, 0xdc, 0x3e, 0x48, 0xe3, 0x98, 0x72, 0x81, 0x0c, 0xfc, 0x15, 0x3c, 0xba, 0x55, 0xa2,
	0x47, 0xaf, 0x8f, 0x58, 0x9c, 0x08, 0x54, 0x90, 0xe7, 0xf6, 0x29, 0x91, 0x01, 0x75, 0x43, 0xee,
	0xa1, 0xe2, 0xfe, 0x8f, 0xa0, 0x74, 0xcd, 0xd4, 0x8b, 0x0c, 0x7f, 0xd5, 0xcc, 0xfe, 0x76, 0x6a,
	0xe6, 0x7f, 0x3b, 0x35, 0x3b, 0x3c, 0x1d, 0xfd, 0xcc, 0x09, 0x52, 0x7a, 0x12, 0xc9, 0xdb, 0x30,
	0x31, 0xff, 0xf2, 0x9b, 0xa2, 0x7a, 0x90, 0xac, 0x49, 0x9d, 0x2e, 0xdf, 0xff, 0x31, 0x94, 0x95,
	0x76, 0x98, 0x8a, 0xcf, 0x51, 0xff, 0xab, 0x56, 0x57, 0x5b, 0x9e, 0xa4, 0x62, 0xff, 0x2d, 0xd4,
	0x95, 0xbe, 0x47, 0xcf, 0xd3, 0xe1, 0x67, 0xfa, 0xf0, 0x37, 0x6d, 0xa4, 0x2a, 0x35, 0x0f, 0xa5,
	0x62, 0x97, 0xef, 0x77, 0x61, 0x7d, 0xce, 0xd0, 0x67, 0xba, 0xf3, 0x77, 0x6d, 0xa9, 0x36, 0xb5,
	0x74, 0x92, 0x8a, 0x37, 0xdf, 0xc0, 0x7d, 0x37, 0x1c, 0x35, 0x2f, 0x29, 0x8d, 0x2e, 0xe9, 0xa4,
	0xe9, 0xa9, 0x49, 0xa6, 0x8c, 0xb8, 0x61, 0xf0, 0xa6, 0xfa, 0x8e, 0xd2, 0xe8, 0x1d, 0x55, 0x2f,
	0xb9, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x31, 0xc2, 0x2f, 0xb5, 0x13, 0x00, 0x00,
}
